CREATE TABLE "leads" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"source" text DEFAULT 'full_check',
	"full_name" text,
	"email" text NOT NULL,
	"preferred_language" text,
	"current_country" text,
	"passport_country" text,
	"age" text,
	"occupation" text,
	"english_level" text,
	"english_test_taken" text,
	"occupation_confirmed" text,
	"estimated_budget_range" text,
	"timeline" text,
	"sponsor_or_family" text,
	"biggest_concern" text,
	"main_goal" text,
	"selected_visa" text,
	"system_score" integer,
	"lead_score" integer,
	"lead_tier" text,
	"report_id" uuid,
	"report_locale" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);