/**
 * Nursing skills assessment (Anmac) for the occupations the registry assigns to ANMAC, read from the git-committed
 * extraction src/data/health-registration/anmac-fees.json (generated by scripts/generate-anmac-fees.ts from
 * data/knowledge/Skill Assessments/Anmac/Anmac.pdf; provenance facts anmac_* / nmba_* in src/data/fee-provenance.json).
 *
 * The document prices three Anmac assessments by the applicant's REGISTRATION status, not by occupation (only the
 * Direct care assessment is occupation-restricted, to ANZSCO 423312/423313 -- neither is an ANMAC occupation in the
 * registry). So the choice here is:
 *   - Australian qualification -> Modified skills assessment (AUD 395). Assumes current NMBA/Ahpra registration,
 *     which that assessment requires; said so in the report text.
 *   - Otherwise, registered-nurse-level occupations -> Full skills assessment (AUD 595), conditional on being
 *     (or having been) registered as a nurse in one of the seven countries the document lists -- stated in the report.
 *   - Otherwise, Enrolled Nurse 411411 -> no amount ("needs human verification"): the Full assessment requires anyone
 *     without a Bachelor of Nursing from the listed countries to have 1,800 hours of paid REGISTERED nurse work
 *     experience, so the document does not clearly cover an overseas-registered enrolled nurse.
 * The NMBA application and registration fees for international applications are named in the document with no
 * amount and are never shown as a number. This replaces the earlier unsourced AUD 1,000 / 12-week placeholder.
 */
import data from "@/src/data/health-registration/anmac-fees.json";

type Locale = "en" | "tr" | "zh-Hans";
type Fee = (typeof data.fees)[number];

export const ANMAC_FEES_SOURCE = {
  document: data.sourceDocument,
  title: data.sourceTitle,
  extractedDate: data.extractedDate,
} as const;

export function anmacFee(id: string): Fee {
  const fee = data.fees.find((f) => f.id === id);
  if (!fee) throw new Error(`anmac-fees.json has no "${id}" -- regenerate it (scripts/generate-anmac-fees.ts)`);
  return fee;
}

const FULL = anmacFee("anmac_full_skills_assessment");
const MODIFIED = anmacFee("anmac_modified_skills_assessment");
const IQNM = anmacFee("nmba_iqnm_assessment_fee");
const FULL_NURSING = (() => {
  const n = FULL.eligibility?.nursing;
  if (!n) throw new Error("anmac-fees.json: Full skills assessment has no nursing eligibility -- regenerate it (scripts/generate-anmac-fees.ts)");
  return n;
})();

/** Registered-nurse-level ANMAC occupations: mapped to the Full skills assessment for overseas-qualified applicants. */
export const FULL_SKILLS_ASSESSMENT_CODES: ReadonlySet<string> = new Set([
  "254211", // Nurse Educator
  "254212", // Nurse Researcher
  "254311", // Nurse Manager
  "254411", // Nurse Practitioner
  "254412", "254413", "254414", "254415", "254416", "254418", "254422", "254423", "254425", "254499", // Registered Nurse specialisations / nec
]);

type Localized = Readonly<Record<Locale, string>>;

/** ANMAC occupations the document does not clearly price for an overseas-qualified applicant. */
export const UNMAPPED_CODES: Readonly<Record<string, Localized>> = {
  "411411": {
    en: "Enrolled Nurse: the Full skills assessment requires anyone whose qualification is not a Bachelor of Nursing from Canada, Hong Kong, Ireland, the United Kingdom or the United States to have 1,800 hours of paid registered nurse work experience since 1 January 2017, so the document does not clearly cover an overseas enrolled nurse. It names 411411 only under the Modified skills assessment (current Australian/NZ registration).",
    tr: "Enrolled Nurse (kayıtlı yardımcı hemşire): Full beceri değerlendirmesi, niteliği Kanada, Hong Kong, İrlanda, Birleşik Krallık veya ABD'den bir Bachelor of Nursing olmayan herkesten 1 Ocak 2017'den beri 1.800 saat ücretli registered nurse deneyimi ister; bu yüzden belge yurt dışındaki bir enrolled nurse'ü açıkça kapsamıyor. 411411 kodunu yalnızca Modified beceri değerlendirmesi altında (güncel Avustralya/Yeni Zelanda kaydı) anıyor.",
    "zh-Hans": "注册登记护士（Enrolled Nurse）：完整技能评估要求学历不是来自加拿大、香港、爱尔兰、英国或美国护理学士（Bachelor of Nursing）的申请人自 2017 年 1 月 1 日起具备 1,800 小时带薪注册护士（registered nurse）工作经验，因此文件并未明确涵盖海外的 enrolled nurse。文件仅在修改版技能评估（需目前在澳大利亚/新西兰注册）下列出 411411。",
  },
};

const UNMATCHED: Localized = {
  en: "The occupation could not be matched to a nursing ANZSCO code, so no Anmac assessment fee is assumed.",
  tr: "Meslek bir hemşirelik ANZSCO koduyla eşleştirilemedi; bu yüzden bir Anmac değerlendirme ücreti varsayılmadı.",
  "zh-Hans": "无法将该职业匹配到护理类 ANZSCO 代码，因此不假定任何 Anmac 评估费用。",
};

export type AnmacAssessmentId = "full" | "modified" | "unmapped";

export type AnmacAssessment = {
  assessmentId: AnmacAssessmentId;
  /** The fee row from anmac-fees.json; absent when unmapped. */
  fee?: Fee;
  /** Why no fee is shown (unmapped only). */
  unmappedReason?: Localized;
  waitWeeks?: { min: number; max: number; page: number };
};

export function resolveAnmacAssessment(input: { anzscoCode?: string; qualificationAwardedInAustralia?: boolean }): AnmacAssessment {
  const code = input.anzscoCode ?? "";
  const wait = (f: Fee) => ({ min: f.waitTimeToStart!.minWeeks, max: f.waitTimeToStart!.maxWeeks, page: f.waitTimeToStart!.page });
  if (input.qualificationAwardedInAustralia === true) return { assessmentId: "modified", fee: MODIFIED, waitWeeks: wait(MODIFIED) };
  if (FULL_SKILLS_ASSESSMENT_CODES.has(code)) return { assessmentId: "full", fee: FULL, waitWeeks: wait(FULL) };
  return {
    assessmentId: "unmapped",
    unmappedReason: UNMAPPED_CODES[code] ?? UNMATCHED,
  };
}

// ── report text ──────────────────────────────────────────────────────────────────────────────────────
const aud = (n: number) => `AUD ${n.toLocaleString("en-AU")}`;
const pick = (locale: Locale, en: string, tr: string, zh: string) => (locale === "tr" ? tr : locale === "zh-Hans" ? zh : en);
const COUNTRIES = FULL_NURSING.registeredIn.join(", ");

/** "Anmac document, p.26" in the report's language. */
function cite(locale: Locale, page: number): string {
  return pick(locale, `Anmac.pdf, p.${page}`, `Anmac.pdf, s.${page}`, `Anmac.pdf，第 ${page} 页`);
}

/**
 * "AUD 595 (Anmac.pdf, p.26)": the amount and where the document states it. No "$" quote on purpose -- the PDF
 * renderer strips "$" before digits (cleanNum in lib/readiness/generate-pdf.ts), which would turn the document's
 * "Fee: $595 AUD" into a misquote. The verbatim quotes live in anmac-fees.json and fee-provenance.json.
 */
export function anmacFeeCitation(fee: { amountAud: number; page: number }, locale: Locale): string {
  return pick(locale, `${aud(fee.amountAud)} (${cite("en", fee.page)})`, `${aud(fee.amountAud)} (${cite("tr", fee.page)})`, `${aud(fee.amountAud)}（${cite("zh-Hans", fee.page)}）`);
}

/** Amount cell: short, the PDF draws it as one right-aligned line. */
export function anmacAmountLabel(a: AnmacAssessment, locale: Locale): string {
  if (a.fee) return aud(a.fee.amountAud);
  return pick(locale, "Not stated -- confirm with Anmac", "Belirtilmemiş -- Anmac ile teyit edin", "未注明——请向 Anmac 确认");
}

function waitLine(a: AnmacAssessment, locale: Locale): string {
  if (!a.waitWeeks) return "";
  const { min, max, page } = a.waitWeeks;
  return pick(
    locale,
    ` Current wait time for the assessment to start: ${min}–${max} weeks (${cite("en", page)}; the document gives no completion time).`,
    ` Değerlendirmenin başlaması için güncel bekleme süresi: ${min}–${max} hafta (${cite("tr", page)}; belge tamamlanma süresi vermiyor).`,
    ` 评估开始前的当前等待时间：${min}–${max} 周（${cite("zh-Hans", page)}；文件未给出完成时间）。`,
  );
}

/** Roadmap explanation: which assessment, its exact scope in the document's words, wait time, the source. */
export function anmacExplanation(a: AnmacAssessment, locale: Locale, authorityLabel: string): string {
  const source = pick(
    locale,
    ` Assessing authority: ${authorityLabel}. Source: ${data.sourceDocument.split("/").pop()} (Ahpra / NMBA and Anmac pages; no effective date stated).`,
    ` Değerlendirme kurumu: ${authorityLabel}. Kaynak: ${data.sourceDocument.split("/").pop()} (Ahpra / NMBA ve Anmac sayfaları; yürürlük tarihi belirtilmemiş).`,
    ` 评估机构：${authorityLabel}。来源：${data.sourceDocument.split("/").pop()}（Ahpra / NMBA 及 Anmac 页面；未注明生效日期）。`,
  );
  if (a.assessmentId === "full") {
    return (
      pick(
        locale,
        `Anmac Full skills assessment: ${anmacFeeCitation(FULL, "en")}. Scope, in the document's words: "${FULL.appliesTo}" For nurses this means currently or previously registered as a nurse in ${COUNTRIES}; if your qualification is not a Bachelor of Nursing from ${FULL_NURSING.additionalIfNotBachelorOfNursingFrom}, you also need a qualification leading to general nursing registration after 1 January 2017 and 1,800 hours of paid registered nurse work experience since then in that country. If you are currently registered in Australia or New Zealand instead, the Modified skills assessment (${aud(MODIFIED.amountAud)}, p.${MODIFIED.page}) applies. If you are registered only in another country, the document states no Anmac assessment for you -- confirm with Anmac.`,
        `Anmac Tam (Full) beceri değerlendirmesi: ${anmacFeeCitation(FULL, "tr")}. Kapsam, belgenin ifadesiyle: "${FULL.appliesTo}" Hemşireler için bu, ${COUNTRIES} ülkelerinden birinde hemşire olarak halen veya daha önce kayıtlı olmak demektir; niteliğiniz ${FULL_NURSING.additionalIfNotBachelorOfNursingFrom} kaynaklı bir Bachelor of Nursing değilse, ayrıca 1 Ocak 2017'den sonra genel hemşirelik kaydına götüren bir nitelik ve o tarihten beri aynı ülkede 1.800 saat ücretli kayıtlı hemşire (registered nurse) deneyimi gerekir. Bunun yerine şu anda Avustralya veya Yeni Zelanda'da kayıtlıysanız Modified beceri değerlendirmesi (${aud(MODIFIED.amountAud)}, s.${MODIFIED.page}) uygulanır. Yalnızca başka bir ülkede kayıtlıysanız belge sizin için bir Anmac değerlendirmesi belirtmiyor -- Anmac ile teyit edin.`,
        `Anmac 完整技能评估（Full skills assessment）：${anmacFeeCitation(FULL, "zh-Hans")}。适用范围（文件原文）："${FULL.appliesTo}" 对护士而言，即目前或曾经在以下国家/地区注册为护士：${COUNTRIES}；如您的学历不是来自 ${FULL_NURSING.additionalIfNotBachelorOfNursingFrom} 的护理学士（Bachelor of Nursing），还需持有 2017 年 1 月 1 日之后获得、可取得普通护士注册的学历，并自该日起在同一国家累计 1,800 小时带薪注册护士工作经验。如您目前在澳大利亚或新西兰注册，则适用修改版技能评估（Modified，${aud(MODIFIED.amountAud)}，第 ${MODIFIED.page} 页）。如仅在其他国家注册，文件未说明适用的 Anmac 评估——请向 Anmac 确认。`,
      ) +
      waitLine(a, locale) +
      source
    );
  }
  if (a.assessmentId === "modified") {
    return (
      pick(
        locale,
        `Anmac Modified skills assessment: ${anmacFeeCitation(MODIFIED, "en")}. Scope, in the document's words: "${MODIFIED.appliesTo}" Assumed because your qualification is Australian; it requires current registration with NMBA/Ahpra, the Nursing Council of New Zealand or the Midwifery Council of New Zealand. Without that registration this assessment does not apply -- confirm with Anmac.`,
        `Anmac Modified beceri değerlendirmesi: ${anmacFeeCitation(MODIFIED, "tr")}. Kapsam, belgenin ifadesiyle: "${MODIFIED.appliesTo}" Niteliğiniz Avustralya'dan olduğu için varsayıldı; NMBA/Ahpra, Yeni Zelanda Hemşirelik Konseyi veya Yeni Zelanda Ebelik Konseyi nezdinde güncel kayıt gerektirir. Bu kayıt yoksa bu değerlendirme uygulanmaz -- Anmac ile teyit edin.`,
        `Anmac 修改版技能评估（Modified skills assessment）：${anmacFeeCitation(MODIFIED, "zh-Hans")}。适用范围（文件原文）："${MODIFIED.appliesTo}" 因您的学历在澳大利亚获得而假定适用；该评估要求目前在 NMBA/Ahpra、新西兰护理委员会（NCNZ）或新西兰助产委员会（MCNZ）注册。如无此注册，则不适用——请向 Anmac 确认。`,
      ) +
      waitLine(a, locale) +
      source
    );
  }
  return (
    pick(
      locale,
      `No Anmac fee is shown for this profile: it needs human verification. ${a.unmappedReason!.en} For reference, the document's Anmac fees are: Full skills assessment ${aud(FULL.amountAud)} (p.${FULL.page}), Modified skills assessment ${aud(MODIFIED.amountAud)} (p.${MODIFIED.page}).`,
      `Bu profil için Anmac ücreti gösterilmiyor: insan tarafından doğrulanması gerekiyor. ${a.unmappedReason!.tr} Bilgi için belgedeki Anmac ücretleri: Full beceri değerlendirmesi ${aud(FULL.amountAud)} (s.${FULL.page}), Modified beceri değerlendirmesi ${aud(MODIFIED.amountAud)} (s.${MODIFIED.page}).`,
      `此情况不显示 Anmac 费用：需人工核实。${a.unmappedReason!["zh-Hans"]} 供参考，文件中的 Anmac 费用为：完整技能评估 ${aud(FULL.amountAud)}（第 ${FULL.page} 页），修改版技能评估 ${aud(MODIFIED.amountAud)}（第 ${MODIFIED.page} 页）。`,
    ) + source
  );
}

/**
 * The separate registration line (never in any total): the NMBA IQNM assessment fee is real, the NMBA
 * application and registration fees are named with no amount. Registration is needed to work as a nurse,
 * not for the Anmac skills assessment itself.
 */
export function nursingRegistrationLine(locale: Locale): { category: string; amountLabel: string; explanation: string } {
  const intl = data.notStated.find((f) => f.id === "nmba_international_application_fee")!;
  return {
    category: pick(
      locale,
      "Nursing registration (Ahpra / NMBA) -- to work as a nurse; not included in the total",
      "Hemşirelik kaydı (Ahpra / NMBA) -- hemşire olarak çalışmak için; toplama dahil değil",
      "护士注册（Ahpra / NMBA）——用于执业；未计入总额",
    ),
    amountLabel: pick(locale, `AUD ${IQNM.amountAud} + fees not published`, `AUD ${IQNM.amountAud} + yayımlanmamış ücretler`, `AUD ${IQNM.amountAud} + 未公布费用`),
    explanation: pick(
      locale,
      `Separate from the Anmac skills assessment. After the Self-check, Ahpra charges a non-refundable IQNM assessment fee (assessment and orientation) of ${aud(IQNM.amountAud)} if you are assigned to Stream A or B or your qualification has not yet been assessed (Anmac.pdf, pp.${IQNM.pages?.join("-")}, Self-check section). The NMBA application fee and registration fee for international applications are named but no amount is given (p.${intl.reason.match(/p\.(\d+)/)?.[1]}) -- confirm them with Ahpra; Stream B exam (MCQ, OSCE) fees are not stated either.`,
      `Anmac beceri değerlendirmesinden ayrıdır. Self-check sonrasında Stream A veya B'ye atanırsanız ya da niteliğiniz henüz değerlendirilmemişse Ahpra ${aud(IQNM.amountAud)} tutarında iade edilmeyen bir IQNM değerlendirme ücreti (değerlendirme ve oryantasyon) alır (Anmac.pdf, s.${IQNM.pages?.join("-")}, Self-check bölümü). Uluslararası başvurular için NMBA başvuru ücreti ve kayıt ücreti belgede adıyla geçer ancak tutar verilmez (s.${intl.reason.match(/p\.(\d+)/)?.[1]}) -- Ahpra ile teyit edin; Stream B sınav (MCQ, OSCE) ücretleri de belirtilmemiştir.`,
      `与 Anmac 技能评估分开。完成 Self-check 后，如被分配到 Stream A 或 B，或您的学历尚未评估，Ahpra 收取不可退还的 IQNM 评估费（评估及入门培训）${aud(IQNM.amountAud)}（Anmac.pdf，第 ${IQNM.pages?.join("-")} 页，Self-check 部分）。国际申请的 NMBA 申请费和注册费在文件中有提及但未给出金额（第 ${intl.reason.match(/p\.(\d+)/)?.[1]} 页）——请向 Ahpra 确认；Stream B 考试（MCQ、OSCE）费用亦未注明。`,
    ),
  };
}

/** The assessment choice in 4 sentences, for the FAQ (authority note), the Application Guide and the registry. */
export const ANMAC_ASSESSMENT_PROCESS: Readonly<Record<Locale, string>> = {
  en:
    `Anmac assesses nurses and midwives for skilled migration; registration to practise is a separate application to Ahpra / the Nursing and Midwifery Board of Australia. ` +
    `Nurses currently or previously registered in ${COUNTRIES} apply for the Full skills assessment (${aud(FULL.amountAud)}); nurses and midwives currently registered in Australia or New Zealand apply for the Modified skills assessment (${aud(MODIFIED.amountAud)}). ` +
    `The current wait time for either assessment to start is ${FULL.waitTimeToStart!.minWeeks}–${FULL.waitTimeToStart!.maxWeeks} weeks, and the outcome letter is valid for 2 years. ` +
    `(Source: ${data.sourceDocument.split("/").pop()}, pp.${FULL.page}, ${MODIFIED.page}.)`,
  tr:
    `Anmac, nitelikli göç için hemşire ve ebeleri değerlendirir; çalışma kaydı Ahpra / Nursing and Midwifery Board of Australia'ya yapılan ayrı bir başvurudur. ` +
    `${COUNTRIES} ülkelerinden birinde halen veya daha önce kayıtlı hemşireler Full beceri değerlendirmesine (${aud(FULL.amountAud)}); Avustralya veya Yeni Zelanda'da halen kayıtlı hemşire ve ebeler Modified beceri değerlendirmesine (${aud(MODIFIED.amountAud)}) başvurur. ` +
    `Her iki değerlendirmenin başlaması için güncel bekleme süresi ${FULL.waitTimeToStart!.minWeeks}–${FULL.waitTimeToStart!.maxWeeks} haftadır ve sonuç mektubu 2 yıl geçerlidir. ` +
    `(Kaynak: ${data.sourceDocument.split("/").pop()}, s.${FULL.page}, ${MODIFIED.page}.)`,
  "zh-Hans":
    `Anmac 为技术移民评估护士和助产士；执业注册是向 Ahpra / 澳大利亚护理和助产委员会（NMBA）提交的另一项申请。` +
    `目前或曾经在 ${COUNTRIES} 注册的护士申请完整技能评估（${aud(FULL.amountAud)}）；目前在澳大利亚或新西兰注册的护士和助产士申请修改版技能评估（${aud(MODIFIED.amountAud)}）。` +
    `两项评估开始前的当前等待时间为 ${FULL.waitTimeToStart!.minWeeks}–${FULL.waitTimeToStart!.maxWeeks} 周，评估结果信有效期 2 年。` +
    `（来源：${data.sourceDocument.split("/").pop()}，第 ${FULL.page}、${MODIFIED.page} 页。）`,
};
