/**
 * Medical registration (Ahpra / Medical Board of Australia) for occupations assessed by AHPRA, read from the
 * git-committed extraction src/data/health-registration/img-pathways.json (generated by
 * scripts/generate-img-pathways.ts from the Medical Board / Ahpra document "Pathways to registration for
 * international medical graduates"; provenance in src/data/health-registration/provenance.json).
 *
 * The Medical Board application + registration fees are real figures from that document's "Schedule of fees
 * effective 1 August 2026". The AMC, ECFMG, specialist-college, CPD-home and assessment fees are NOT: the
 * document gives no amount for any of them and defers to the organisation ("Contact the AMC for fee
 * information."), so they are surfaced only as that deferral text -- never as a number.
 */
import data from "@/src/data/health-registration/img-pathways.json";
import amcFees from "@/src/data/health-registration/amc-fees.json";

type Block = { kind: "paragraph" | "bullet"; text: string };
type FeeRow = (typeof data.ahpraFeeSchedule.items)[number];
type Locale = "en" | "tr" | "zh-Hans";

export const IMG_PATHWAYS_SOURCE = {
  document: data.sourceDocument,
  title: data.sourceTitle,
  extractedDate: data.extractedDate,
  feeScheduleEffectiveDate: data.ahpraFeeSchedule.effectiveDate,
} as const;

export type MedicalRegistrationPathwayId = "expedited-specialist" | "specialist-recognition" | "standard" | "au-nz-graduate";

function feeRow(id: string): FeeRow {
  const row = data.ahpraFeeSchedule.items.find((r) => r.id === id);
  if (!row) throw new Error(`img-pathways.json has no fee-schedule row "${id}" -- regenerate it (scripts/generate-img-pathways.ts)`);
  return row;
}

function pathway(id: string) {
  const p = data.pathways.find((x) => x.id === id);
  if (!p) throw new Error(`img-pathways.json has no pathway "${id}"`);
  return p;
}

/** The bullets directly after a lead paragraph (e.g. the Expedited Specialist pathway's accepted-specialty list). */
function listAfter(blocks: Block[], lead: RegExp): string[] {
  const i = blocks.findIndex((b) => b.kind === "paragraph" && lead.test(b.text));
  if (i < 0) return [];
  const out: string[] = [];
  for (const b of blocks.slice(i + 1)) {
    if (b.kind !== "bullet") break;
    out.push(b.text.replace(/\.$/, ""));
  }
  return out;
}

/** The specialties currently on the Board's Expedited Specialist pathway accepted list, as the document states them. */
export const EXPEDITED_SPECIALTIES: readonly string[] = listAfter(
  pathway("expedited-specialist").eligibility as Block[],
  /^The current specialties on the list are:/,
);

// ANZSCO occupation -> the Expedited list specialty it corresponds to. Only unambiguous one-to-one matches; an
// entry only applies while the document still lists that specialty (checked against EXPEDITED_SPECIALTIES).
// Physician – general medicine has no dedicated ANZSCO code among the AHPRA occupations (the listed physician
// codes are sub-specialties such as cardiology), so no occupation maps to it.
const ANZSCO_TO_EXPEDITED_SPECIALTY: Readonly<Record<string, string>> = {
  "253111": "general practice",
  "253211": "anaesthesia",
  "253913": "obstetrics and gynaecology",
  "253321": "paediatrics and child health – general paediatrics",
  "253411": "psychiatry",
  "253917": "radiology – diagnostic radiology",
};

// Non-specialist doctors: the Standard pathway (the Competent Authority pathway only applies to graduates
// assessed in the UK, Canada, the USA, New Zealand or Ireland, which the intake form does not ask about).
const NON_SPECIALIST_CODES = new Set(["253112", "253999"]);

export type MedicalRegistrationFees = {
  pathwayId: MedicalRegistrationPathwayId;
  /** Name of the pathway in the document (English, as published). */
  pathwayName: string;
  /** The specialty on the Expedited list, when that is why this pathway was chosen. */
  expeditedSpecialty?: string;
  /** Registration applied for first, and the two Medical Board rows paid together at application. */
  registrationType: "specialist" | "limited" | "general";
  applicationFee: FeeRow;
  registrationFee: FeeRow;
  totalAud: number;
  /** A later Medical Board stage on the same pathway (specialist registration once college requirements are met). */
  laterStage?: { applicationFee: FeeRow; registrationFee: FeeRow; totalAud: number };
  /** An alternative first registration named by the document for the same pathway. */
  alternative?: { condition: string; applicationFee: FeeRow; registrationFee: FeeRow; totalAud: number };
  /** The document's own statements for every non-Medical-Board fee on this pathway -- no amounts. */
  deferredFees: Array<{ organisation: string; text: string; deferralText: string | null }>;
  /**
   * Standard pathway only: the AMC clinical examination fee, from the AMC's own pages (amc-fees.json) -- the
   * one AMC fee any source document states. In person is the low end, online the high end.
   */
  amcClinicalExam?: { inPersonAud: number; onlineAud: number; page: number; quote: string };
  /** Medical Board total, plus the AMC clinical examination where it applies (min = in person, max = online). */
  totalMinAud: number;
  totalMaxAud: number;
  sourcePages: number[];
};

const pair = (applicationId: string, registrationId: string) => {
  const applicationFee = feeRow(applicationId);
  const registrationFee = feeRow(registrationId);
  return { applicationFee, registrationFee, totalAud: applicationFee.nationalFeeAud + registrationFee.nationalFeeAud };
};

function amcFee(id: string) {
  const fee = amcFees.fees.find((f) => f.id === id);
  if (!fee) throw new Error(`amc-fees.json has no "${id}" -- regenerate it (scripts/generate-amc-fees.ts)`);
  return fee;
}

/** Adds totalMinAud/totalMaxAud: the Medical Board total, plus the AMC clinical examination when given. */
function withTotals<T extends { totalAud: number; amcClinicalExam?: MedicalRegistrationFees["amcClinicalExam"] }>(fees: T) {
  return {
    ...fees,
    totalMinAud: fees.totalAud + (fees.amcClinicalExam?.inPersonAud ?? 0),
    totalMaxAud: fees.totalAud + (fees.amcClinicalExam?.onlineAud ?? 0),
  };
}

/** Picks the pathway and the Medical Board fees that apply to this applicant (see the assumptions per branch). */
export function resolveMedicalRegistration(input: { anzscoCode?: string; qualificationAwardedInAustralia?: boolean }): MedicalRegistrationFees {
  const code = input.anzscoCode ?? "";
  const deferred = (id: string) =>
    data.unresolvedFees
      .filter((f) => f.pathwayId === id)
      .map((f) => ({ organisation: f.organisation, text: f.text, deferralText: f.deferralText }));

  // Australian/NZ-qualified doctors: general registration (after an accredited internship). The document covers
  // them only in its section for Australian/NZ graduates who also hold an overseas specialist qualification.
  if (input.qualificationAwardedInAustralia === true) {
    const p = pathway("au-nz-graduates-overseas-specialist");
    return withTotals({
      pathwayId: "au-nz-graduate",
      pathwayName: p.name,
      registrationType: "general",
      ...pair("application-fee-for-general-registration", "registration-fee-for-general-registration"),
      alternative: {
        condition: "no accredited internship completed in Australia or New Zealand: provisional registration",
        ...pair("application-fee-for-provisional-registration-for-australian-and-new-zealand-graduates", "registration-fee-for-provisional-registration"),
      },
      deferredFees: deferred(p.id),
      sourcePages: [...p.sourcePages, ...data.ahpraFeeSchedule.pages],
    });
  }

  const specialty = ANZSCO_TO_EXPEDITED_SPECIALTY[code];
  if (specialty && EXPEDITED_SPECIALTIES.includes(specialty)) {
    const p = pathway("expedited-specialist");
    return withTotals({
      pathwayId: "expedited-specialist",
      pathwayName: p.name,
      expeditedSpecialty: specialty,
      registrationType: "specialist",
      ...pair("application-fee-for-specialist-registration", "registration-fee-for-specialist-registration-for-practitioners-who-do-not-hold-general-registration"),
      deferredFees: deferred(p.id),
      sourcePages: [...p.sourcePages, ...data.ahpraFeeSchedule.pages],
    });
  }

  if (NON_SPECIALIST_CODES.has(code)) {
    const p = pathway("standard");
    return withTotals({
      pathwayId: "standard",
      pathwayName: p.name,
      registrationType: "limited",
      ...pair("application-fee-for-limited-registration", "registration-fee-for-limited-registration"),
      alternative: {
        condition: "both AMC exams (CAT MCQ and clinical) passed before applying: provisional registration",
        ...pair(
          "application-fee-for-provisional-registration-for-international-medical-graduates-graduates-outside-australia-and-new-zealand",
          "registration-fee-for-provisional-registration",
        ),
      },
      deferredFees: deferred(p.id),
      // The Standard pathway needs the AMC clinical examination or a workplace-based assessment; the exam is the
      // usual route ("Most non-specialist IMGs are assessed through this method"), and its fee is the one AMC fee
      // a source document states (amc-fees.json). The WBA and CAT MCQ fees stay unpriced.
      amcClinicalExam: {
        inPersonAud: amcFee("amc_clinical_exam_in_person").amountAud,
        onlineAud: amcFee("amc_clinical_exam_online").amountAud,
        page: amcFee("amc_clinical_exam_in_person").page,
        quote: amcFee("amc_clinical_exam_in_person").quote,
      },
      sourcePages: [...p.sourcePages, ...data.ahpraFeeSchedule.pages],
    });
  }

  // Every other AHPRA occupation is a specialty not on the Expedited list: college comparability assessment,
  // limited registration for supervised practice, then specialist registration.
  const p = pathway("specialist-recognition");
  return withTotals({
    pathwayId: "specialist-recognition",
    pathwayName: p.name,
    registrationType: "limited",
    ...pair("application-fee-for-limited-registration", "registration-fee-for-limited-registration"),
    laterStage: pair("application-fee-for-specialist-registration", "registration-fee-for-specialist-registration-for-practitioners-who-do-not-hold-general-registration"),
    deferredFees: deferred(p.id),
    sourcePages: [...p.sourcePages, ...data.ahpraFeeSchedule.pages],
  });
}

// ── report text ──────────────────────────────────────────────────────────────────────────────────────
const aud = (n: number) => `AUD ${n.toLocaleString("en-AU")}`;
const pick = (locale: Locale, en: string, tr: string, zh: string) => (locale === "tr" ? tr : locale === "zh-Hans" ? zh : en);

const REG_TYPE: Record<MedicalRegistrationFees["registrationType"], { en: string; tr: string; zh: string }> = {
  specialist: { en: "specialist registration", tr: "uzman (specialist) kaydı", zh: "专科注册" },
  limited: { en: "limited registration", tr: "sınırlı (limited) kayıt", zh: "有限注册" },
  general: { en: "general registration", tr: "genel (general) kayıt", zh: "普通注册" },
};

/** "Medical Board of Australia schedule of fees effective 1 August 2026" in the report's language. */
export function feeScheduleCitation(locale: Locale): string {
  const date = data.ahpraFeeSchedule.effectiveDate;
  return pick(
    locale,
    `Medical Board of Australia schedule of fees effective ${date}`,
    `Medical Board of Australia ücret tarifesi (effective ${date} / ${date} itibarıyla geçerli)`,
    `澳大利亚医学委员会收费表（effective ${date}，自 ${date} 起生效）`,
  );
}

/**
 * Amount cell for the Financial Roadmap: just the total of the two Medical Board fees paid together at
 * application. Kept short on purpose -- the PDF draws the amount as one right-aligned line; the breakdown and the
 * "effective 1 August 2026" citation lead the explanation instead (medicalRegistrationFeeBreakdown).
 */
export function medicalRegistrationAmountLabel(fees: MedicalRegistrationFees): string {
  return fees.totalMinAud === fees.totalMaxAud ? aud(fees.totalMinAud) : `${aud(fees.totalMinAud)}–${fees.totalMaxAud.toLocaleString("en-AU")}`;
}

/** The AMC clinical examination sentence (Standard pathway), cited to the AMC's own pages; "" when not applicable. */
export function amcClinicalExamLine(fees: MedicalRegistrationFees, locale: Locale): string {
  const exam = fees.amcClinicalExam;
  if (!exam) return "";
  return pick(
    locale,
    `Plus the AMC clinical examination: ${aud(exam.inPersonAud)} in person or ${aud(exam.onlineAud)} online, payable to the AMC when the exam is scheduled (Australian Medical Council, p.${exam.page}: "${exam.quote}"; no effective date stated). It applies if you take the clinical exam rather than a workplace-based assessment; the AMC CAT MCQ exam and candidate-account/PSV fees are not published in either document.`,
    `Buna AMC klinik sınavı eklenir: yüz yüze ${aud(exam.inPersonAud)} veya çevrimiçi ${aud(exam.onlineAud)}, sınav planlandığında AMC'ye ödenir (Australian Medical Council, s.${exam.page}: "${exam.quote}"; yürürlük tarihi belirtilmemiş). İşyeri temelli değerlendirme yerine klinik sınava girerseniz geçerlidir; AMC CAT MCQ sınavı ve aday hesabı/PSV ücretleri iki belgede de yayımlanmamıştır.`,
    `另加 AMC 临床考试：现场 ${aud(exam.inPersonAud)} 或线上 ${aud(exam.onlineAud)}，在安排考试时向 AMC 缴纳（Australian Medical Council，第 ${exam.page} 页："${exam.quote}"；未注明生效日期）。适用于参加临床考试而非工作场所评估的情况；AMC CAT MCQ 考试及候选人账户/PSV 费用在两份文件中均未公布。`,
  );
}

/** "Medical Board application fee AUD 1,661 + registration fee AUD 1,102 for specialist registration (...effective 1 August 2026)." */
export function medicalRegistrationFeeBreakdown(fees: MedicalRegistrationFees, locale: Locale): string {
  const type = REG_TYPE[fees.registrationType];
  return pick(
    locale,
    `Medical Board application fee ${aud(fees.applicationFee.nationalFeeAud)} + registration fee ${aud(fees.registrationFee.nationalFeeAud)} for ${type.en}, both paid at application (${feeScheduleCitation("en")}).`,
    `Tıp Kurulu başvuru ücreti ${aud(fees.applicationFee.nationalFeeAud)} + kayıt ücreti ${aud(fees.registrationFee.nationalFeeAud)} (${type.tr}), ikisi de başvuruda ödenir (${feeScheduleCitation("tr")}).`,
    `医学委员会申请费 ${aud(fees.applicationFee.nationalFeeAud)} + 注册费 ${aud(fees.registrationFee.nationalFeeAud)}（${type.zh}），均在申请时缴纳（${feeScheduleCitation("zh-Hans")}）。`,
  );
}

const PATHWAY_NAME: Record<MedicalRegistrationPathwayId, { en: string; tr: string; zh: string }> = {
  "expedited-specialist": { en: "Expedited Specialist pathway", tr: "Hızlandırılmış Uzman Yolu (Expedited Specialist pathway)", zh: "快速专科通道（Expedited Specialist pathway）" },
  "specialist-recognition": { en: "Specialist pathway – specialist recognition", tr: "Uzman Yolu – uzmanlık tanıma (Specialist pathway – specialist recognition)", zh: "专科通道 – 专科认可（Specialist pathway – specialist recognition）" },
  standard: { en: "Standard pathway", tr: "Standart Yol (Standard pathway)", zh: "标准通道（Standard pathway）" },
  "au-nz-graduate": { en: "Australian/NZ medical graduate", tr: "Avustralya/Yeni Zelanda tıp mezunu", zh: "澳大利亚/新西兰医学毕业生" },
};

/** Roadmap explanation: which pathway was assumed and why, what else is paid to the Medical Board, the source. */
export function medicalRegistrationExplanation(fees: MedicalRegistrationFees, locale: Locale, authorityLabel: string): string {
  const name = PATHWAY_NAME[fees.pathwayId];
  const why =
    fees.pathwayId === "expedited-specialist"
      ? pick(
          locale,
          `Assumed pathway: ${name.en} -- "${fees.expeditedSpecialty}" is on the Board's Expedited Specialist pathway accepted qualifications list, so an overseas-trained specialist applies directly for specialist registration (with about six months of supervised practice).`,
          `Varsayılan yol: ${name.tr} -- "${fees.expeditedSpecialty}" Kurul'un Expedited Specialist kabul edilen nitelikler listesinde; yurt dışında eğitim almış bir uzman doğrudan uzman kaydına başvurur (yaklaşık altı ay denetimli uygulama ile).`,
          `假定路径：${name.zh}——"${fees.expeditedSpecialty}"在医学委员会的快速专科通道认可资格清单上，海外培训的专科医生可直接申请专科注册（需约六个月的督导执业）。`,
        )
      : fees.pathwayId === "specialist-recognition"
        ? pick(
            locale,
            `Assumed pathway: ${name.en} -- this specialty is not on the Expedited Specialist list, so the specialist college first assesses comparability; the first registration is limited registration for 3–24 months of supervised practice. Specialist registration later costs another ${aud(fees.laterStage!.totalAud)} (application ${aud(fees.laterStage!.applicationFee.nationalFeeAud)} + registration ${aud(fees.laterStage!.registrationFee.nationalFeeAud)}).`,
            `Varsayılan yol: ${name.tr} -- bu uzmanlık Expedited Specialist listesinde değil; önce uzmanlık koleji denkliği değerlendirir, ilk kayıt 3–24 ay denetimli uygulama için sınırlı kayıttır. Daha sonra uzman kaydı ayrıca ${aud(fees.laterStage!.totalAud)} tutar (başvuru ${aud(fees.laterStage!.applicationFee.nationalFeeAud)} + kayıt ${aud(fees.laterStage!.registrationFee.nationalFeeAud)}).`,
            `假定路径：${name.zh}——该专科不在快速专科清单上，须先由专科学院评估可比性；首次注册为有限注册，用于 3–24 个月的督导执业。之后的专科注册另需 ${aud(fees.laterStage!.totalAud)}（申请费 ${aud(fees.laterStage!.applicationFee.nationalFeeAud)} + 注册费 ${aud(fees.laterStage!.registrationFee.nationalFeeAud)}）。`,
          )
        : fees.pathwayId === "standard"
          ? pick(
              locale,
              `Assumed pathway: ${name.en} (AMC CAT MCQ exam, then the AMC clinical exam or a workplace-based assessment, and 12 months of supervised practice). If both AMC exams are passed before applying, provisional registration applies instead: ${aud(fees.alternative!.totalAud)}.`,
              `Varsayılan yol: ${name.tr} (AMC CAT MCQ sınavı, ardından AMC klinik sınavı veya işyeri temelli değerlendirme ve 12 ay denetimli uygulama). Başvurudan önce iki AMC sınavı da geçildiyse bunun yerine geçici (provisional) kayıt uygulanır: ${aud(fees.alternative!.totalAud)}.`,
              `假定路径：${name.zh}（AMC CAT MCQ 考试，随后 AMC 临床考试或工作场所评估，以及 12 个月督导执业）。如申请前已通过两项 AMC 考试，则改为临时注册：${aud(fees.alternative!.totalAud)}。`,
            )
          : pick(
              locale,
              `Assumed: an Australian/New Zealand medical graduate applying for general registration after an accredited internship; without one, provisional registration applies: ${aud(fees.alternative!.totalAud)}.`,
              `Varsayım: akredite stajı tamamlamış bir Avustralya/Yeni Zelanda tıp mezunu genel kayda başvurur; staj yoksa geçici (provisional) kayıt uygulanır: ${aud(fees.alternative!.totalAud)}.`,
              `假设：澳大利亚/新西兰医学毕业生在完成认证实习后申请普通注册；如未完成实习，则适用临时注册：${aud(fees.alternative!.totalAud)}。`,
            );
  const nsw =
    fees.registrationFee.nswRebateOrSurchargeAud > 0
      ? pick(
          locale,
          ` With a principal place of practice in NSW the registration fee is ${aud(fees.registrationFee.nswFeeAud)}.`,
          ` Asıl çalışma yeri NSW ise kayıt ücreti ${aud(fees.registrationFee.nswFeeAud)} olur.`,
          ` 主要执业地点在新南威尔士州（NSW）时，注册费为 ${aud(fees.registrationFee.nswFeeAud)}。`,
        )
      : "";
  const source = pick(
    locale,
    ` Assessing authority: ${authorityLabel}. Source: "${data.sourceTitle}" (Medical Board of Australia / Ahpra), ${feeScheduleCitation("en")}.`,
    ` Değerlendirme kurumu: ${authorityLabel}. Kaynak: "${data.sourceTitle}" (Medical Board of Australia / Ahpra), ${feeScheduleCitation("tr")}.`,
    ` 评估机构：${authorityLabel}。来源："${data.sourceTitle}"（Medical Board of Australia / Ahpra），${feeScheduleCitation("zh-Hans")}。`,
  );
  const amc = amcClinicalExamLine(fees, locale);
  return `${medicalRegistrationFeeBreakdown(fees, locale)}${amc ? ` ${amc}` : ""} ${why}${nsw}${source}`;
}

const ORGANISATION: Record<string, { en: string; tr: string; zh: string }> = {
  AMC: { en: "AMC", tr: "AMC", zh: "AMC" },
  ECFMG: { en: "ECFMG", tr: "ECFMG", zh: "ECFMG" },
  "Specialist medical college": { en: "specialist medical college", tr: "uzmanlık tıp koleji", zh: "专科医学院" },
  "CPD home": { en: "CPD home", tr: "CPD kuruluşu", zh: "CPD 机构" },
  "Workplace-based assessment (SIMG pays)": { en: "workplace-based assessments", tr: "işyeri temelli değerlendirmeler", zh: "工作场所评估" },
  "Other assessments on this pathway": { en: "other assessments/exams", tr: "diğer değerlendirmeler/sınavlar", zh: "其他评估/考试" },
};

/** The separate, unpriced line: which organisations charge what, in the document's own words -- no amounts. */
export function deferredFeesLine(fees: MedicalRegistrationFees, locale: Locale): { category: string; amountLabel: string; explanation: string } {
  const orgs = [...new Set(fees.deferredFees.map((f) => f.organisation))].map((o) => ORGANISATION[o]?.[locale === "zh-Hans" ? "zh" : locale] ?? o);
  const quoted = fees.deferredFees.map((f) => `${f.organisation}: "${f.text}"`).join(" ");
  return {
    category: pick(
      locale,
      `AMC / ECFMG / specialist college fees (not included in the total)`,
      `AMC / ECFMG / uzmanlık koleji ücretleri (toplama dahil değil)`,
      `AMC / ECFMG / 专科学院费用（未计入总额）`,
    ),
    // Short: the PDF draws the amount as one right-aligned line.
    amountLabel: pick(locale, "Not published -- confirm directly", "Yayımlanmadı -- doğrudan teyit edin", "未公布——请直接确认"),
    explanation: pick(
      locale,
      `Charged separately by: ${orgs.join(", ")}. The Medical Board document names these fees but gives no amounts, so no figure is shown here -- confirm each directly with the organisation.${fees.amcClinicalExam ? " (The AMC clinical examination fee is shown in the line above, from the AMC's own pages.)" : ""} In the document's own words (English): ${quoted}`,
      `Ayrıca ücret alan kuruluşlar: ${orgs.join(", ")}. Medical Board belgesi bu ücretleri sayar ancak tutar vermez; bu yüzden burada rakam gösterilmez -- her birini doğrudan ilgili kuruluşla teyit edin.${fees.amcClinicalExam ? " (AMC klinik sınavı ücreti, AMC'nin kendi sayfalarından, yukarıdaki satırda gösterilmiştir.)" : ""} Belgenin kendi ifadesiyle (İngilizce): ${quoted}`,
      `另行收费的机构：${orgs.join("、")}。医学委员会文件列出了这些费用但未给出金额，因此此处不显示数字——请直接向各机构确认。${fees.amcClinicalExam ? "（AMC 临床考试费用已根据 AMC 官方页面列于上一行。）" : ""}文件原文（英文）：${quoted}`,
    ),
  };
}

/**
 * The end-to-end process in 5 sentences, summarised from the same document (pathway pages cited in
 * provenance.json). Used by the FAQ (authority note), the Application Guide and the skills-assessment line.
 */
export const MEDICAL_REGISTRATION_PROCESS: Readonly<Record<Locale, string>> = {
  en:
    "For doctors, the assessment is medical registration with the Medical Board of Australia and Ahpra rather than a single desktop skills assessment. " +
    "Every pathway starts with the Australian Medical Council (AMC) arranging primary source verification (PSV) of your medical qualifications through ECFMG, and your primary medical degree must come from a school recognised by both the AMC and the World Directory of Medical Schools. " +
    "Specialists whose qualification is on the Board's Expedited Specialist pathway list (which includes general practice) apply directly for specialist registration and complete about six months of supervised practice. " +
    "Other specialists are first assessed by their specialist college as substantially comparable, partially comparable or not comparable, which decides whether they continue on the Specialist pathway under limited or provisional registration with 3–24 months of supervised practice. " +
    `Non-specialists use the Competent Authority pathway or the Standard pathway (AMC exams or a workplace-based assessment, plus 12 months of supervised practice). (Source: "${data.sourceTitle}", Medical Board of Australia / Ahpra.)`,
  tr:
    "Doktorlar için değerlendirme, tek bir masa başı beceri değerlendirmesi değil, Medical Board of Australia ve Ahpra nezdinde tıbbi kayıttır. " +
    "Her yol, Avustralya Tıp Konseyi'nin (AMC) tıp niteliklerinizin birincil kaynak doğrulamasını (PSV) ECFMG aracılığıyla yaptırmasıyla başlar; temel tıp diplomanız hem AMC hem de World Directory of Medical Schools tarafından tanınan bir okuldan olmalıdır. " +
    "Niteliği Kurul'un Expedited Specialist yolu listesinde olan uzmanlar (aile hekimliği/general practice dahil) doğrudan uzman kaydına başvurur ve yaklaşık altı ay denetimli uygulama tamamlar. " +
    "Diğer uzmanlar önce uzmanlık koleji tarafından büyük ölçüde denk, kısmen denk veya denk değil olarak değerlendirilir; bu sonuç, 3–24 ay denetimli uygulamayla sınırlı veya geçici kayıt altında Uzman Yolu'nda devam edip edemeyeceklerini belirler. " +
    `Uzman olmayan hekimler Competent Authority yolunu veya Standart Yolu (AMC sınavları ya da işyeri temelli değerlendirme ve 12 ay denetimli uygulama) kullanır. (Kaynak: "${data.sourceTitle}", Medical Board of Australia / Ahpra.)`,
  "zh-Hans":
    "对医生而言，评估即向澳大利亚医学委员会（Medical Board of Australia）和 Ahpra 申请医疗注册，而不是单一的书面技能评估。" +
    "每条路径都从澳大利亚医学理事会（AMC）通过 ECFMG 对您的医学资格进行原始来源核验（PSV）开始，且您的基础医学学位必须来自同时获 AMC 和《世界医学院名录》（WDOMS）认可的院校。" +
    "资格在医学委员会快速专科通道（Expedited Specialist pathway）清单上的专科医生（包括全科医学）可直接申请专科注册，并完成约六个月的督导执业。" +
    "其他专科医生须先由其专科学院评估为实质可比、部分可比或不可比，该结果决定其能否在有限或临时注册下继续专科通道，并完成 3–24 个月的督导执业。" +
    `非专科医生适用胜任机构通道（Competent Authority pathway）或标准通道（AMC 考试或工作场所评估，加上 12 个月督导执业）。（来源："${data.sourceTitle}"，Medical Board of Australia / Ahpra。）`,
};

/** ANZSCO code from an occupation string ("General Practitioner 253111"), or by exact title against the given list. */
export function anzscoCodeFromOccupation(occupation: string | undefined, titled: ReadonlyArray<{ anzscoCode?: string; title: string }>): string | undefined {
  if (!occupation) return undefined;
  const code = occupation.match(/\b(\d{6})\b/)?.[1];
  if (code) return code;
  const title = occupation.trim().toLowerCase();
  return titled.find((o) => o.title.toLowerCase() === title)?.anzscoCode;
}
