import type { PDFContext } from "../pdf-types";

/**
 * Footer components for the PDF generator.
 *
 * Includes:
 * - addGlobalFooters: Applies footer + page numbers to all pages
 * - addViralCTABanner: Closing CTA banner for marketing conversion
 *
 * Extracted from the original monolith (lines 1007-1032 and 1575-1617).
 */

export function createFooterHelpers(ctx: PDFContext) {
  const {
    doc,
    pageWidth,
    pageHeight,
    margin,
    contentWidth,
    COLORS,
    FONTS,
    setBaseFont,
    setBoldFont,
    safeText,
    effectiveLocale,
  } = ctx;

  /**
   * Applies a global footer (disclaimer + page numbers + brand credit)
   * to every page of the document. Must be called AFTER all content is
   * rendered so pageCount is accurate.
   */
  function addGlobalFooters(): void {
    const totalPages = doc.getNumberOfPages();
    const footerWidth = pageWidth - margin * 2;

    // Use country-aware disclaimer if available, otherwise fallback
    const footerText =
      ctx.report.disclaimer ||
      (ctx.text.coverConfidential
        ? "This report is an automated data analysis for general information only."
        : "");

    for (let page = 1; page <= totalPages; page += 1) {
      doc.setPage(page);
      setBaseFont();
      doc.setDrawColor(COLORS.border.r, COLORS.border.g, COLORS.border.b);
      doc.setLineWidth(0.25);
      doc.line(margin, pageHeight - 14, pageWidth - margin, pageHeight - 14);
      doc.setFontSize(FONTS.small);
      doc.setTextColor(COLORS.lightText.r, COLORS.lightText.g, COLORS.lightText.b);

      if (footerText) {
        const footerLines = doc.splitTextToSize(footerText, footerWidth);
        doc.text(
          footerLines.map((line: string) => safeText(line)),
          margin,
          pageHeight - 10,
        );
      }

      // Page number (right) and brand credit (left) on same baseline
      doc.text(
        `${page}/${totalPages}`,
        pageWidth - margin,
        pageHeight - 4,
        { align: "right" },
      );
      doc.setFontSize(6.5);
      doc.setTextColor(COLORS.accent.r, COLORS.accent.g, COLORS.accent.b);
      doc.text(
        safeText("Generated by LogiVisa AI • logivisa.com"),
        margin,
        pageHeight - 4,
      );
    }
  }

  /**
   * Renders the closing viral CTA banner — encourages reader to visit
   * logivisa.com for a personalized assessment.
   */
  function addViralCTABanner(): void {
    const bannerHeight = 28;
    ctx.ensurePageSpace(bannerHeight + 10);
    ctx.yPosition += 5;

    // Banner background — light cyan with accent border
    doc.setFillColor(236, 254, 255);
    doc.setDrawColor(COLORS.accent.r, COLORS.accent.g, COLORS.accent.b);
    doc.setLineWidth(0.4);
    doc.roundedRect(margin, ctx.yPosition, contentWidth, bannerHeight, 2, 2, "FD");

    // Left accent stripe
    doc.setFillColor(COLORS.accent.r, COLORS.accent.g, COLORS.accent.b);
    doc.rect(margin, ctx.yPosition + 2, 3, bannerHeight - 4, "F");

    // Title
    setBoldFont();
    doc.setFontSize(11);
    doc.setTextColor(COLORS.primary.r, COLORS.primary.g, COLORS.primary.b);

    const ctaTitle =
      effectiveLocale === "tr"
        ? "Kendi PR puanlarınızı bulmak ister misiniz?"
        : effectiveLocale === "zh-Hans"
          ? "想查看自己的PR积分吗？"
          : "Want to find your own PR points?";

    doc.text(safeText(ctaTitle), margin + 6, ctx.yPosition + 7);

    // Subtitle
    setBaseFont();
    doc.setFontSize(FONTS.body);
    doc.setTextColor(COLORS.text.r, COLORS.text.g, COLORS.text.b);
    const ctaSubtitle =
      effectiveLocale === "tr"
        ? "LogiVisa AI ile 60 saniyede ücretsiz olarak vize şansınızı ve kesin puanlarınızı hesaplayın."
        : effectiveLocale === "zh-Hans"
          ? "使用LogiVisa AI，60秒内免费计算您的签证机会和确切积分。"
          : "Calculate your visa chances and exact points for free in 60 seconds using LogiVisa AI.";

    const subtitleLines = doc.splitTextToSize(safeText(ctaSubtitle), contentWidth - 10);
    doc.text(subtitleLines, margin + 6, ctx.yPosition + 14);

    // Clickable URL
    setBoldFont();
    doc.setFontSize(FONTS.body);
    doc.setTextColor(COLORS.accent.r, COLORS.accent.g, COLORS.accent.b);
    const urlText =
      effectiveLocale === "tr"
        ? "logivisa.com'u ziyaret edin"
        : effectiveLocale === "zh-Hans"
          ? "访问 www.logivisa.com"
          : "Visit www.logivisa.com";

    doc.textWithLink(safeText(urlText), margin + 6, ctx.yPosition + 22, {
      url: "https://logivisa.com",
    });

    ctx.yPosition += bannerHeight + 5;
  }

  return {
    addGlobalFooters,
    addViralCTABanner,
  };
}