type LocalizedStructuredFields = {
  key_requirements?: string[];
  documents_required?: string[];
  application_steps?: string[];
  visa_conditions?: string[];
  risks?: string[];
  english_requirements?: Record<string, unknown>;
  financial_requirements?: Record<string, unknown>;
  raw_json?: Record<string, unknown>;
};

type LocalizedVisaFields = {
  visa_name?: string;
  category?: string;
  purpose?: string;
  stay_period?: string;
  cost?: string;
  work_rights?: string;
};

type LocaleVisaStructuredMap = Record<string, LocalizedStructuredFields>;
type LocaleVisaFieldsMap = Record<string, LocalizedVisaFields>;

const trVisaFields: LocaleVisaFieldsMap = {
  "500": {
    visa_name: "Öğrenci vizesi",
    category: "Eğitim",
    purpose: "Avustralya'da uygun bir eğitim programına katılmak",
    stay_period: "6 yıla kadar ve kayıt durumuna bağlı",
    cost: "Muafiyet yoksa AUD 2.000'den başlar",
    work_rights:
      "Eğitim dönemi boyunca iki haftada 48 saate kadar çalışma; araştırma veya lisansüstü öğrenciler için farklı kurallar uygulanabilir",
  },
  "482": {
    visa_name: "Talep Gören Beceriler vizesi",
    category: "Çalışma",
    purpose:
      "Core Skills Occupation List'te yer alan bir meslek için onaylı işveren sponsoruyla Avustralya'da geçici çalışma",
    stay_period: "4 yıla kadar. Hong Kong pasaport sahipleri 5 yıla kadar kalabilir.",
    cost: "Asıl başvuru sahibi ve 18+ bağımlılar için AUD 3.210'dan başlar. 18 yaş altı bağımlılar için AUD 805.",
    work_rights:
      "Atanan meslekte onaylı sponsor için çalışma. Bazı durumlarda sponsorun ilişkili kuruluşunda çalışma mümkündür.",
  },
  "189": {
    visa_name: "Nitelikli Bağımsız vizesi",
    category: "Kalıcı Nitelikli Göç",
    purpose: "Davetli nitelikli çalışan olarak Avustralya'nın her yerinde kalıcı yaşamak ve çalışmak",
    stay_period: "Kalıcı",
    cost: "Asıl başvuru sahibi için AUD 4.910'dan başlar",
    work_rights: "Avustralya'nın her yerinde çalışma ve eğitim",
  },
  "190": {
    visa_name: "Nitelikli Aday Gösterilmiş vizesi",
    category: "Kalıcı Nitelikli Göç",
    purpose:
      "Avustralya eyalet veya bölge yönetimi tarafından aday gösterilen nitelikli çalışan olarak kalıcı yaşamak ve çalışmak",
    stay_period: "Kalıcı",
    cost: "Asıl başvuru sahibi için AUD 4.910'dan başlar",
    work_rights: "Avustralya'nın her yerinde çalışma ve eğitim",
  },
  "491": {
    visa_name: "Nitelikli Bölgesel Çalışma (Geçici) vizesi",
    category: "Bölgesel Nitelikli Göç",
    purpose:
      "Nitelikli çalışan olarak Avustralya'nın belirlenmiş bölgesel alanlarında yaşamak, çalışmak ve eğitim görmek",
    stay_period: "5 yıl",
    cost: "Asıl başvuru sahibi için AUD 4.910'dan başlar. Aile üyeleri ve ikinci taksit için ek ücretler olabilir.",
    work_rights: "Avustralya'nın belirlenmiş bölgesel alanlarında yaşama, çalışma ve eğitim.",
  },
  "820_801": {
    visa_name: "Partner vizesi (ülke içi)",
    category: "Aile Göçü",
    purpose:
      "Avustralya vatandaşı, daimi oturum sahibi veya uygun Yeni Zelanda vatandaşı partnerin eşine/fiili partnerine Avustralya'da geçici yaşama ve kalıcı aşamaya ilerleme imkanı sağlar",
    stay_period: "Kalıcı Partner vizesi 801 sonuçlanana veya geri çekilene kadar geçici",
    cost:
      "Çoğu başvuru sahibi için AUD 9.365'ten başlar. Subclass 300 sahipleri için AUD 1.560'tan, bazı eski subclass 300 sahipleri için AUD 1.980'den başlar.",
    work_rights: "Kalıcı Partner vizesi değerlendirilirken Avustralya'da yaşama, çalışma ve eğitim.",
  },
  "485": {
    visa_name: "Geçici Mezun vizesi",
    category: "Mezuniyet Sonrası Çalışma",
    purpose:
      "Uygun yakın dönem mezunlara Avustralya'daki eğitimlerini tamamladıktan sonra geçici yaşama, çalışma ve eğitim imkanı sağlar",
    stay_period:
      "Genellikle niteliğe göre 2-3 yıl; Hong Kong ve British National Overseas pasaport sahipleri 5 yıl kalabilir",
    cost: "AUD 4.600'dan başlar",
    work_rights:
      "Avustralya'da yaşama, çalışma ve eğitim. Vize geçerliyken giriş-çıkış yapma ve uygun aile üyelerini dahil etme.",
  },
};

const zhHansVisaFields: LocaleVisaFieldsMap = {
  "500": {
    visa_name: "学生签证",
    category: "学习",
    purpose: "在澳大利亚参加符合条件的课程学习",
    stay_period: "最长6年，并与注册期限一致",
    cost: "如无豁免，费用自 AUD 2,000 起",
    work_rights: "课程期间每两周最多工作48小时；研究型或研究生可能适用不同规则",
  },
  "482": {
    visa_name: "紧缺技能签证",
    category: "工作",
    purpose: "在获批雇主担保下，以核心技能职业清单中的职业在澳大利亚临时工作",
    stay_period: "最长4年。香港护照持有人最长可达5年。",
    cost: "主申请人及18岁以上附属申请人每人 AUD 3,210 起；18岁以下每人 AUD 805。",
    work_rights: "在提名职业中为获批担保雇主工作；部分情况下可为关联实体工作。",
  },
  "189": {
    visa_name: "独立技术移民签证",
    category: "永久技术移民",
    purpose: "作为受邀技术人员在澳大利亚任何地区永久生活和工作",
    stay_period: "永久",
    cost: "主申请人 AUD 4,910 起",
    work_rights: "可在澳大利亚任何地区工作和学习",
  },
  "190": {
    visa_name: "州担保技术移民签证",
    category: "永久技术移民",
    purpose: "作为州或领地提名的技术人员在澳大利亚永久生活和工作",
    stay_period: "永久",
    cost: "主申请人 AUD 4,910 起",
    work_rights: "可在澳大利亚任何地区工作和学习",
  },
  "491": {
    visa_name: "偏远地区技术工作（临时）签证",
    category: "偏远地区技术移民",
    purpose: "作为技术人员在澳大利亚指定偏远地区生活、工作和学习",
    stay_period: "5年",
    cost: "主申请人 AUD 4,910 起；家庭成员及第二笔费用可能另计。",
    work_rights: "可在澳大利亚指定偏远地区生活、工作和学习。",
  },
  "820_801": {
    visa_name: "伴侣签证（境内）",
    category: "家庭移民",
    purpose:
      "允许澳大利亚公民、永久居民或符合条件的新西兰公民的配偶/事实伴侣在澳临时居留，并过渡到永久居留",
    stay_period: "临时，直至永久伴侣签证 801 完成审理或撤回",
    cost:
      "多数申请人 AUD 9,365 起。300 子类持有人 AUD 1,560 起，部分原 300 子类持有人 AUD 1,980 起。",
    work_rights: "在永久伴侣签证审理期间可在澳生活、工作和学习。",
  },
  "485": {
    visa_name: "临时毕业生签证",
    category: "毕业后工作",
    purpose: "允许符合条件的应届毕业生在完成澳洲学习后在澳临时生活、工作和学习",
    stay_period: "通常2至3年（取决于学历）；香港及英籍国民（海外）护照持有人可达5年",
    cost: "AUD 4,600 起",
    work_rights: "可在澳生活、工作和学习；签证有效期内可出入境，并可包含符合条件的家庭成员。",
  },
};

const trStructuredData: LocaleVisaStructuredMap = {
  "500": {
    key_requirements: [
      "Avustralya içinden veya dışından çevrimiçi başvurun",
      "Tam zamanlı bir eğitime kayıtlı olun ve geçerli bir Kayıt Onayı (CoE) bulundurun",
      "Yurt Dışı Öğrenci Sağlık Sigortasını (OSHC) sürdürün",
      "En az 6 yaşında olun",
      "18 yaşından küçükseniz uygun refah düzenlemelerine sahip olun",
      "Avustralya içinden başvuruyorsanız uygun bir esas vizeye sahip olun",
      "İngilizce dil şartlarını karşılayın veya muafiyet kapsamında olun",
      "Kalış süresi için yeterli mali kapasiteyi gösterin",
      "Gerçek bir öğrenci olduğunuzu gösterin",
      "Sağlık ve karakter şartlarını karşılayın",
      "18 yaş ve üzerindeyseniz Avustralya Değerler Beyanını imzalayın",
      "Avustralya Hükümetine olan borçlarınızı ödemiş olun",
      "Uygunluğu olumsuz etkileyen bir vize geçmişine sahip olmayın",
    ],
    documents_required: [
      "Geçerli pasaport",
      "Kayıt Onayı (CoE)",
      "Gerekliyse İngilizce yeterlilik kanıtı",
      "Gerekliyse mali yeterlilik kanıtı",
      "Yurt Dışı Öğrenci Sağlık Sigortası (OSHC)",
      "Kimlik belgeleri",
      "Gerekliyse sağlık muayenesi sonuçları",
      "Gerekliyse polis belgeleri",
      "18 yaş altı için refah ve ebeveyn onay belgeleri",
      "Varsa eş ve bakmakla yükümlü olunan kişilere ait belgeler",
      "İngilizce olmayan belgeler için onaylı çeviriler",
    ],
    application_steps: [
      "Başvuru öncesi hazırlığınızı tamamlayın",
      "Belge Kontrol Aracı ile gerekli belgeleri toplayın",
      "ImmiAccount üzerinden çevrimiçi başvurun",
      "Belgeleri yükleyin ve vize başvuru ücretini ödeyin veya muafiyet kanıtı sunun",
      "Ek bilgi taleplerine yanıt verin",
      "İstenirse biyometri veya sağlık muayenesini tamamlayın",
      "Yazılı vize sonucunu bekleyin",
    ],
    visa_conditions: [
      "Uygun bir eğitim programındaki kaydınızı sürdürün",
      "Çalışma kısıtlarına uyun",
      "Yeterli sağlık sigortasını sürdürün",
      "Avustralya yasalarına uyun",
      "Vize geçerliyken Avustralya'ya giriş çıkış yapabilirsiniz",
      "Bu vize uzatılamaz; daha uzun kalmak için yeni vizeye başvurulmalıdır",
      "Koşullarınız değişirse Bakanlığı bilgilendirin",
    ],
    risks: [
      "Başvuru eksikse işlem gecikebilir veya reddedilebilir",
      "CoE eksik ya da geçersizse başvuru geçersiz sayılabilir",
      "Yanlış veya yanıltıcı bilgi ret ve gelecekte vize sonuçlarına yol açabilir",
      "Yetersiz mali kanıt ret ile sonuçlanabilir",
      "OSHC'nin sürdürülmemesi uyum sorunlarına yol açabilir",
      "Önceki ret veya iptaller uygunluğu etkileyebilir",
      "Gerçek Öğrenci şartının karşılanmaması ret ile sonuçlanabilir",
    ],
    english_requirements: {
      notes: [
        "Sınavın tamamı çevrimiçi yapılan evden/online İngilizce sınavları kabul edilmez.",
        "Bazı başvuru sahipleri İngilizce sınav kanıtından muaf olabilir.",
        "Kanıt gereksinimleri için Belge Kontrol Aracı kullanılmalıdır.",
      ],
    },
    financial_requirements: {
      schooling_costs_per_child: "Çocuk başına yılda en az AUD 13.502",
    },
  },
  "189": {
    key_requirements: [
      "İlgili nitelikli meslek listesinde bir mesleğe sahip olun",
      "Uygun bir beceri değerlendirmesine sahip olun",
      "Başvuru daveti alın",
      "En az 65 puan alın",
      "Davet tarihinde 45 yaşın altında olun",
      "Yeterli düzeyde İngilizceye sahip olun",
      "Sağlık ve karakter şartlarını karşılayın",
    ],
    documents_required: [
      "Niyet Beyanı (EOI)",
      "Başvuru daveti",
      "Beceri değerlendirmesi",
      "İngilizce sınav sonuçları",
      "Kimlik belgeleri",
      "Puan beyanlarını destekleyen kanıtlar",
    ],
    application_steps: [
      "SkillSelect üzerinden EOI gönderin",
      "Daveti bekleyin",
      "Belgeleri toplayın",
      "ImmiAccount üzerinden başvurun",
      "Belgeleri yükleyin",
      "Kararı bekleyin",
    ],
    visa_conditions: [
      "Kalıcı oturum",
      "Avustralya'nın her yerinde yaşama ve çalışma hakkı",
      "5 yıl seyahat hakkı",
      "Vatandaşlığa uygunluk imkanı",
    ],
    risks: [
      "Davet yoksa başvuru yapılamaz",
      "Düşük puan davet alınamamasına neden olabilir",
      "Yanlış beyanlar ret ile sonuçlanabilir",
    ],
    english_requirements: {
      required_level: "Yeterli İngilizce",
      IELTS: "Her bantta 6,0",
      PTE: "Eşdeğer puanlar gerekir",
    },
    raw_json: {
      occupation_requirements: {
        summary: "Meslek, uygun Nitelikli Meslekler Listesinde yer almalıdır.",
        sample_occupations: [
          "Muhasebeci",
          "İnşaat mühendisi",
          "Yazılım mühendisi",
          "Kayıtlı hemşire",
          "Elektrikçi",
          "Aşçı",
        ],
      },
      points_test_rules: {
        minimum_points: 65,
        age: [
          { range: "18-24", points: 25 },
          { range: "25-32", points: 30 },
          { range: "33-39", points: 25 },
          { range: "40-44", points: 15 },
        ],
        english: [
          { level: "Yeterli", points: 0 },
          { level: "İleri", points: 10 },
          { level: "Üstün", points: 20 },
        ],
      },
    },
    financial_requirements: {
      status: "Kaynak metinde birincil gereksinim değil",
    },
  },
  "190": {
    key_requirements: [
      "İlgili nitelikli meslek listesinde bir mesleğe sahip olun",
      "Meslek için uygun bir beceri değerlendirmesine sahip olun",
      "SkillSelect üzerinden Niyet Beyanı (EOI) gönderin",
      "Bir Avustralya eyaleti veya bölgesi tarafından aday gösterilin",
      "Bu vize için başvuru daveti alın",
      "En az 65 puan alın",
      "Başvuru daveti aldığınızda 45 yaşın altında olun",
      "Davet anında en az Yeterli İngilizce düzeyine sahip olun",
      "Sağlık ve karakter şartlarını karşılayın",
      "Avustralya Hükümetine olan borçlarınızı ödeyin",
      "18 yaş ve üzerindeyseniz Avustralya Değerler Beyanını imzalayın",
    ],
    documents_required: [
      "SkillSelect üzerinden Niyet Beyanı (EOI)",
      "Başvuru daveti",
      "Eyalet veya bölge adaylığı",
      "Uygun beceri değerlendirmesi",
      "Kimlik belgeleri",
      "Yeterli İngilizce kanıtı",
      "Puan beyanlarını destekleyen kanıtlar",
      "Varsa ilişki belgeleri",
      "Gerekliyse karakter belgeleri ve polis kayıtları",
      "İstenirse sağlık muayenesi sonuçları",
      "Dahil edilen aile üyelerine ait belgeler",
      "İngilizce olmayan belgeler için çeviriler",
    ],
    application_steps: [
      "SkillSelect üzerinden Niyet Beyanı (EOI) gönderin",
      "Nitelikli Aday Gösterilmiş 190 alt sınıf vizesini seçin",
      "Eyalet veya bölge adaylığı için bekleyin",
      "Aday gösterilirseniz başvuru daveti alın",
      "Davet tarihinden itibaren 60 gün içinde ImmiAccount üzerinden çevrimiçi başvurun",
      "Belgeleri yükleyin ve başvuru ücretini ödeyin",
      "İstenirse ek bilgi taleplerine yanıt verin",
      "İstenirse sağlık muayenesi veya biyometriyi tamamlayın",
      "Yazılı vize sonucunu bekleyin",
    ],
    visa_conditions: [
      "Kalıcı vize",
      "Avustralya'da yaşama, çalışma ve eğitim hakkı",
      "Vize veriliş tarihinden itibaren 5 yıl giriş çıkış hakkı",
      "5 yıl sonra yeniden giriş için Resident Return vizesi gerekebilir",
      "Uygun akrabalar için sponsorluk imkanı",
      "Avustralya vatandaşlığına uygunluk imkanı",
      "Avustralya yasalarına uyma zorunluluğu",
    ],
    risks: [
      "Eyalet veya bölge adaylığı yoksa başvuru daveti alınamaz",
      "Adaylık başvuru sonrası geri çekilirse başvuru geçersiz olur",
      "65 puanın altındaki skor davet alınamamasına yol açar",
      "EOI puanlarına göre davet puanı 65'in üzerinde olabilir",
      "Davet sonrası puan beyanları kanıtlanmalıdır",
      "Davet tarihinde yaş 45'in altında olmalıdır",
      "Beceri değerlendirmesi uygun ve geçerli olmalıdır",
      "Meslek ilgili nitelikli meslek listesinde olmalıdır",
      "Eyalet ve bölge kurumlarının kendi adaylık kriterleri vardır",
      "Eksik veya hatalı bilgi başvuruyu geciktirebilir ya da olumsuz etkileyebilir",
    ],
    english_requirements: {
      required_level: "Yeterli İngilizce",
      summary: "Davet anında, subclass 190 başvuru sahipleri en az Yeterli İngilizce düzeyine sahip olmalıdır.",
      test_validity: "Sınav sonuçları, vize alt sınıfına bağlı olarak, genellikle vize başvurusundan önceki 3 yıl içinde alınmış olmalıdır.",
      passport_exemptions: [
        "Kanada",
        "Yeni Zelanda",
        "İrlanda Cumhuriyeti",
        "Büyük Britanya ve Kuzey İrlanda Birleşik Krallığı",
        "Amerika Birleşik Devletleri",
      ],
      tests_taken_on_or_after_2025_08_07: {
        C1_Advanced: { listening: 163, reading: 163, writing: 170, speaking: 179 },
        CELPIP_General: { listening: 7, reading: 7, writing: 7, speaking: 7 },
        IELTS_Academic: {
          listening: 6,
          reading: 6,
          writing: 6,
          speaking: 6,
          note: "Uygun vizelerde IELTS One Skill Retake kabul edilebilir.",
        },
        IELTS_General_Training: {
          listening: 6,
          reading: 6,
          writing: 6,
          speaking: 6,
          note: "Uygun vizelerde IELTS One Skill Retake kabul edilebilir.",
        },
        MET: {
          listening: 56,
          reading: 55,
          writing: 57,
          speaking: 48,
          note: "Uygun vizelerde MET Single Section Retake kabul edilebilir.",
        },
        OET: { listening: 290, reading: 310, writing: 290, speaking: 330 },
        LANGUAGECERT_Academic: { listening: 57, reading: 60, writing: 64, speaking: 70 },
        PTE_Academic: { listening: 47, reading: 48, writing: 51, speaking: 54 },
        TOEFL_iBT: {
          listening: 16,
          reading: 16,
          writing: 19,
          speaking: 19,
          note: "Kayıt sırasında Taking TOEFL for Australia seçilmelidir.",
        },
      },
      tests_taken_on_or_before_2025_08_06: {
        C1_Advanced: {
          listening: 169,
          reading: 169,
          writing: 169,
          speaking: 169,
          note: "12 Şubat 2024 ile 6 Ağustos 2025 arasında yalnızca Cambridge C1 Advanced kağıt tabanlı sonuçları kabul edilir. Daha eski sınavlar, geçerlilik süresi içinde halen kabul edilebilir.",
        },
        IELTS: {
          listening: 6,
          reading: 6,
          writing: 6,
          speaking: 6,
          note: "IELTS Academic veya General Training.",
        },
        OET: { listening: "B", reading: "B", writing: "B", speaking: "B" },
        PTE_Academic: { listening: 50, reading: 50, writing: 50, speaking: 50 },
        TOEFL_iBT: {
          listening: 12,
          reading: 13,
          writing: 21,
          speaking: 21,
          note: "26 Temmuz 2023 ile 4 Mayıs 2024 arasında alınan TOEFL iBT sınavları Avustralya vize amaçları için onaylanmamıştır.",
        },
      },
      online_tests_not_accepted: {
        rule: "Bakanlık, tamamen çevrimiçi, uzaktan gözetimli veya evden yapılan İngilizce sınavlarını kanıt olarak kabul etmez.",
        examples_not_accepted: [
          "CELPIP Online",
          "IELTS Online",
          "LANGUAGECERT Academic Online",
          "MET Digital taken at-home",
          "OET@Home",
          "TOEFL iBT Home Edition",
        ],
      },
      notes: [
        "6 Ağustos 2025 ve öncesinde alınan sınavlar, vize türüne bağlı olarak 6 Ağustos 2028 dahil tarihine kadar kanıt olarak kullanılabilir.",
        "Bazı vizelerde başka kanıt türleri kabul edilebilir.",
      ],
    },
    raw_json: {
      occupation_requirements: {
        summary: "Başvuru sahibinin, Skilled Nominated subclass 190 vizesi için uygun nitelikli meslekler listesindeki ilgili bir mesleğe sahip olması gerekir.",
        state_specific_review_required: true,
        notes: [
          "Subclass 190 için bir Avustralya eyaleti veya bölgesi devlet kurumu tarafından aday gösterilmek gerekir.",
          "Her eyalet veya bölgenin kendi aday gösterme kriterleri ve meslek öncelikleri vardır.",
          "Meslek uygunluğu, hem ilgili nitelikli meslek listesine hem de aday gösteren eyalet veya bölgenin kriterlerine göre kontrol edilmelidir.",
        ],
        states_and_territories: [
          "Avustralya Başkent Bölgesi",
          "Yeni Güney Galler",
          "Kuzey Bölgesi",
          "Queensland",
          "Güney Avustralya",
          "Tazmanya",
          "Victoria",
          "Batı Avustralya",
        ],
      },
      points_test_rules: {
        minimum_points_required: 65,
        summary: "Subclass 190 puan testine tabi bir vizedir. Başvuru sahibinin en az 65 puan alması gerekir ve EOI beyanları ile eyalet veya bölge adaylığına göre davet alabilir.",
        note: "Resmi subclass'a özgü farklar tespit edilmedikçe, ayrıntılı puan kategorileri subclass 189 için kullanılan puan testli nitelikli göç tablosunu yeniden kullanmalıdır.",
      },
    },
    financial_requirements: {
      status: "Kaynak metinde birincil gereksinim değil",
      notes: [
        "Sağlanan kaynak, subclass 190 için özel bir kişisel mali yeterlilik gereksinimi belirtmemektedir.",
        "Fonksiyonel İngilizce düzeyinin altındaki aile üyeleri için vize ücreti ikinci taksidi uygulanabilir.",
      ],
    },
  },
  "482": {
    key_requirements: [
      "Onaylı bir sponsor tarafından aday gösterilmek",
      "Core Skills Occupation List'teki bir meslek için aday gösterilmek",
      "Yıllık Piyasa Ücret Oranı ve Core Skills Income Threshold altında olmayacak ücret almak",
      "Aday olunan meslekte veya ilgili alanda en az 1 yıl deneyime sahip olmak",
      "Gerekliyse uygun beceri değerlendirmesine sahip olmak",
      "Muaf durumlar dışında yalnızca sponsor veya ilişkili kuruluş için çalışmak",
      "Muaf değilse asgari İngilizce yeterliliğini sağlamak",
      "Avustralya içinden başvuruluyorsa uygun vizeye sahip olmak",
      "Avustralya içinden başvuruda önceki vize koşullarına uymuş olmak",
      "Yeterli sağlık sigortasını sürdürmek",
      "Sağlık ve karakter şartlarını karşılamak",
      "Vize sponsorluğu için ödeme geçmişine sahip olmamak",
      "Uygunluğu etkileyen ret/iptal geçmişine sahip olmamak",
      "Avustralya Hükümetine borcu olmamak",
      "18 yaş ve üzerindekiler için Avustralya Değerler Beyanı'nı imzalamak",
    ],
    documents_required: [
      "Geçerli pasaport",
      "İşveren adaylık Transaction Reference Number",
      "Kimlik belgeleri",
      "Varsa isim değişikliği kanıtı",
      "Zorunluysa beceri değerlendirme referans numarası",
      "Beceri, yeterlilik ve iş geçmişi kanıtı",
      "İlgili diploma/sertifika belgeleri",
      "Gerekliyse kayıt veya lisans belgeleri",
      "Özgeçmiş",
      "İş referansları",
      "İngilizce yeterlilik belgeleri",
      "Yeterli sağlık sigortası kanıtı",
      "Gerekliyse sağlık muayenesi sonuçları",
      "Gerekliyse Avustralya polis belgesi",
      "Gerekliyse yurt dışı polis belgeleri",
      "Varsa askerlik kayıtları",
      "Varsa partner belgeleri",
      "Varsa bağımlı belgeleri",
      "18 yaş altı bağımlılar için ebeveyn sorumluluk belgeleri (varsa)",
      "İngilizce olmayan belgeler için çeviriler",
    ],
    application_steps: [
      "Başvuru öncesi adaylık, pasaport, gerekliyse beceri değerlendirmesi ve İngilizce sınavını hazırlayın",
      "Kimlik, beceri, meslek, İngilizce, sağlık sigortası, karakter ve aile belgelerini toplayın",
      "ImmiAccount üzerinden çevrimiçi başvurun",
      "Belgeleri yükleyin ve başvuru ücretini ödeyin",
      "İstenirse ek bilgi taleplerine yanıt verin",
      "İstenirse sağlık muayenesi veya biyometriyi tamamlayın",
      "Başvuru işlenirken yasal statünüzü koruyun",
      "Yazılı vize sonucunu bekleyin",
    ],
    visa_conditions: [
      "Aday gösterilen meslekte çalışmak",
      "Genellikle yalnızca sponsor işveren için çalışmak",
      "Avustralyalı sponsor varsa sponsor veya ilişkili kuruluş için çalışabilmek",
      "Avustralya'ya girişten itibaren veya ülke içi onayda verilişten itibaren 90 gün içinde işe başlamak",
      "Yeterli sağlık sigortasını sürdürmek",
      "Avustralya yasalarına uymak",
      "Vize geçerliyken Avustralya'ya giriş çıkış yapabilmek",
      "Avustralya dışında geçirilen süre vizeyi uzatmaz",
      "İletişim, işveren, çalışma durumu, ilişki durumu veya çocuk doğumu gibi değişiklikleri bildirmek",
    ],
    risks: [
      "İşveren adaylığı onaylanmadan vize verilemez",
      "Belgeler eksikse başvuru gecikebilir veya reddedilebilir",
      "Zorunlu beceri değerlendirmesi başvuru öncesi başlatılmamışsa başvuru geçersiz olabilir",
      "Yanlış veya yanıltıcı bilgi ret ve gelecekte vize sonuçlarına yol açabilir",
      "İngilizce şartlarının karşılanmaması uygunluğu etkileyebilir",
      "Sağlık sigortasının sürdürülmemesi vize koşulu ihlaline yol açabilir",
      "Önceki ret veya iptaller uygunluğu etkileyebilir",
      "Son 3 yılda sponsorluk için ödeme yapılması uygunluğu etkileyebilir",
      "İş sona ererse yeni işveren bulunması veya Avustralya'dan ayrılma düzenlemesi gerekebilir",
    ],
    english_requirements: {
      summary:
        "Skills in Demand 482 için birincil başvuru sahipleri, muafiyet yoksa asgari İngilizce yeterliliğini göstermelidir.",
      applies_to_streams: ["Core Skills akışı", "Specialist Skills akışı"],
      test_validity: "İngilizce sınavları başvurudan önceki 3 yıl içinde alınmış olmalıdır.",
      exemptions: [
        "Kanada pasaportu sahibi olmak",
        "Yeni Zelanda pasaportu sahibi olmak",
        "İrlanda Cumhuriyeti pasaportu sahibi olmak",
        "Birleşik Krallık pasaportu sahibi olmak",
        "Amerika Birleşik Devletleri pasaportu sahibi olmak",
        "Derslerin çoğunun İngilizce verildiği en az ortaöğretim düzeyinde bir kurumda en az 5 yıl tam zamanlı eğitim tamamlamış olmak",
        "Aday gösterilen mesleğin başka bir ülkenin diplomatik veya konsolosluk misyonunda icra edilecek olması",
        "Aday gösterilen mesleğin Tayvan Yetkilileri Ofisinde icra edilecek olması",
        "Aday gösterilen mesleğin lisans, kayıt veya üyelik gerektirmesi ve başvuru sahibinin bunu almak için eşit veya daha yüksek İngilizce yeterliliği kanıtlamış olması",
        "Başvuru sahibinin yurt dışı bir işletmenin çalışanı olması, işletmenin veya ilişkili kuruluşunun kişiyi Avustralya'da çalışmak üzere aday göstermesi ve yıllık en az AUD 96.400 garanti kazanç alacak olması",
      ],
      tests_taken_on_or_after_2025_09_13: {
        single_skill_retake_note:
          "Sınav tek beceri telafi seçeneği sunuyorsa, o beceriye ait sonuç kabul edilebilir.",
        CELPIP_General: { listening: 5, reading: 5, writing: 5, speaking: 5 },
        IELTS_Academic: { listening: 5, reading: 5, writing: 5, speaking: 5 },
        IELTS_General_Training: { listening: 5, reading: 5, writing: 5, speaking: 5 },
        LANGUAGECERT_Academic: { listening: 41, reading: 44, writing: 45, speaking: 54 },
        MET: { listening: 49, reading: 47, writing: 45, speaking: 38 },
        OET: { listening: 220, reading: 240, writing: 200, speaking: 270 },
        PTE_Academic: { listening: 33, reading: 36, writing: 29, speaking: 24 },
        TOEFL_iBT: {
          listening: 8,
          reading: 8,
          writing: 9,
          speaking: 14,
          note: "21 Ocak 2026 ve sonrasında alınan sınavlarda kayıt sırasında Taking TOEFL for Australia seçilmelidir.",
        },
      },
      tests_taken_before_2025_09_13: {
        single_sitting_required: true,
        single_skill_retake_accepted: false,
        IELTS: { overall: 5, listening: 5, reading: 5, writing: 5, speaking: 5 },
        OET: { listening: "B", reading: "B", writing: "B", speaking: "B" },
        TOEFL_iBT: {
          overall: 35,
          listening: 4,
          reading: 4,
          writing: 14,
          speaking: 14,
          note: "26 Temmuz 2023 ile 4 Mayıs 2024 arasında alınan TOEFL iBT sınavları Avustralya vize amaçları için onaylanmamıştır.",
        },
        PTE_Academic: { overall: 36, listening: 36, reading: 36, writing: 36, speaking: 36 },
        C1_Advanced: {
          overall: 154,
          listening: 154,
          reading: 154,
          writing: 154,
          speaking: 154,
          note: "12 Şubat 2024'ten itibaren yalnızca Cambridge C1 Advanced kağıt tabanlı sınav sonuçları kabul edilir. 12 Şubat 2024 öncesindeki sınavlar geçerlilik süresi içinde halen kabul edilebilir.",
        },
      },
      labour_agreement_stream_note:
        "Labour Agreement akışında İngilizce şartları, işveren ile Commonwealth arasındaki anlaşmada belirtilmiş olabilir.",
      online_tests_not_accepted: {
        rule:
          "Sınavın tamamı çevrimiçi/uzaktan gözetimli/evden yapılan İngilizce test kanıtları kabul edilmez.",
        examples_not_accepted: [
          "CELPIP Online",
          "IELTS Online",
          "LANGUAGECERT Academic Online",
          "OET@Home",
          "MET Digital taken at-home",
          "TOEFL iBT Home Edition",
        ],
      },
    },
    financial_requirements: {
      status: "Kaynak metinde birincil gereksinim değil",
      notes: [
        "Sağlanan kaynak metin, kişisel mali yeterlilik gereksinimi belirtmemektedir.",
        "Başvuru sahibi, Yıllık Piyasa Ücret Oranı'nı ve Core Skills Income Threshold'u karşılayan bir maaş almalıdır.",
        "Kesin gelir eşiği tutarı için resmi nitelikli vize gelir eşiği kaynağına başvurun.",
      ],
    },
    raw_json: {
      family_members: {
        can_include_family: true,
        notes: [
          "Aile üyeleri, başvuru sahibinin şu anda veya daha önce 457 ya da 482 alt sınıfı vizeye sahip olup olmamasına bağlı olarak ikincil başvuru sahibi olarak dahil edilebilir.",
          "İkincil başvuru sahipleri sağlık ve karakter şartlarını karşılamalıdır.",
          "Başvuru gönderildikten sonra aile üyeleri eklenemez; ancak uygunsa daha sonra subsequent entrant olarak başvurabilirler.",
        ],
      },
    },
  },
  "491": {
    key_requirements: [
      "Eyalet/bölge adaylığı almak veya uygun bir akraba tarafından sponsor edilmek",
      "İlgili nitelikli meslek listesinde bir mesleğe sahip olmak",
      "Meslek için uygun beceri değerlendirmesine sahip olmak",
      "Başvuru daveti almak",
      "Puan testini karşılamak",
      "En az 65 puan almak",
      "Davet tarihinde 45 yaşın altında olmak",
      "Davet anında en az Yeterli İngilizceye sahip olmak",
      "Onaylanırsa belirlenmiş bölgesel alanda yaşamak, çalışmak ve eğitim görmek",
      "Sağlık ve karakter şartlarını karşılamak",
      "Avustralya Hükümetine borçları ödemiş olmak",
      "18 yaş ve üzerindekiler için Avustralya Değerler Beyanı'nı imzalamak",
    ],
    documents_required: [
      "SkillSelect üzerinden EOI",
      "Başvuru daveti",
      "Uygun beceri değerlendirmesi",
      "Kimlik belgeleri",
      "Yeterli İngilizce kanıtı",
      "Puan beyanlarını destekleyen kanıtlar",
      "Gerekliyse karakter belgeleri ve polis kayıtları",
      "İstenirse sağlık muayenesi sonuçları",
      "Varsa partner belgeleri",
      "Varsa bağımlı çocuk belgeleri",
      "Akraba sponsorluğu varsa sponsor beyanı",
      "Sponsorun uygun akraba olduğuna dair kanıt",
      "Sponsorun 18+ olduğuna dair kanıt",
      "Sponsorun Avustralya vatandaşı/daimi oturumlu/uygun Yeni Zelanda vatandaşı olduğuna dair kanıt",
      "Sponsorun belirlenmiş bölgede ikamet ettiğine dair kanıt",
      "İngilizce olmayan belgeler için çeviriler",
    ],
    application_steps: [
      "SkillSelect üzerinden EOI gönderin",
      "491 davetli yolunu seçin",
      "Eyalet/bölge adaylığı mı yoksa akraba sponsorluğu mu istediğinizi belirtin",
      "Adaylık, sponsorluk veya davet turunu bekleyin",
      "Seçilirseniz başvuru daveti alın",
      "Davet tarihinden itibaren 60 gün içinde ImmiAccount üzerinden başvurun",
      "Belgeleri yükleyip ilk başvuru ücretini ödeyin",
      "İstenirse ek bilgi taleplerine yanıt verin",
      "İstenirse sağlık muayenesi veya biyometriyi tamamlayın",
      "Başvuru sürecinde yasal statünüzü koruyun",
      "Yazılı vize sonucunu bekleyin",
    ],
    visa_conditions: [
      "5 yıl geçerli geçici vize",
      "Belirlenmiş bölgesel alanlarda yaşama, çalışma ve eğitim zorunluluğu",
      "Vize geçerliyken Avustralya'ya giriş çıkış",
      "Yurt dışında geçirilen süre vizeyi uzatmaz",
      "Uygunsa 3 yıl sonra 191 kalıcı oturumuna başvuru imkanı",
      "Bu vize uzatılamaz",
      "Vize sahibi aile üyeleri de bölgesel alanlarda yaşamalı/çalışmalı/eğitim görmelidir",
      "Tüm vize koşullarına ve Avustralya yasalarına uyulmalıdır",
    ],
    risks: [
      "Davet yoksa başvuru yapılamaz",
      "65 puan altı davet alınamamasına neden olur",
      "EOI beyanlarına göre davet puanı 65'in üzerinde olabilir",
      "Davet tarihinde yaş 45'in altında olmalıdır",
      "Beceri değerlendirmesi uygun ve geçerli olmalıdır",
      "Meslek ilgili listede olmalıdır",
      "Adaylık/sponsorluk geçerli olmalıdır",
      "Adaylık geri çekilirse vize verilmeyebilir",
      "Onaylanırsa yalnızca belirlenmiş bölgesel alanlarda yaşama/çalışma/eğitim şartı vardır",
      "491 sahipleri genelde 3 yıl dolmadan bazı kalıcı vizelere başvuramaz",
      "Eksik veya hatalı bilgi başvuruyu geciktirebilir veya olumsuz etkileyebilir",
    ],
    english_requirements: {
      required_level: "Yeterli İngilizce",
      summary:
        "Davet anında birincil başvuru sahibinin en az Yeterli İngilizceye sahip olması gerekir. 18+ aile üyeleri için Functional English veya ikinci taksit ücreti gerekebilir.",
      passport_exemptions: [
        "Kanada",
        "Yeni Zelanda",
        "İrlanda Cumhuriyeti",
        "Büyük Britanya ve Kuzey İrlanda Birleşik Krallığı",
        "Amerika Birleşik Devletleri",
      ],
      tests_taken_on_or_after_2025_08_07: {
        C1_Advanced: { listening: 163, reading: 163, writing: 170, speaking: 179 },
        CELPIP_General: { listening: 7, reading: 7, writing: 7, speaking: 7 },
        IELTS_Academic: { listening: 6, reading: 6, writing: 6, speaking: 6 },
        IELTS_General_Training: { listening: 6, reading: 6, writing: 6, speaking: 6 },
        MET: { listening: 56, reading: 55, writing: 57, speaking: 48 },
        OET: { listening: 290, reading: 310, writing: 290, speaking: 330 },
        LANGUAGECERT_Academic: { listening: 57, reading: 60, writing: 64, speaking: 70 },
        PTE_Academic: { listening: 47, reading: 48, writing: 51, speaking: 54 },
        TOEFL_iBT: {
          listening: 16,
          reading: 16,
          writing: 19,
          speaking: 19,
          note: "Kayıt sırasında Taking TOEFL for Australia seçilmelidir.",
        },
      },
      tests_taken_on_or_before_2025_08_06: {
        C1_Advanced: { listening: 169, reading: 169, writing: 169, speaking: 169 },
        IELTS: { listening: 6, reading: 6, writing: 6, speaking: 6 },
        OET: { listening: "B", reading: "B", writing: "B", speaking: "B" },
        PTE_Academic: { listening: 50, reading: 50, writing: 50, speaking: 50 },
        TOEFL_iBT: {
          listening: 12,
          reading: 13,
          writing: 21,
          speaking: 21,
          note: "26 Temmuz 2023 ile 4 Mayıs 2024 arasında alınan TOEFL iBT sınavları Avustralya vize amaçları için onaylanmamıştır.",
        },
      },
      functional_english_for_family_members: {
        summary:
          "18 yaş ve üzeri aile üyeleri Functional English göstermeli veya ikinci taksit ücreti ödemelidir.",
      },
      online_tests_not_accepted: {
        rule: "Sınavın tamamı çevrimiçi/uzaktan gözetimli/evden yapılan İngilizce test kanıtları kabul edilmez.",
        examples_not_accepted: [
          "CELPIP Online",
          "IELTS Online",
          "LANGUAGECERT Academic Online",
          "MET Digital taken at-home",
          "OET@Home",
          "TOEFL iBT Home Edition",
        ],
      },
    },
    financial_requirements: {
      status: "Kaynak metinde birincil gereksinim değil",
      notes: [
        "Kaynak metin, subclass 491 için özel bir kişisel mali yeterlilik gereksinimi açıklamamaktadır.",
        "Vize ücretleri ve olası ikinci taksit ücretleri uygulanabilir.",
        "Fonksiyonel İngilizce'nin altındaki aile üyeleri için ikinci taksit ücreti AUD 4.890'dır.",
      ],
    },
    raw_json: {
      occupation_requirements: {
        summary: "Başvuru sahibinin, Skilled Regional subclass 491 vizesi için uygun nitelikli mesleklerin birleşik listesindeki bir mesleğe sahip olması gerekir.",
        notes: [
          "Subclass 491, eyalet veya bölge adaylığı ya da uygun akraba sponsorluğu içerebilir.",
          "Eyalet ve bölge devlet kurumlarının kendi adaylık kriterleri vardır.",
          "Meslek uygunluğu, ilgili nitelikli meslek listesi ile adaylık veya sponsorluk yoluna göre kontrol edilmelidir.",
        ],
      },
      points_test_rules: {
        minimum_points_required: 65,
        summary: "Subclass 491 puan testine tabi bir vizedir. Başvuru sahibinin en az 65 puan alması gerekir ve EOI beyanları, adaylık veya uygun akraba sponsorluğuna göre davet alabilir.",
        note: "Ayrıntılı puan kategorileri, subclass'a özgü resmi farklar belirlenmedikçe 189/190 için kullanılan nitelikli göç puan tablosunu yeniden kullanmalıdır.",
      },
      regional_requirements: {
        summary: "Vize sahipleri Avustralya'nın belirlenmiş bölgesel alanlarında yaşamalı, çalışmalı ve eğitim görmelidir.",
        pathway_to_permanent_residence: "Uygun olunması halinde 3 yıl sonra Permanent Residence (Skilled Regional) subclass 191 için başvuru yapılabilir.",
        cannot_apply_for_certain_permanent_visas_before_3_years: [
          "Subclass 820 Partner vizesi",
          "Subclass 132 Business Talent vizesi",
          "Subclass 186 Employer Nomination Scheme vizesi",
          "Subclass 188 Business Innovation and Investment vizesi",
          "Subclass 189 Skilled Independent vizesi",
          "Subclass 190 Skilled Nominated vizesi",
          "Subclass 858 Global Talent vizesi",
        ],
      },
      nomination_or_sponsorship: {
        options: [
          "Avustralya eyalet veya bölge devlet kurumu tarafından aday gösterilme",
          "Uygun bir akraba tarafından sponsor edilme",
        ],
        eligible_relative_sponsor_requirements: [
          "18 yaş veya üzerinde olmak",
          "Genellikle Avustralya'nın belirlenmiş bir bölgesinde ikamet etmek",
          "Avustralya vatandaşı, Avustralya daimi oturum sahibi veya uygun Yeni Zelanda vatandaşı olmak",
          "Başvuru sahibinin veya partnerinin uygun akrabası olmak",
        ],
        eligible_relatives: [
          "Ebeveyn",
          "Çocuk veya üvey çocuk",
          "Erkek veya kız kardeş",
          "Evlatlık erkek veya kız kardeş",
          "Üvey erkek veya kız kardeş",
          "Teyze veya amca/dayı",
          "Evlatlık teyze veya amca/dayı",
          "Üvey teyze veya amca/dayı",
          "Yeğen",
          "Evlatlık yeğen",
          "Üvey yeğen",
          "Büyük ebeveyn",
          "Birinci dereceden kuzen",
        ],
      },
    },
  },
  "820_801": {
    key_requirements: [
      "Avustralya vatandaşı/daimi oturumlu/uygun Yeni Zelanda vatandaşı eş veya fiili partnerle gerçek bir ilişki içinde olmak",
      "Eşin veya fiili partnerin başvuru sahibi için sponsor olması",
      "Geçici 820 başvurusu sırasında Avustralya'da bulunmak",
      "Başvuruya dahil aile üyelerinin de Avustralya'da olması",
      "Geçici vize kararı verilirken Avustralya içinde veya dışında olmak",
      "Çoğu durumda 18 yaş veya üzerinde olmak",
      "Eş/fiili partner ilişki şartlarını karşılamak",
      "Sağlık şartlarını karşılamak",
      "Karakter şartlarını karşılamak",
      "Avustralya Hükümetine borç olmaması veya ödeme planı bulunması",
      "Gerekiyorsa Avustralya Değerler Beyanı'nı imzalamak",
    ],
    documents_required: [
      "Pasaport ve kimlik belgeleri",
      "Her iki ebeveyn adını içeren doğum belgesi veya kabul edilen alternatif kimlik belgesi",
      "Varsa ulusal kimlik kartı",
      "Varsa isim değişikliği kanıtı",
      "İlişki geçmişi beyanı",
      "Evliyseniz evlilik belgesi veya evliliğin Avustralya'da geçerli olduğuna dair kanıt",
      "Varsa fiili ilişki kanıtı",
      "Muafiyet yoksa en az 12 aylık fiili ilişki kanıtı",
      "Ortak finansal ilişki kanıtları (mortgage, kira, kredi, banka hesabı, fatura vb.)",
      "Ortak yaşam düzenine ilişkin kanıtlar",
      "Sosyal ilişki kanıtları (ortak davetler, seyahat, tanık beyanları vb.)",
      "Uzun vadeli bağlılık kanıtları",
      "Varsa önceki ilişkilere dair kanıtlar",
      "İstenirse sağlık muayenesi kanıtı",
      "Gerekliyse Avustralya polis belgesi",
      "Gerekliyse yurt dışı polis belgeleri",
      "Varsa askerlik kayıtları",
      "Sponsorun vatandaşlık/oturum durumunu gösteren kanıt",
      "Sponsor tarafından doldurulan partner sponsorluk formu",
      "Varsa bağımlı çocuk belgeleri",
      "18 yaş altı için ebeveyn sorumluluk belgeleri (varsa)",
      "İngilizce olmayan belgeler için çeviriler",
    ],
    application_steps: [
      "İlişki, kimlik, sponsorluk, sağlık, karakter ve aile belgelerini hazırlayın",
      "Avustralya'dayken ImmiAccount üzerinden online başvurun",
      "Family ve Stage 1 Partner or Prospective Marriage Visa seçin",
      "Başvuruyu tamamlayıp ücreti ödeyin",
      "Başvuruyu gönderin",
      "Sponsorla Transaction Reference Number/Application ID paylaşın",
      "Sponsor ImmiAccount üzerinden sponsorluk başvurusu yapsın",
      "Destekleyici belgeleri ekleyin",
      "Gerekliyse sağlık muayenelerini tamamlayın",
      "Gerekliyse karakter belgeleri ve polis kayıtlarını sunun",
      "İstenirse ek bilgi taleplerine yanıt verin",
      "Başvuru süresince Avustralya'da yasal statünüzü koruyun",
      "820 geçici vize için yazılı kararı bekleyin",
      "Uygun zamanda 801 kalıcı aşama için ek belgeleri sunun",
    ],
    visa_conditions: [
      "Avustralya'da yaşama, çalışma ve eğitim",
      "Vize süresince Avustralya'ya giriş çıkış",
      "Avustralya yasalarına ve vize koşullarına uyum",
      "Vize detayları için VEVO kullanımı",
      "801 uygunluğunu etkileyecek başka vize almamaya dikkat",
      "820 onaylandıktan sonra başvuruya aile üyesi eklenemez",
      "İlişki durumu, iletişim bilgileri, pasaport bilgileri veya çocuk doğumu gibi değişiklikleri bildirme",
    ],
    risks: [
      "İlişkinin sona ermesi geçici veya kalıcı partner vize sonucunu etkileyebilir",
      "Yetersiz ilişki kanıtı başvuruyu geciktirebilir veya olumsuz etkileyebilir",
      "Eksik sponsorluk bilgisi bazı durumlarda başvuruyu geçersiz kılabilir",
      "Esas vizesi olmayan başvuru sahipleri için ek kriterler uygulanabilir",
      "Bazı önceki ret/iptaller uygunluğu etkileyebilir",
      "Bazı bölgesel vize sahipleri başvuru öncesi 2-3 yıl beklemek zorunda olabilir",
      "No further stay koşulu başvuruyu engelleyebilir (kaldırılmadıkça)",
      "Sponsorun onaylanması gerekir",
      "Subclass 444 verilmesi bazı durumlarda 801 uygunluğunu etkileyebilir",
      "Başka bir vize verilirse 801 uygunluğu kaybedilebilir",
      "Yanlış/eksik bilgi gecikme, geçersizlik veya ret doğurabilir",
    ],
    english_requirements: {
      status: "Kaynak metinde birincil başvuru sahibi için zorunlu değil",
      notes: [
        "Sağlanan kaynak metin, birincil 820 başvuru sahibi için resmi İngilizce sınav şartı belirtmemektedir.",
      ],
    },
    financial_requirements: {
      status: "Kaynak metinde gelir eşiği belirtilmemiş",
      notes: [
        "Sağlanan kaynak metin, başvuru sahibi için kişisel bir gelir eşiği belirtmemektedir.",
        "Başvuru sahibi doğru vize başvuru ücretini ödemelidir.",
        "Ek maliyetler sağlık muayeneleri, polis belgeleri ve biyometri içerebilir.",
        "Sponsor, başvuru sahibi ve dahil edilen aile üyelerine mali yardım ve konaklama konusunda destek olmalıdır.",
      ],
    },
    raw_json: {
      relationship_requirements: {
        summary: "Başvuru sahibi, Avustralya vatandaşı, Avustralya daimi oturum sahibi veya uygun Yeni Zelanda vatandaşı bir kişinin eşi ya da fiili partneri olmalıdır.",
        spouse: {
          requirement: "Evli bir ilişki içinde olunmalı ve evlilik Avustralya'da geçerli olmalıdır.",
          minimum_age_note: "Evli başvuru sahipleri, çoğu durumda başvuru sırasında 18 yaş veya üzerinde olmalıdır.",
        },
        de_facto: {
          requirement: "Fiili partner ilişkisinde olunmalıdır.",
          usual_minimum_duration: "Genellikle başvurudan hemen önce en az 12 ay.",
          notes: [
            "Sadece flört dönemi veya çevrimiçi ilişki, fiili partner ilişkisi olarak sayılmayabilir.",
            "12 aylık şart, zorlayıcı ve insani durumlarda uygulanmayabilir.",
            "12 aylık şart, bazı insani vize durumlarında uygulanmayabilir.",
            "İlişki bir Avustralya eyaleti veya bölge makamına kayıtlıysa 12 aylık şart uygulanmayabilir.",
          ],
        },
        evidence_categories: {
          financial: [
            "Ortak mortgage veya kira sözleşmesi belgeleri",
            "Büyük varlıklar için ortak krediler",
            "Ortak banka hesap dökümleri",
            "Her iki isimde düzenlenmiş ev faturaları",
          ],
          household: [
            "Ev işlerinin nasıl paylaşıldığına dair beyan",
            "Her iki isimde düzenlenmiş ev faturaları",
            "Her iki partnere de gönderilmiş posta veya e-postalar",
            "Çocuklar için ortak sorumluluğu gösteren belgeler",
            "Yaşam düzenini kanıtlayan belgeler",
          ],
          social: [
            "İlişkiyi bilen kişilerden Form 888 tanık beyanları",
            "Ortak davetler veya birlikte dışarı çıkıldığını gösteren kanıtlar",
            "Ortak arkadaş çevresine dair kanıt",
            "İlişkinin devlet kurumlarına, kamuya veya ticari kuruluşlara bildirildiğine dair kanıt",
            "Ortak sportif, kültürel veya sosyal etkinlik kanıtları",
            "Birlikte seyahat edildiğine dair kanıt",
          ],
          commitment: [
            "Birbirinin geçmişi ve aile durumu hakkında bilgi",
            "Birleşik kişisel meseleler",
            "Ayrıyken iletişimin sürdürüldüğüne dair kanıt",
            "Partnerlerin akraba olmadığını gösteren kanıt",
            "Varsa vasiyet şartları",
          ],
        },
        relationship_history_statement_should_cover: [
          "Çiftin ilk ne zaman, nerede ve nasıl tanıştığı",
          "İlişkinin nasıl geliştiği",
          "Birlikte ne zaman yaşamaya başladıkları, nişanlandıkları veya evlendikleri",
          "Çiftin birlikte neler yaptığı",
          "Ayrı geçirilen zaman",
          "İlişkideki önemli olaylar",
          "Gelecek planları",
        ],
      },
      pathway: {
        summary: "Subclass 820, ülke içi Partner vizesinin geçici aşamasıdır; subclass 801 ise kalıcı aşamasıdır.",
        stage_1: {
          subclass: "820",
          type: "geçici",
          description: "Kalıcı Partner vizesi işlenirken başvuru sahibinin Avustralya'da geçici olarak yaşamasına olanak tanır.",
        },
        stage_2: {
          subclass: "801",
          type: "kalıcı",
          description: "Kalıcı aşama değerlendirmesinin ardından başvuru sahibinin Avustralya'da kalıcı olarak yaşamasına olanak tanır.",
        },
        permanent_stage_timing_note: "Kalıcı aşama değerlendirmesi genellikle geçici ve kalıcı Partner vizelerine başvurudan 2 yıl sonra, uygunluk tarihinden itibaren başlar.",
      },
      permanent_stage_801: {
        subclass: "801",
        visa_name: "Partner vizesi (Kalıcı)",
        stage: "kalıcı",
        stay_period: "Süresiz",
        cost: "Geçici ve kalıcı Partner vizelerine başvururken ödenir",
        processing_time_note: "İşlem süresi, genellikle geçici ve kalıcı Partner vizelerine başvurudan 2 yıl sonra başlayan uygunluk tarihinden itibaren hesaplanır.",
        key_requirements: [
          "Geçici Partner vizesi subclass 820 veya Dependent Child vizesi subclass 445 sahibi olmak",
          "Çoğu durumda sponsorla gerçek ve devam eden ilişkide olmaya devam etmek",
          "Genellikle subclass 820 ve 801 vizelerine başvurudan beri iki yıl geçmiş olması",
          "Sağlık şartlarını karşılamaya devam etmek",
          "Avustralya Hükümetine borç olmaması veya geri ödeme düzenlemesinin yapılmış olması",
          "18 yaş altındaki başvuru sahipleri için vize verilmesinin çocuğun üstün yararına olması",
        ],
        rights_and_benefits: [
          "Avustralya'da kalıcı olarak yaşama, çalışma ve eğitim",
          "Medicare erişimi",
          "Uygun aile üyelerine sponsor olabilme",
          "Veriliş tarihinden itibaren 5 yıl boyunca Avustralya'ya giriş çıkış yapabilme",
          "Uygunsa Avustralya vatandaşlığına başvurabilme",
          "Uygunsa Adult Migrant English Program kapsamında ücretsiz İngilizce derslerine katılabilme",
        ],
        documents_required: [
          "En güncel pasaportun kimlik sayfaları",
          "Gerekliyse güncel Avustralya polis belgesi",
          "Gerekliyse yurt dışı polis belgeleri",
          "Sponsorla ilişkinin sürdüğüne dair kanıt",
          "Sponsor tarafından tamamlanan Commonwealth yasal beyanı",
          "Evliyseniz evlilik belgesi",
          "Varsa fiili ilişki kanıtı",
          "Mali kanıtlar",
          "Ev yaşamına ilişkin kanıtlar",
          "Sosyal kanıtlar",
          "Bağlılık kanıtları",
          "Form 888 tanık beyanları",
          "Varsa aile üyesi belgeleri",
          "İngilizce olmayan belgeler için çeviriler",
        ],
        relationship_evidence: {
          summary: "Başvuru sahibi, geçici Partner vizesine sponsor olan aynı kişinin eşi ya da fiili partneri olmaya devam ettiğine dair kanıt sunmalıdır.",
          sponsor_statutory_declaration_should_cover: [
            "Çiftin birbirine, diğer herkesi dışlayacak şekilde karşılıklı bağlılığı olup olmadığı",
            "İlişkinin gerçek ve devam ediyor olup olmadığı",
            "Çiftin birlikte yaşayıp yaşamadığı veya kalıcı olarak ayrı yaşayıp yaşamadığı",
            "İlişkinin ne zaman başladığı ve ne kadar süredir birlikte yaşandığı",
            "Çiftin paylaştığı mali yükümlülükler",
            "Çocuklara ortak sorumluluk dahil ev yaşamının niteliği",
            "İlişkinin sosyal yönleri",
            "Birbirlerine olan bağlılığın niteliği",
            "Gelecek planları",
          ],
          evidence_categories: {
            financial: [
              "Ortak mortgage veya kira sözleşmesi belgeleri",
              "Büyük varlıklar için ortak krediler",
              "Ortak banka hesap dökümleri",
              "Her iki isimde düzenlenmiş ev faturaları",
            ],
            household: [
              "Ev işlerinin nasıl paylaşıldığına dair beyan",
              "Her iki isimde düzenlenmiş ev faturaları",
              "Her iki partnere de gönderilmiş posta veya e-postalar",
              "Çocuklar için ortak sorumluluğu gösteren belgeler",
              "Yaşam düzenini kanıtlayan belgeler",
            ],
            social: [
              "Form 888 tanık beyanları",
              "Ortak davetler",
              "Ortak arkadaşlara dair kanıt",
              "İlişkinin devlet kurumlarına, kamuya veya ticari kuruluşlara bildirildiğine dair kanıt",
              "Ortak sportif, kültürel veya sosyal etkinlik kanıtları",
              "Birlikte seyahat edildiğine dair kanıt",
            ],
            commitment: [
              "Birbirinin geçmişi ve aile durumu hakkında bilgi",
              "Birleşik kişisel meseleler",
              "Ayrıyken iletişimin sürdürüldüğüne dair kanıt",
              "Partnerlerin akraba olmadığını gösteren kanıt",
              "Varsa vasiyet şartları",
            ],
          },
        },
        application_steps: [
          "VEVO üzerinden mevcut vize durumunu kontrol edin",
          "Kalıcı aşama değerlendirmesi için uygun hale gelene kadar bekleyin; bu genellikle geçici ve kalıcı Partner vizelerine başvurudan 2 yıl sonradır",
          "Güncel kimlik, karakter ve ilişki kanıtlarını toplayın",
          "ImmiAccount'a giriş yapın",
          "New application seçin",
          "Family seçin",
          "Stage 2 - Permanent Partner Visa Assessment seçin",
          "Başvuruyu tamamlayın",
          "Destekleyici belgeleri ekleyin",
          "Kalıcı aşama değerlendirmesi için belgeleri gönderin",
          "Başvuruyu ImmiAccount üzerinden takip edin ve yönetin",
          "İstenirse ek bilgi taleplerine yanıt verin",
          "Yazılı kararı bekleyin",
        ],
        visa_conditions: [
          "Kalıcı oturum",
          "Avustralya yasalarına uyma zorunluluğu",
          "Veriliş tarihinden itibaren 5 yıl geçerli seyahat hakkı",
          "Seyahat hakkı süresi dolduktan sonra kalıcı oturum sahibi olarak yeniden giriş için Resident Return vizesi gerekebilir",
          "Kalıcı Partner vizesi verildikten sonra aile üyesi eklenemez",
        ],
        risks: [
          "Kalıcı aşama genellikle ilk partner vizesi başvurusundan 2 yıl geçmeden değerlendirilemez",
          "İlişkinin bozulması, bazı istisnalar bulunsa da kalıcı vize sonucunu etkileyebilir",
          "Bazı durumlarda aile içi şiddet hükümleri ilgili olabilir",
          "Eksik belgeler işlemleri geciktirebilir",
          "Yanlış bilgiler başvuruyu etkileyebilir",
          "Süresi dolmuş polis belgelerinin yenilenmesi gerekebilir",
          "Kalıcı Partner vizesi reddedilirse kişi artık geçici Partner vizesine sahip olmayabilir",
        ],
        family_members: {
          dependent_child_445_pathway: "Subclass 820 verildikten sonra kalıcı Partner vizesi başvurusuna bağımlı çocuk eklemek için çocuğun genellikle Dependent Child vizesi subclass 445 sahibi olması ve Avustralya'da bulunması gerekir.",
          cannot_add_after_grant: "Kalıcı Partner vizesi subclass 801 verildikten sonra aile üyeleri eklenemez.",
        },
        sponsor_801_requirements: {
          summary: "Sponsor, başvuru sahibine geçici Partner vizesi için sponsor olan aynı kişi olmalı ve başvuru sahibiyle evli veya fiili partner ilişkisini sürdürmelidir.",
          documents_required: [
            "İmza gösteren en güncel pasaportun kişisel bilgiler sayfası veya Avustralya sürücü belgesi",
            "İlişkiye ilişkin tamamlanmış Commonwealth yasal beyanı",
          ],
          obligations: [
            "Partnere ve dahil edilen aile üyelerine sponsor olmak",
            "Mali destek ve konaklama desteği sağlamak",
            "Koşullar değişirse Bakanlığı bilgilendirmek",
          ],
          withdrawal_note: "Vize verildikten sonra sponsor geri çekilemez; ancak kalıcı Partner vizesi kararı verilmeden önce sponsorluk geri çekilebilir.",
        },
      },
      sponsor_requirements: {
        summary: "Sponsor genellikle başvuru sahibinin partneridir ve onaylanmış olmalıdır.",
        who_can_sponsor: [
          "Avustralya vatandaşı",
          "Avustralya daimi oturum sahibi",
          "Uygun Yeni Zelanda vatandaşı",
        ],
        sponsor_obligations: [
          "Partnere ve dahil edilen aile üyelerine sponsor olmak",
          "Partnere ve dahil edilen aile üyelerine mali destek sağlamak",
          "Partnere ve dahil edilen aile üyelerine konaklama konusunda yardımcı olmak",
        ],
        sponsor_age: "Sponsor 18 yaş veya üzerinde olmalıdır. Sponsor 18 yaşından küçükse ve başvuru sahibiyle evliyse, bir ebeveyn veya vasi sponsor olabilir.",
        sponsorship_duration: "Sponsorluk genellikle, başvuru sahipleri vize verildiğinde Avustralya'daysa geçici partner vizesi verildikten 2 yıl sonra; başvuru sahipleri veriliş anında Avustralya dışındaysa Avustralya'ya sonraki girişten 2 yıl sonra sona erer.",
        sponsor_documents: [
          "Avustralya vatandaşlığı, daimi oturum veya uygun Yeni Zelanda vatandaşlığı kanıtı",
          "Pasaport kopyası",
          "Doğum belgesi kopyası",
          "Yüz fotoğrafı",
          "Sponsor Avustralya daimi oturum sahibi veya uygun Yeni Zelanda vatandaşıysa, genellikle Avustralya'da yaşadığını gösteren kanıt",
          "Avustralya polis belgesi",
          "Gerekliyse yurt dışı polis belgesi",
          "İlgili mahkumiyetlerin vize başvuru sahibine açıklanmasına dair yazılı onay",
        ],
        sponsor_risks: [
          "Karakter şartları karşılanmazsa sponsorluk onaylanmayabilir",
          "Çocuklarla ilgili bazı suçlar için sponsorluk sınırlamaları vardır",
          "Sponsor, kalıcı Partner vizesi subclass 801 kararı öncesinde sponsorluk geri çekebilir",
          "Sponsor, subclass 820 verildikten sonra sponsorluğunu geri çekemez",
        ],
      },
      family_members: {
        can_include_dependent_child: true,
        notes: [
          "Bağımlı çocuk, başvuru yapılırken ya da yapıldıktan sonra ancak geçici vize kararı verilmeden önce dahil edilebilir.",
          "Başvuru sahibiyle birlikte başvuran aile üyeleri Avustralya'da bulunmalıdır.",
          "Aile üyeleri sağlık ve karakter şartlarını karşılamalıdır.",
          "Subclass 820 verildikten sonra, aile üyeleri subclass 820 başvurusuna eklenemez.",
          "Bağımlı bir çocuğun, kalıcı Partner vizesi başvurusuna dahil edilmeden önce Dependent Child vizesi subclass 445 başvurusu yapması gerekebilir.",
        ],
      },
      domestic_and_family_violence: {
        summary: "Kaynak, aile içi şiddet hükümlerinin uygulanabileceğini ve bilgilerin gizli olduğunu belirtmektedir.",
        notes: [
          "Aile içi şiddet yaşanıyorsa başvuru sahibi geçici ve kalıcı Partner vizeleri için yine de uygun olabilir.",
          "Kaynak, ImmiAccount ve e-posta şifrelerini değiştirmek gibi çevrimiçi güvenlik adımlarını önermektedir.",
        ],
      },
      faq_summary: {
        online_application: "Başvurular genellikle ImmiAccount üzerinden çevrimiçi yapılmalıdır. Kağıt başvurular sadece sınırlı durumlarda ve davet üzerine mümkündür.",
        progress_updates: "Bakanlık standart işlem süreleri içinde ilerleme güncellemesi sağlamaz; başvuru sahipleri ImmiAccount'u kontrol edebilir.",
        urgent_processing: "Zorlayıcı ve insani durumlarda öncelikli işlem değerlendirilebilir, ancak garanti yoktur.",
        health_exams: "Sağlık muayeneleri başvurudan sonra tamamlanabilir ve genellikle 12 ay geçerlidir.",
        withdrawal: "Başvuru sahipleri ImmiAccount üzerinden çevrimiçi geri çekme yapabilir; geri çekmeye dahil edilen yetişkin başvuru sahiplerinin onayı gerekir.",
        review_rights: "Ret kararı incelemeye açıksa, bildirimde inceleme başvurusunun nasıl yapılacağı açıklanır.",
        permanent_stage_documents: "İlk başvurudan bu yana iki yıl geçtiyse ve başvuru sahibi subclass 820 sahibiyse, ImmiAccount'ta Stage 2 Permanent Partner Visa Assessment tamamlanabilir.",
      },
    },
  },
  "485": {
    key_requirements: [
      "Başvuru sırasında Avustralya'da olmak",
      "Başvurudan önceki son 6 ay içinde bir dönemde Student visa (500) sahibi olmak",
      "CRICOS kayıtlı kurumdan uygun bir Avustralya niteliğini (lisans veya üzeri) tamamlamış olmak",
      "Çoğu durumda 50 yaş altında olmak (standart sınır 35 altı; bazı istisnalar olabilir)",
      "İngilizce şartlarını karşılamak",
      "Vize süresince kabul edilebilir sağlık sigortası bulundurmak",
      "Sağlık ve karakter şartlarını (polis belgesi dahil) karşılamak",
      "Avustralya Hükümetine ödenmemiş borcu olmamak",
      "18 yaş ve üzerindeyse Avustralya Değerler Beyanı'nı imzalamak",
    ],
    documents_required: [
      "Geçerli pasaport",
      "CRICOS kayıtlı kurumdan uygun mezuniyet kanıtı",
      "Son 6 ay içinde 500 vizesi sahibi olunduğuna dair kanıt",
      "Asgari eşiği karşılayan İngilizce sınav sonucu",
      "Sağlık sigortası kanıtı",
      "Avustralya polis belgesi",
      "Gerekliyse yurt dışı polis belgeleri",
      "Kimlik belgeleri ve varsa isim değişikliği kanıtı",
      "İstenirse sağlık muayenesi sonuçları",
      "Bağımlı dahil ediliyorsa aile belgeleri",
      "İngilizce olmayan belgeler için çeviriler",
    ],
    application_steps: [
      "Yaş, öğrenci vizesi süresi, nitelik ve İngilizce şartlarını teyit edin",
      "Nitelik, polis belgesi ve sigorta dahil tüm belgeleri toplayın",
      "Avustralya'dayken ImmiAccount üzerinden online başvurun",
      "Başvuru ücretini ödeyin",
      "İstenirse sağlık muayenesini tamamlayın",
      "İstenen polis belgeleri ve ek belgeleri sunun",
      "Ek bilgi taleplerine yanıt verin",
      "Yazılı vize sonucunu bekleyin",
    ],
    visa_conditions: [
      "Geçici vize; istihdamı başvuru sahibi bulur",
      "Vize uzatılamaz; ek kalış için yeni başvuru gerekir",
      "Uygunsa 485 ikinci akışa başvuru mümkün olabilir",
      "Vize süresince uygun sağlık sigortasını sürdürmek zorunludur",
      "Tüm vize koşulları ve Avustralya yasalarına uyulmalıdır",
      "Vize geçerliyken Avustralya'ya giriş çıkış yapılabilir",
      "Yurt dışında geçirilen süre vizeyi uzatmaz",
      "Koşullar değişirse Bakanlığı bilgilendirin",
    ],
    risks: [
      "Başvuru anında Avustralya'da olmak zorunludur",
      "Başvurudan önceki 6 ay içinde öğrenci vizesi sahibi olmak kritik bir şarttır",
      "Yaş şartları uygulanır; standart durumda genelde 35 yaş altı gerekir",
      "İngilizce sınav sonuçları minimum eşiği karşılamalıdır",
      "Nitelik CRICOS kayıtlı kurumdan lisans veya üzeri olmalıdır",
      "İstihdam ve sonraki yollar kişisel koşullara bağlıdır",
      "Vize, nitelikli göç yollarına geçiş garantisi vermez",
      "Eksik veya hatalı bilgi başvuruyu geciktirebilir veya olumsuz etkileyebilir",
    ],
    english_requirements: {
      summary:
        "İngilizce gereksinimleri geçerlidir. Asgari eşikler karşılanmalıdır. Uygulanacak sınav türü ve puan, bireysel koşullara ve sınav tarihine bağlıdır.",
      approximate_standard:
        "Yaklaşık olarak IELTS 6.5 genel düzeyine denk gelir; sınav türü ve tarihe göre beceri bazlı alt eşikler uygulanır.",
      online_tests_note:
        "Evden veya tamamen çevrimiçi sınavlar kabul edilmeyebilir. Güncel kabul edilen formatlar için resmi kaynaklara bakın.",
      notes: [
        "Asgari eşikler uygulanır. Net puan gereksinimi seçilen sınav ve sınav tarihine bağlıdır.",
        "Güncel koşullar için Home Affairs resmi kaynağını kontrol edin.",
      ],
    },
    financial_requirements: {
      status: "Kaynak metinde gelir eşiği belirtilmemiş",
      notes: [
        "Bu vize akışı için belirli bir kişisel gelir eşiği belirtilmemiştir.",
        "Başvuru sahipleri hükümet başvuru ücretini ödemek zorundadır.",
        "Vize süresi boyunca kabul edilebilir sağlık sigortası sürdürülmelidir.",
        "Ek maliyetler sağlık muayeneleri, polis belgeleri ve belge çevirilerini içerebilir.",
      ],
    },
    raw_json: {
      eligibility: {
        age_limit: {
          default: 35,
          note: "Standart yaş sınırı 35 yaş altıdır. Belirli koşullarda daha yüksek sınırlar uygulanabilir.",
          exceptions: [
            "Doktora (PhD) veya araştırma derecesi mezunları bazı koşullarda 50 yaşa kadar uygun olabilir",
            "Hong Kong veya İngiliz Ulusal (Denizaşırı) pasaport sahipleri için farklı yaş eşikleri uygulanabilir",
            "Yaş gereksinimleri güncel resmi kaynaklardan doğrulanmalıdır",
          ],
        },
        location_requirement: {
          must_be_in_australia: true,
          note: "Başvuru sahibinin başvuru sırasında Avustralya'da bulunması gerekir",
        },
        student_visa_requirement: {
          description: "Başvurudan önceki son 6 ay içinde herhangi bir dönemde Student visa (subclass 500) sahibi olunmuş olması gerekir",
        },
        qualification_requirement: {
          description: "CRICOS kayıtlı bir Avustralya kurumundan lisans veya üzeri bir derece tamamlanmış olması gerekir",
          qualification_levels: [
            "Lisans derecesi",
            "Lisans (onurlar) derecesi",
            "Yüksek lisans sertifikası",
            "Yüksek lisans diploması",
            "Ders tabanlı yüksek lisans",
            "Araştırma tabanlı yüksek lisans",
            "Doktora derecesi",
          ],
        },
        police_check_required: true,
        health_insurance_required: true,
      },
      pathway: {
        summary: "Avustralya vize sistemindeki tipik ilerleme yolları; bireysel koşullara bağlı olarak Öğrenci vizesinden Geçici Mezun vizesine ve ardından nitelikli göç yollarına geçişi içerebilir.",
        stage_1: "Öğrenci vizesi (500)",
        stage_2: "Geçici Mezun vizesi (485) — Yükseköğretim Sonrası Çalışma akışı",
        stage_3: "Nitelikli göç yolları (189/190/491) — bireysel koşullara bağlı olarak uygulanabilir",
        progression_note: "Bu yalnızca tipik bir ilerleme bağlamını temsil eder. Göç tavsiyesi niteliği taşımaz ve kalıcı oturum yollarına erişim garantisi vermez.",
      },
    },
  },
};

const zhHansStructuredData: LocaleVisaStructuredMap = {
  "500": {
    key_requirements: [
      "在澳大利亚境内或境外在线申请",
      "注册全日制课程并持有有效的入学确认函（CoE）",
      "持续持有海外学生健康保险（OSHC）",
      "年龄至少为6岁",
      "未满18岁需具备合规的监护安排",
      "在澳大利亚境内申请时需持有符合条件的实质性签证",
      "满足英语语言要求或符合豁免条件",
      "具备覆盖在澳期间的充足经济能力",
      "符合真实学生（Genuine Student）要求",
      "满足健康与品行要求",
      "18岁及以上需签署澳大利亚价值观声明",
      "已偿还欠澳大利亚政府的相关债务",
      "无影响资格的不良签证历史",
    ],
    documents_required: [
      "有效护照",
      "入学确认函（CoE）",
      "如需提供英语能力证明",
      "如需提供资金能力证明",
      "海外学生健康保险（OSHC）",
      "身份证明文件",
      "如需提供体检结果",
      "如需提供无犯罪证明",
      "未满18岁需提供监护及父母同意文件",
      "如适用，配偶与受抚养人相关文件",
      "非英文文件的认证翻译件",
    ],
    application_steps: [
      "提交申请前完成准备工作",
      "使用文件清单工具准备所需材料",
      "通过 ImmiAccount 在线提交申请",
      "上传材料并支付签证申请费，或提供费用豁免证明",
      "按要求补充提交额外信息",
      "如被要求，完成生物信息采集或体检",
      "等待书面签证结果",
    ],
    visa_conditions: [
      "持续就读于符合条件的课程",
      "遵守工作时长限制",
      "持续维持充分的健康保险",
      "遵守澳大利亚法律",
      "签证有效期内可自由出入澳大利亚",
      "该签证不可延期；需延长停留应重新申请新签证",
      "个人情况变化时需通知移民部门",
    ],
    risks: [
      "材料不完整可能导致审理延迟或被拒",
      "缺少或无效 CoE 可能导致申请无效",
      "错误或虚假信息可能导致拒签并影响后续签证",
      "资金证明不足可能导致拒签",
      "未持续持有 OSHC 可能引发合规问题",
      "既往拒签或签证取消记录可能影响资格",
      "未满足真实学生要求可能导致拒签",
    ],
    english_requirements: {
      notes: [
        "不接受全程在线进行的居家/线上英语考试。",
        "部分申请人可能可豁免提交英语成绩证明。",
        "应使用材料清单工具确认需提交的证明。",
      ],
    },
    financial_requirements: {
      schooling_costs_per_child: "每名子女每年至少 AUD 13,502",
    },
  },
  "189": {
    key_requirements: [
      "职业需在相关技术职业清单上",
      "持有合格的职业评估",
      "获得申请邀请",
      "EOI 评分至少达到65分",
      "获邀时年龄低于45岁",
      "具备合格英语能力",
      "满足健康与品行要求",
    ],
    documents_required: [
      "意向申请（EOI）",
      "申请邀请函",
      "职业评估",
      "英语考试成绩",
      "身份证明文件",
      "支持打分主张的证明材料",
    ],
    application_steps: [
      "在 SkillSelect 提交 EOI",
      "等待获邀",
      "准备申请材料",
      "通过 ImmiAccount 提交申请",
      "上传材料",
      "等待签证结果",
    ],
    visa_conditions: [
      "永久居留签证",
      "可在澳大利亚任何地区生活与工作",
      "享有5年出入境权限",
      "可符合申请入籍条件",
    ],
    risks: [
      "未获邀请则无法申请",
      "分数偏低可能无法获邀",
      "不实主张可能导致拒签",
    ],
    english_requirements: {
      required_level: "合格英语",
      IELTS: "各单项 6.0",
      PTE: "需达到同等分数",
    },
    raw_json: {
      occupation_requirements: {
        summary: "职业必须在技术职业清单上。",
        sample_occupations: [
          "会计",
          "土木工程师",
          "软件工程师",
          "注册护士",
          "电工",
          "厨师",
        ],
      },
      points_test_rules: {
        minimum_points: 65,
        age: [
          { range: "18-24", points: 25 },
          { range: "25-32", points: 30 },
          { range: "33-39", points: 25 },
          { range: "40-44", points: 15 },
        ],
        english: [
          { level: "合格", points: 0 },
          { level: "熟练", points: 10 },
          { level: "优秀", points: 20 },
        ],
      },
    },
    financial_requirements: {
      status: "来源文本未列为主要要求",
    },
  },
  "190": {
    key_requirements: [
      "职业需在相关技术职业清单上",
      "持有与职业匹配的合格职业评估",
      "通过 SkillSelect 提交 EOI",
      "获得澳大利亚州或领地政府提名",
      "获得本签证申请邀请",
      "EOI 评分至少达到65分",
      "获邀时年龄低于45岁",
      "获邀时至少达到合格英语水平",
      "满足健康与品行要求",
      "已偿还欠澳大利亚政府的债务",
      "18岁及以上需签署澳大利亚价值观声明",
    ],
    documents_required: [
      "通过 SkillSelect 提交的 EOI",
      "申请邀请函",
      "州或领地提名证明",
      "合格职业评估",
      "身份证明文件",
      "合格英语证明",
      "支持打分主张的证明材料",
      "如适用，关系证明文件",
      "如需提供品行文件与无犯罪证明",
      "如被要求，体检结果",
      "如包含家属，需提供家属相关文件",
      "非英文文件的翻译件",
    ],
    application_steps: [
      "通过 SkillSelect 提交 EOI",
      "选择技术提名 190 子类签证",
      "等待州或领地政府可能发出的提名",
      "获提名后接收申请邀请",
      "在获邀后60个自然日内通过 ImmiAccount 在线申请",
      "上传材料并支付申请费",
      "如被要求，补充提交额外信息",
      "如被要求，完成体检或生物信息采集",
      "等待书面签证结果",
    ],
    visa_conditions: [
      "永久签证",
      "可在澳大利亚生活、工作和学习",
      "自签证获批日起5年内可多次出入境",
      "5年后再次入境可能需申请居民返程签证",
      "可为符合条件的亲属提供担保",
      "可符合申请澳大利亚国籍条件",
      "必须遵守澳大利亚法律",
    ],
    risks: [
      "未获州或领地提名将无法获得该签证邀请",
      "申请后若提名被撤回，申请将变为无效",
      "低于65分将无法获邀",
      "根据 EOI 声明，实际获邀分数可能高于65分",
      "获邀后必须证明打分主张",
      "获邀时年龄必须低于45岁",
      "职业评估必须合格且在有效期内",
      "职业必须在相关技术职业清单上",
      "各州和领地有各自的提名标准",
      "信息不完整或不准确可能导致审理延迟或不利结果",
    ],
    english_requirements: {
      required_level: "合格英语",
      summary: "在获邀时，190 子类申请人必须至少具备合格英语。",
      test_validity: "根据签证子类不同，英语考试成绩通常须在签证申请前 3 年内取得。",
      passport_exemptions: [
        "加拿大",
        "新西兰",
        "爱尔兰共和国",
        "大不列颠及北爱尔兰联合王国",
        "美利坚合众国",
      ],
      tests_taken_on_or_after_2025_08_07: {
        C1_Advanced: { listening: 163, reading: 163, writing: 170, speaking: 179 },
        CELPIP_General: { listening: 7, reading: 7, writing: 7, speaking: 7 },
        IELTS_Academic: {
          listening: 6,
          reading: 6,
          writing: 6,
          speaking: 6,
          note: "符合条件的签证可能接受 IELTS One Skill Retake。",
        },
        IELTS_General_Training: {
          listening: 6,
          reading: 6,
          writing: 6,
          speaking: 6,
          note: "符合条件的签证可能接受 IELTS One Skill Retake。",
        },
        MET: {
          listening: 56,
          reading: 55,
          writing: 57,
          speaking: 48,
          note: "符合条件的签证可能接受 MET Single Section Retake。",
        },
        OET: { listening: 290, reading: 310, writing: 290, speaking: 330 },
        LANGUAGECERT_Academic: { listening: 57, reading: 60, writing: 64, speaking: 70 },
        PTE_Academic: { listening: 47, reading: 48, writing: 51, speaking: 54 },
        TOEFL_iBT: {
          listening: 16,
          reading: 16,
          writing: 19,
          speaking: 19,
          note: "报名时必须选择 Taking TOEFL for Australia。",
        },
      },
      tests_taken_on_or_before_2025_08_06: {
        C1_Advanced: {
          listening: 169,
          reading: 169,
          writing: 169,
          speaking: 169,
          note: "自 2024 年 2 月 12 日至 2025 年 8 月 6 日，仅接受 Cambridge C1 Advanced 纸笔考试成绩。更早的考试在有效期内仍可能被接受。",
        },
        IELTS: {
          listening: 6,
          reading: 6,
          writing: 6,
          speaking: 6,
          note: "IELTS Academic 或 General Training。",
        },
        OET: { listening: "B", reading: "B", writing: "B", speaking: "B" },
        PTE_Academic: { listening: 50, reading: 50, writing: 50, speaking: 50 },
        TOEFL_iBT: {
          listening: 12,
          reading: 13,
          writing: 21,
          speaking: 21,
          note: "2023 年 7 月 26 日至 2024 年 5 月 4 日期间参加的 TOEFL iBT 不被接受用于澳大利亚签证。",
        },
      },
      online_tests_not_accepted: {
        rule: "移民部门不接受完全在线、远程监考或居家完成的英语考试作为证明。",
        examples_not_accepted: [
          "CELPIP Online",
          "IELTS Online",
          "LANGUAGECERT Academic Online",
          "MET Digital taken at-home",
          "OET@Home",
          "TOEFL iBT Home Edition",
        ],
      },
      notes: [
        "2025 年 8 月 6 日及之前参加的考试，可根据签证类型一直作为证明使用至 2028 年 8 月 6 日（含当天）。",
        "某些签证可能允许使用其他形式的证明。",
      ],
    },
    raw_json: {
      occupation_requirements: {
        summary: "申请人必须拥有适用于 Skilled Nominated 190 子类签证的相关技术职业清单中的职业。",
        state_specific_review_required: true,
        notes: [
          "190 子类需要获得澳大利亚州或领地政府机构提名。",
          "每个州或领地都有自己的提名标准和职业优先级。",
          "职业资格应同时根据相关技术职业清单以及提名州或领地的标准进行核查。",
        ],
        states_and_territories: [
          "澳大利亚首都领地",
          "新南威尔士州",
          "北领地",
          "昆士兰州",
          "南澳大利亚州",
          "塔斯马尼亚州",
          "维多利亚州",
          "西澳大利亚州",
        ],
      },
      points_test_rules: {
        minimum_points_required: 65,
        summary: "190 子类属于打分制签证。申请人必须至少获得 65 分，并可能基于 EOI 声明以及州或领地提名获得邀请。",
        note: "除非发现官方针对该子类的特殊差异，否则详细打分类别应复用 189 子类所使用的技术移民打分表。",
      },
    },
    financial_requirements: {
      status: "来源文本未列为主要要求",
      notes: [
        "所提供的来源未说明190子类的具体个人财务能力要求。",
        "英语水平低于功能性英语的家庭成员可能需支付签证费第二笔款项。",
      ],
    },
  },
  "482": {
    key_requirements: [
      "需由获批担保方提名",
      "提名职业需在 Core Skills Occupation List 上",
      "薪资需达到市场薪资并不低于核心技能收入门槛",
      "在提名职业或相关领域具备至少1年经验",
      "如职业要求，需提供有效职业评估",
      "除豁免外，仅可为担保方或其关联实体工作",
      "除豁免外，需满足最低英语要求",
      "境内申请时需持有合适签证",
      "境内申请时需遵守过往签证条件",
      "需维持充分健康保险",
      "需满足健康与品行要求",
      "不得有为签证担保付费的不良记录",
      "不得有影响资格的拒签或取消记录",
      "不得欠澳大利亚政府债务",
      "18岁及以上需签署澳大利亚价值观声明",
    ],
    documents_required: [
      "有效护照",
      "雇主提名 Transaction Reference Number",
      "身份证明文件",
      "如适用，姓名变更证明",
      "如强制要求，职业评估参考号",
      "技能、资历与工作背景证明",
      "相关学历或资格证书",
      "如需，注册或执照证明",
      "简历",
      "工作证明/推荐信",
      "英语能力文件",
      "健康保险证明",
      "如需，体检结果",
      "如需，澳洲无犯罪证明",
      "如需，海外无犯罪证明",
      "如适用，服役记录",
      "如适用，配偶文件",
      "如适用，受抚养人文件",
      "如适用，18岁以下受抚养人监护责任文件",
      "非英文文件翻译件",
    ],
    application_steps: [
      "申请前准备提名、护照、所需职业评估及英语考试",
      "收集身份、技能、职业、英语、保险、品行与家庭文件",
      "通过 ImmiAccount 在线申请",
      "上传材料并支付申请费",
      "如被要求，补交材料",
      "如被要求，完成体检或生物信息采集",
      "审理期间保持合法居留",
      "等待书面结果",
    ],
    visa_conditions: [
      "在提名职业中工作",
      "通常仅为担保企业工作",
      "如由澳洲企业担保，可为其或关联实体工作",
      "入境后90天内或境内获批后90天内开始工作",
      "维持充分健康保险",
      "遵守澳大利亚法律",
      "签证有效期内可出入境",
      "离境时间不延长签证",
      "联系方式、雇主、就业、关系状态或子女出生变更需通知移民部门",
    ],
    risks: [
      "雇主提名未获批，签证无法获批",
      "材料不完整可能导致延迟或拒签",
      "如需职业评估但未在申请前启动，申请可能无效",
      "虚假或误导信息可能导致拒签并影响后续签证",
      "未满足英语要求会影响资格",
      "未维持健康保险可能违反签证条件",
      "既往拒签或取消记录可能影响资格",
      "近3年存在为担保付费行为可能影响资格",
      "若工作终止，可能需更换雇主或安排离境",
    ],
    english_requirements: {
      summary: "482 紧缺技能签证主申请人除豁免外需满足最低英语要求。",
      applies_to_streams: ["核心技能通道", "专业技能通道"],
      test_validity: "英语考试通常需在申请前3年内取得。",
      exemptions: [
        "持加拿大护照",
        "持新西兰护照",
        "持爱尔兰共和国护照",
        "持英国护照",
        "持美国护照",
        "在以英语授课为主的至少中学层级机构完成至少5年全日制学习",
        "提名职业将在另一国家的外交或领事机构履行",
        "提名职业将在台湾当局驻外机构履行",
        "提名职业要求执照、注册或会员资格，且申请人已证明具备取得该资格所需的同等或更高英语水平",
        "申请人为海外企业员工，由该企业或其关联实体提名赴澳工作，且保证年收入至少为 AUD 96,400",
      ],
      tests_taken_on_or_after_2025_09_13: {
        single_skill_retake_note:
          "如果该考试提供单项重考选项，则该项成绩可能被接受。",
        CELPIP_General: { listening: 5, reading: 5, writing: 5, speaking: 5 },
        IELTS_Academic: { listening: 5, reading: 5, writing: 5, speaking: 5 },
        IELTS_General_Training: { listening: 5, reading: 5, writing: 5, speaking: 5 },
        LANGUAGECERT_Academic: { listening: 41, reading: 44, writing: 45, speaking: 54 },
        MET: { listening: 49, reading: 47, writing: 45, speaking: 38 },
        OET: { listening: 220, reading: 240, writing: 200, speaking: 270 },
        PTE_Academic: { listening: 33, reading: 36, writing: 29, speaking: 24 },
        TOEFL_iBT: {
          listening: 8,
          reading: 8,
          writing: 9,
          speaking: 14,
          note: "对于 2026 年 1 月 21 日及之后参加的考试，报名时必须选择 Taking TOEFL for Australia。",
        },
      },
      tests_taken_before_2025_09_13: {
        single_sitting_required: true,
        single_skill_retake_accepted: false,
        IELTS: { overall: 5, listening: 5, reading: 5, writing: 5, speaking: 5 },
        OET: { listening: "B", reading: "B", writing: "B", speaking: "B" },
        TOEFL_iBT: {
          overall: 35,
          listening: 4,
          reading: 4,
          writing: 14,
          speaking: 14,
          note: "2023 年 7 月 26 日至 2024 年 5 月 4 日期间参加的 TOEFL iBT 不被接受用于澳大利亚签证。",
        },
        PTE_Academic: { overall: 36, listening: 36, reading: 36, writing: 36, speaking: 36 },
        C1_Advanced: {
          overall: 154,
          listening: 154,
          reading: 154,
          writing: 154,
          speaking: 154,
          note: "自 2024 年 2 月 12 日起，仅接受 Cambridge C1 Advanced 纸笔考试成绩。2024 年 2 月 12 日之前的考试在有效期内仍可能被接受。",
        },
      },
      labour_agreement_stream_note: "劳工协议通道英语要求可能按雇主与联邦协议执行。",
      online_tests_not_accepted: {
        rule: "不接受全程线上、远程监考或居家完成的英语考试证明。",
        examples_not_accepted: [
          "CELPIP Online",
          "IELTS Online",
          "LANGUAGECERT Academic Online",
          "OET@Home",
          "MET Digital taken at-home",
          "TOEFL iBT Home Edition",
        ],
      },
    },
    financial_requirements: {
      status: "来源文本未列为主要要求",
      notes: [
        "所提供的来源文本未说明个人财务能力要求。",
        "申请人的薪资必须达到年度市场薪资率且不低于核心技能收入门槛。",
        "具体收入门槛金额请参考官方签证收入门槛来源。",
      ],
    },
    raw_json: {
      family_members: {
        can_include_family: true,
        notes: [
          "家庭成员能否作为副申请人包含在申请中，取决于申请人当前或过去是否持有 457 或 482 子类签证。",
          "副申请人必须满足健康和品行要求。",
          "提交申请后不能再添加家庭成员，但如符合条件，可在之后以 subsequent entrant 方式申请。",
        ],
      },
    },
  },
  "491": {
    key_requirements: [
      "需获得州/领地提名或符合条件亲属担保",
      "职业需在相关技术职业清单上",
      "需具备合格职业评估",
      "需获得申请邀请",
      "需满足打分测试",
      "至少65分",
      "获邀时年龄低于45岁",
      "获邀时至少达到合格英语",
      "获批后需在指定偏远地区生活、工作和学习",
      "满足健康与品行要求",
      "已偿还政府债务",
      "18岁及以上需签署澳大利亚价值观声明",
    ],
    documents_required: [
      "SkillSelect EOI",
      "申请邀请函",
      "合格职业评估",
      "身份证明文件",
      "合格英语证明",
      "支持打分主张的证据",
      "如需，品行文件与无犯罪证明",
      "如需，体检结果",
      "如适用，配偶文件",
      "如适用，受抚养子女文件",
      "如为亲属担保，担保声明",
      "担保人符合亲属关系证明",
      "担保人18岁以上证明",
      "担保人公民/永居/符合条件新西兰公民证明",
      "担保人通常居住在指定地区证明",
      "非英文文件翻译件",
    ],
    application_steps: [
      "在 SkillSelect 提交 EOI",
      "选择 491 邀请通道",
      "说明申请州担保或亲属担保",
      "等待提名/担保/邀请轮次",
      "获选后接收邀请",
      "在60天内通过 ImmiAccount 申请",
      "上传材料并支付第一笔申请费",
      "如被要求，补交信息",
      "如被要求，完成体检或生物信息采集",
      "审理期间保持合法身份",
      "等待书面结果",
    ],
    visa_conditions: [
      "5年临时签证",
      "须在指定偏远地区生活、工作和学习",
      "签证有效期内可出入境",
      "离境时间不延长签证",
      "符合条件可在3年后申请191",
      "该签证不可延期",
      "持签家庭成员同样需在指定地区生活、工作和学习",
      "需遵守签证条件及澳大利亚法律",
    ],
    risks: [
      "未获邀请则无法申请",
      "低于65分通常无法获邀",
      "实际获邀分数可能高于65分",
      "获邀时年龄必须低于45岁",
      "职业评估必须有效且匹配",
      "职业必须在相关清单上",
      "提名或担保必须有效",
      "提名被撤回可能导致无法获签",
      "获批后仅可在指定偏远地区生活、工作和学习",
      "通常需持491满3年后方可申请部分永居签证",
      "信息不完整或不准确可能导致延迟或不利结果",
    ],
    english_requirements: {
      required_level: "合格英语",
      summary: "获邀时主申请人需至少达到合格英语。18岁以上家庭成员需满足功能性英语或支付第二笔费用。",
      passport_exemptions: [
        "加拿大",
        "新西兰",
        "爱尔兰共和国",
        "大不列颠及北爱尔兰联合王国",
        "美利坚合众国",
      ],
      tests_taken_on_or_after_2025_08_07: {
        C1_Advanced: { listening: 163, reading: 163, writing: 170, speaking: 179 },
        CELPIP_General: { listening: 7, reading: 7, writing: 7, speaking: 7 },
        IELTS_Academic: { listening: 6, reading: 6, writing: 6, speaking: 6 },
        IELTS_General_Training: { listening: 6, reading: 6, writing: 6, speaking: 6 },
        MET: { listening: 56, reading: 55, writing: 57, speaking: 48 },
        OET: { listening: 290, reading: 310, writing: 290, speaking: 330 },
        LANGUAGECERT_Academic: { listening: 57, reading: 60, writing: 64, speaking: 70 },
        PTE_Academic: { listening: 47, reading: 48, writing: 51, speaking: 54 },
        TOEFL_iBT: {
          listening: 16,
          reading: 16,
          writing: 19,
          speaking: 19,
          note: "报名时必须选择 Taking TOEFL for Australia。",
        },
      },
      tests_taken_on_or_before_2025_08_06: {
        C1_Advanced: { listening: 169, reading: 169, writing: 169, speaking: 169 },
        IELTS: { listening: 6, reading: 6, writing: 6, speaking: 6 },
        OET: { listening: "B", reading: "B", writing: "B", speaking: "B" },
        PTE_Academic: { listening: 50, reading: 50, writing: 50, speaking: 50 },
        TOEFL_iBT: {
          listening: 12,
          reading: 13,
          writing: 21,
          speaking: 21,
          note: "2023 年 7 月 26 日至 2024 年 5 月 4 日期间参加的 TOEFL iBT 不被接受用于澳大利亚签证。",
        },
      },
      functional_english_for_family_members: {
        summary: "18岁及以上家庭成员需证明功能性英语，否则可能需支付第二笔费用。",
      },
      online_tests_not_accepted: {
        rule: "不接受全程线上、远程监考或居家完成的英语考试证明。",
        examples_not_accepted: [
          "CELPIP Online",
          "IELTS Online",
          "LANGUAGECERT Academic Online",
          "MET Digital taken at-home",
          "OET@Home",
          "TOEFL iBT Home Edition",
        ],
      },
    },
    financial_requirements: {
      status: "来源文本未列为主要要求",
      notes: [
        "来源文本未说明491子类的具体个人财务能力要求。",
        "可能需支付签证费及第二笔款项。",
        "英语水平低于功能性英语的家庭成员需支付第二笔签证费 AUD 4,890。",
      ],
    },
    raw_json: {
      occupation_requirements: {
        summary: "申请人必须拥有适用于 Skilled Regional 491 子类签证的合资格技术职业合并清单中的职业。",
        notes: [
          "491 子类可能涉及州或领地提名，或符合条件亲属担保。",
          "州和领地政府机构各自有不同的提名标准。",
          "职业资格应根据相关技术职业清单以及提名或担保路径进行核查。",
        ],
      },
      points_test_rules: {
        minimum_points_required: 65,
        summary: "491 子类属于打分制签证。申请人必须至少获得 65 分，并可能基于 EOI 声明、提名或符合条件亲属担保获得邀请。",
        note: "除非识别出该子类的官方特殊差异，否则详细打分类别应复用 189/190 所用的技术移民打分表。",
      },
      regional_requirements: {
        summary: "签证持有人必须在澳大利亚指定偏远地区生活、工作和学习。",
        pathway_to_permanent_residence: "如符合条件，可在 3 年后申请 191 类永久居留（偏远地区技术）。",
        cannot_apply_for_certain_permanent_visas_before_3_years: [
          "820 类伴侣签证",
          "132 类商业人才签证",
          "186 类雇主提名计划签证",
          "188 类商业创新和投资签证",
          "189 类独立技术移民签证",
          "190 类州担保技术移民签证",
          "858 类全球人才签证",
        ],
      },
      nomination_or_sponsorship: {
        options: [
          "由澳大利亚州或领地政府机构提名",
          "由符合条件的亲属担保",
        ],
        eligible_relative_sponsor_requirements: [
          "年满 18 岁",
          "通常居住在澳大利亚指定地区",
          "澳大利亚公民、澳大利亚永久居民或符合条件的新西兰公民",
          "申请人或其配偶/伴侣的符合条件亲属",
        ],
        eligible_relatives: [
          "父母",
          "子女或继子女",
          "兄弟姐妹",
          "收养兄弟姐妹",
          "继兄弟姐妹",
          "姑妈、姨妈、叔叔或舅舅",
          "收养姑妈、姨妈、叔叔或舅舅",
          "继姑妈、姨妈、叔叔或舅舅",
          "侄子、侄女、外甥或外甥女",
          "收养侄甥辈亲属",
          "继侄甥辈亲属",
          "祖父母或外祖父母",
          "第一代表亲",
        ],
      },
    },
  },
  "820_801": {
    key_requirements: [
      "与澳大利亚公民/永居/符合条件新西兰公民配偶或事实伴侣关系真实",
      "需由配偶或事实伴侣担保",
      "申请820阶段时需在澳大利亚境内",
      "共同申请家庭成员也需在澳境内",
      "临时阶段审理时可在境内或境外",
      "多数情况下需年满18岁",
      "满足婚姻或事实伴侣关系要求",
      "满足健康要求",
      "满足品行要求",
      "无政府欠款或已安排偿还",
      "如要求，签署澳大利亚价值观声明",
    ],
    documents_required: [
      "护照及身份证明",
      "载明父母姓名的出生证明或可接受替代文件",
      "如有，国民身份证",
      "如适用，姓名变更证明",
      "关系历史陈述",
      "如已婚，结婚证或婚姻在澳有效证明",
      "如适用，事实伴侣关系证明",
      "如无豁免，至少12个月事实关系证明",
      "财务关系证明（联名房贷/租约/贷款/账户/账单等）",
      "共同生活证明",
      "社会关系证明（共同邀请、旅行、证人声明等）",
      "长期承诺证明",
      "如适用，既往关系证明",
      "如要求，体检证明",
      "如需，澳洲无犯罪证明",
      "如需，海外无犯罪证明",
      "如适用，服役记录",
      "担保人身份资格证明",
      "担保人填写的伴侣担保表格",
      "如适用，受抚养子女文件",
      "如适用，18岁以下申请人的监护责任文件",
      "非英文文件翻译件",
    ],
    application_steps: [
      "准备关系、身份、担保、健康、品行和家庭材料",
      "在澳期间通过 ImmiAccount 在线申请",
      "选择 Family 和 Stage 1 Partner or Prospective Marriage Visa",
      "完成申请并支付费用",
      "提交申请",
      "将 TRN 或 Application ID 提供给担保人",
      "担保人通过 ImmiAccount 提交担保申请",
      "上传支持材料",
      "如需，完成体检",
      "如需，提交品行及无犯罪材料",
      "如被要求，补交信息",
      "审理期间保持在澳合法身份",
      "等待820阶段书面决定",
      "到期后提交801阶段补充材料",
    ],
    visa_conditions: [
      "可在澳生活、工作和学习",
      "持签期间可出入境",
      "遵守澳大利亚法律与签证条件",
      "可通过 VEVO 查看签证信息",
      "避免获取影响801资格的其他签证",
      "820获批后不可再向该申请新增家庭成员",
      "关系、联系方式、护照信息或子女出生变化需通知移民部门",
    ],
    risks: [
      "关系破裂可能影响临时或永久阶段结果",
      "关系证据不足可能导致延迟或不利结果",
      "担保信息缺失在部分情形下可导致申请无效",
      "若申请人不持有实质性签证，可能适用额外标准",
      "既往拒签或取消记录可能影响资格",
      "部分偏远地区签证持有人可能需持签满2-3年后方可申请",
      "No further stay 条款未豁免时可能阻止申请",
      "担保人必须获批",
      "部分情况下444签证可能影响801资格",
      "如获批其他签证，可能失去801资格",
      "错误或不完整信息可能导致延迟、无效或拒签",
    ],
    english_requirements: {
      status: "来源文本未要求主申请人提供英语考试",
      notes: ["提供的来源文本未规定 820 主申请人的正式英语考试要求。"],
    },
    financial_requirements: {
      status: "来源文本未说明收入门槛",
      notes: [
        "所提供的来源文本未说明申请人的个人收入门槛。",
        "申请人须支付正确的签证申请费。",
        "额外费用可能包括体检、无犯罪证明及生物信息采集费用。",
        "担保人须在经济和住宿方面协助申请人及所含家庭成员。",
      ],
    },
    raw_json: {
      relationship_requirements: {
        summary: "申请人必须是澳大利亚公民、澳大利亚永久居民或符合条件的新西兰公民的配偶或事实伴侣。",
        spouse: {
          requirement: "必须处于婚姻关系中，且该婚姻在澳大利亚有效。",
          minimum_age_note: "已婚申请人在大多数情况下申请时必须年满 18 岁。",
        },
        de_facto: {
          requirement: "必须处于事实伴侣关系中。",
          usual_minimum_duration: "通常要求在申请前至少连续 12 个月。",
          notes: [
            "恋爱阶段或仅在线关系的时间可能不算作事实伴侣关系。",
            "在存在令人信服且具同情因素的情况下，12 个月要求可能不适用。",
            "在某些人道主义签证情形下，12 个月要求可能不适用。",
            "如果关系已在澳大利亚州或领地机构登记，12 个月要求可能不适用。",
          ],
        },
        evidence_categories: {
          financial: [
            "联名房贷或租赁文件",
            "重大资产的联名贷款",
            "联名银行账户对账单",
            "双方姓名的家庭账单",
          ],
          household: [
            "关于如何分担家务的说明",
            "双方姓名的家庭账单",
            "寄给双方的邮件或电子邮件",
            "显示共同承担子女责任的文件",
            "证明共同居住安排的文件",
          ],
          social: [
            "了解双方关系的人员出具的 Form 888 证人陈述",
            "联名邀请函或共同外出的证据",
            "共同朋友的证明",
            "向政府、公共或商业机构告知该关系的证明",
            "共同参加体育、文化或社交活动的证明",
            "共同旅行的证明",
          ],
          commitment: [
            "了解彼此背景和家庭情况",
            "共同处理个人事务",
            "分开期间保持联系的证明",
            "证明双方不存在亲属关系的材料",
            "如有，遗嘱条款",
          ],
        },
        relationship_history_statement_should_cover: [
          "双方首次相识的时间、地点和方式",
          "关系如何发展",
          "双方何时开始同住、订婚或结婚",
          "双方共同从事的活动",
          "分开相处的时间",
          "关系中的重要事件",
          "未来计划",
        ],
      },
      pathway: {
        summary: "820子类为境内伴侣签证路径的临时阶段，801子类为永久阶段。",
        stage_1: {
          subclass: "820",
          type: "临时",
          description: "允许申请人在永久伴侣签证审理期间在澳大利亚临时居留。",
        },
        stage_2: {
          subclass: "801",
          type: "永久",
          description: "完成永久阶段评估后，允许申请人在澳大利亚永久居留。",
        },
        permanent_stage_timing_note: "永久阶段评估一般自资格确认日开始，通常为提交临时及永久伴侣签证申请后 2 年。",
      },
      permanent_stage_801: {
        subclass: "801",
        visa_name: "伴侣签证（永久）",
        stage: "永久",
        stay_period: "永久",
        cost: "在申请临时和永久伴侣签证时一并支付",
        processing_time_note: "处理时间自符合资格之日起计算，通常为申请临时及永久伴侣签证后 2 年。",
        key_requirements: [
          "持有 820 类临时伴侣签证或 445 类受抚养子女签证",
          "在大多数情况下，继续与担保人保持真实且持续的关系",
          "通常自申请 820 和 801 签证起已满两年",
          "继续满足健康要求",
          "不欠澳大利亚政府债务或已安排偿还",
          "对任何未满 18 岁申请人而言，签证批准必须符合其最佳利益",
        ],
        rights_and_benefits: [
          "在澳大利亚永久生活、工作和学习",
          "享受 Medicare",
          "为符合条件的家庭成员提供担保",
          "自获签日起 5 年内可自由往返澳大利亚",
          "如符合条件可申请澳大利亚国籍",
          "如符合条件可通过 Adult Migrant English Program 参加免费英语课程",
        ],
        documents_required: [
          "最新护照身份页",
          "如需，当前澳大利亚无犯罪证明",
          "如需，海外无犯罪证明",
          "证明与担保人关系仍在持续的材料",
          "由担保人完成的 Commonwealth 法定声明",
          "如已婚，结婚证",
          "如适用，事实伴侣关系证明",
          "财务证据",
          "共同居住证据",
          "社交证据",
          "承诺关系证据",
          "Form 888 证人陈述",
          "如适用，家庭成员文件",
          "非英文文件的翻译件",
        ],
        relationship_evidence: {
          summary: "申请人必须提供证据，证明其仍是为其担保临时伴侣签证的同一人的配偶或事实伴侣。",
          sponsor_statutory_declaration_should_cover: [
            "双方是否彼此专一并相互承诺",
            "关系是否真实且持续",
            "双方是否共同生活或并未永久分居",
            "关系开始的时间以及共同生活的时长",
            "双方共同承担的财务责任",
            "家庭生活的性质，包括对子女的共同责任",
            "关系的社交层面",
            "彼此承诺的性质",
            "未来计划",
          ],
          evidence_categories: {
            financial: [
              "联名房贷或租赁文件",
              "重大资产的联名贷款",
              "联名银行账户对账单",
              "双方姓名的家庭账单",
            ],
            household: [
              "关于如何分担家务的说明",
              "双方姓名的家庭账单",
              "寄给双方的邮件或电子邮件",
              "显示共同承担子女责任的文件",
              "证明共同居住安排的文件",
            ],
            social: [
              "Form 888 证人陈述",
              "联名邀请函",
              "共同朋友的证明",
              "向政府、公共或商业机构告知该关系的证明",
              "共同参加体育、文化或社交活动的证明",
              "共同旅行的证明",
            ],
            commitment: [
              "了解彼此背景和家庭情况",
              "共同处理个人事务",
              "分开期间保持联系的证明",
              "证明双方不存在亲属关系的材料",
              "如有，遗嘱条款",
            ],
          },
        },
        application_steps: [
          "通过 VEVO 检查当前签证状态",
          "等待符合永久阶段评估资格，通常为申请临时及永久伴侣签证后 2 年",
          "准备最新的身份、品行和关系证据",
          "登录 ImmiAccount",
          "选择 New application",
          "选择 Family",
          "选择 Stage 2 - Permanent Partner Visa Assessment",
          "完成申请",
          "附上支持文件",
          "提交永久阶段评估材料",
          "在 ImmiAccount 中跟踪和管理申请",
          "如被要求，回应补充信息请求",
          "等待书面决定",
        ],
        visa_conditions: [
          "永久居留",
          "必须遵守澳大利亚法律",
          "自获签日起 5 年内享有旅行权限",
          "旅行权限到期后，如需以永久居民身份重新入境，可能需要居民返程签证",
          "永久伴侣签证获批后不得再添加家庭成员",
        ],
        risks: [
          "永久阶段通常要在首次伴侣签证申请后 2 年才能评估",
          "关系破裂可能影响永久签证结果，但某些情况下可能存在例外",
          "某些情况下可能适用家庭暴力 provisions",
          "材料不完整可能延迟处理",
          "错误信息可能影响申请",
          "过期的无犯罪证明可能需要重新办理",
          "若永久伴侣签证被拒，申请人可能不再持有临时伴侣签证",
        ],
        family_members: {
          dependent_child_445_pathway: "若要在 820 子类获批后将受抚养子女加入永久伴侣签证申请，子女通常必须持有 445 类受抚养子女签证并在澳大利亚境内。",
          cannot_add_after_grant: "801 类永久伴侣签证获批后，不得再添加家庭成员。",
        },
        sponsor_801_requirements: {
          summary: "担保人必须是为申请人临时伴侣签证提供担保的同一人，并且必须继续与申请人保持婚姻或事实伴侣关系。",
          documents_required: [
            "显示签名的最新护照个人资料页或澳大利亚驾驶执照",
            "关于关系的已完成 Commonwealth 法定声明",
          ],
          obligations: [
            "为伴侣和所含家庭成员提供担保",
            "提供经济及住宿协助",
            "情况变化时通知移民部门",
          ],
          withdrawal_note: "签证获批后担保人不能撤回，但在永久伴侣签证作出决定前可能可以撤回担保。",
        },
      },
      sponsor_requirements: {
        summary: "担保人通常是申请人的伴侣，且必须获得批准。",
        who_can_sponsor: [
          "澳大利亚公民",
          "澳大利亚永久居民",
          "符合条件的新西兰公民",
        ],
        sponsor_obligations: [
          "为伴侣和所含家庭成员提供担保",
          "为伴侣和所含家庭成员提供经济协助",
          "为伴侣和所含家庭成员提供住宿协助",
        ],
        sponsor_age: "担保人必须年满 18 岁。如担保人未满 18 岁且与申请人已婚，父母或监护人可能可以担保。",
        sponsorship_duration: "如果申请人在签证获批时位于澳大利亚境内，担保通常在临时伴侣签证获批后 2 年结束；如果获批时位于境外，则通常在下一次进入澳大利亚后 2 年结束。",
        sponsor_documents: [
          "澳大利亚公民身份、澳大利亚永久居留身份或符合条件的新西兰公民身份的证明",
          "护照复印件",
          "出生证明复印件",
          "面部照片",
          "若担保人为澳大利亚永久居民或符合条件的新西兰公民，证明其通常居住在澳大利亚的材料",
          "澳大利亚无犯罪证明",
          "如需，海外无犯罪证明",
          "同意向签证申请人披露相关定罪记录的书面同意书",
        ],
        sponsor_risks: [
          "若不符合品行要求，担保可能不获批准",
          "某些涉及儿童的犯罪会受到担保限制",
          "担保人可在 801 类永久伴侣签证作出决定前撤回担保",
          "820 类签证获批后，担保人不能撤回其担保身份",
        ],
      },
      family_members: {
        can_include_dependent_child: true,
        notes: [
          "受抚养子女可在递交申请时一并包含，或在递交后但临时签证决定前加入。",
          "与申请人一同申请的家庭成员必须在澳大利亚境内。",
          "家庭成员必须满足健康和品行要求。",
          "820 子类获批后，不能再向 820 申请中添加家庭成员。",
          "受抚养子女在被加入永久伴侣签证申请前，可能需要先申请 445 类受抚养子女签证。",
        ],
      },
      domestic_and_family_violence: {
        summary: "来源指出，家庭暴力 provisions 可能适用，且相关信息会被保密。",
        notes: [
          "如果遭遇家庭暴力，申请人仍可能符合临时和永久伴侣签证资格。",
          "来源建议采取在线安全措施，例如更改 ImmiAccount 和电子邮箱密码。",
        ],
      },
      faq_summary: {
        online_application: "申请通常必须通过 ImmiAccount 在线递交。纸质申请仅在有限情形下并经邀请时可用。",
        progress_updates: "在标准处理时间内，移民部门不会提供进度更新；申请人可自行查看 ImmiAccount。",
        urgent_processing: "在具有令人信服且具同情因素的情况下，可能考虑优先处理，但不作保证。",
        health_exams: "体检可在申请后完成，通常有效期为 12 个月。",
        withdrawal: "申请人可通过 ImmiAccount 在线撤回申请；被包含在撤回中的成年申请人必须同意。",
        review_rights: "如拒签决定可复审，通知中会说明如何申请复审。",
        permanent_stage_documents: "若自首次申请以来已满两年且申请人持有 820 子类签证，则可在 ImmiAccount 中完成 Stage 2 Permanent Partner Visa Assessment。",
      },
    },
  },
  "485": {
    key_requirements: [
      "申请时必须在澳大利亚境内",
      "申请前6个月内曾持有500学生签证",
      "完成 CRICOS 注册机构的合格澳洲学历（本科及以上）",
      "多数情况年龄需在50岁以下（标准门槛通常35岁以下，部分可例外）",
      "满足英语要求",
      "全程持有可接受的健康保险",
      "满足健康与品行要求（含无犯罪证明）",
      "不得拖欠政府债务",
      "18岁及以上需签署澳大利亚价值观声明",
    ],
    documents_required: [
      "有效护照",
      "CRICOS 注册机构合格学历完成证明",
      "近6个月内持有500签证证明",
      "达到最低门槛的英语成绩",
      "健康保险证明",
      "澳洲无犯罪证明",
      "如需，海外无犯罪证明",
      "身份证明及如适用姓名变更证明",
      "如被要求，体检结果",
      "如包含家属，家属文件",
      "非英文文件翻译件",
    ],
    application_steps: [
      "确认年龄、学生签证时效、学历和英语要求",
      "收集学历、无犯罪和保险等全部材料",
      "在澳期间通过 ImmiAccount 在线申请",
      "支付签证申请费",
      "如被要求，完成体检",
      "提交无犯罪证明及其他补充材料",
      "按要求补交进一步信息",
      "等待书面结果",
    ],
    visa_conditions: [
      "临时签证，需自行就业",
      "签证不可延期，如需继续停留须重新申请",
      "符合条件可申请485第二阶段相关通道",
      "签证期间需持续维持可接受的健康保险",
      "必须遵守签证条件及澳大利亚法律",
      "签证有效期内可出入境",
      "离境时间不延长签证",
      "情况变化时需通知移民部门",
    ],
    risks: [
      "申请时必须在澳大利亚境内",
      "申请前6个月内曾持有学生签证是关键条件",
      "存在年龄门槛，标准申请人通常需低于35岁",
      "英语成绩需达到最低要求",
      "学历需为 CRICOS 注册机构本科及以上",
      "就业与后续路径取决于个人情况",
      "该签证不保证进入技术移民路径",
      "信息不完整或不准确可能导致延迟或不利结果",
    ],
    english_requirements: {
      summary: "该签证有英语要求，需满足最低门槛，具体考试和分数取决于个人情况及考试日期。",
      approximate_standard: "大致相当于 IELTS 总分 6.5，且按考试类型与日期适用分项门槛。",
      online_tests_note: "居家或全在线英语考试可能不被接受，请以官方最新要求为准。",
      notes: [
        "最低门槛适用；具体分数取决于所选考试及考试时间。",
        "请以澳大利亚内政部官网最新要求为准。",
      ],
    },
    financial_requirements: {
      status: "来源文本未说明收入门槛",
      notes: [
        "该签证流未说明具体的个人收入门槛。",
        "申请人须支付政府申请费。",
        "签证期间须持续维持可接受的健康保险。",
        "额外费用可能包括体检、无犯罪证明及文件翻译费用。",
      ],
    },
    raw_json: {
      eligibility: {
        age_limit: {
          default: 35,
          note: "标准年龄限制为35岁以下。在特定情况下可适用更高年龄上限。",
          exceptions: [
            "在某些情况下，博士（PhD）或研究学位毕业生可在 50 岁前申请",
            "香港或英籍国民（海外）护照持有人可能适用不同的年龄门槛",
            "年龄要求应以当前官方来源为准进行核实",
          ],
        },
        location_requirement: {
          must_be_in_australia: true,
          note: "申请人申请时必须在澳大利亚境内",
        },
        student_visa_requirement: {
          description: "申请前6个月内的任意时间点，需曾持有学生签证（500子类）",
        },
        qualification_requirement: {
          description: "必须已完成 CRICOS 注册澳洲机构的本科及以上学历",
          qualification_levels: [
            "本科学位",
            "本科荣誉学位",
            "研究生证书",
            "研究生文凭",
            "课程型硕士学位",
            "研究型硕士学位",
            "博士学位",
          ],
        },
        police_check_required: true,
        health_insurance_required: true,
      },
      pathway: {
        summary: "澳大利亚签证体系中典型的签证路径可能包括：从学生签证过渡到临时毕业生签证，再根据个人情况进入技术移民路径。",
        stage_1: "学生签证（500）",
        stage_2: "临时毕业生签证（485）——毕业后高等教育工作流",
        stage_3: "技术移民路径（189/190/491）——可能适用于符合条件的申请人",
        progression_note: "以上仅代表典型路径背景，不构成移民建议，亦不保证可进入永久居留路径。",
      },
    },
  },
};

const localizedStructuredData: Record<string, LocaleVisaStructuredMap> = {
  tr: trStructuredData,
  "zh-Hans": zhHansStructuredData,
};

const localizedVisaFieldsData: Record<string, LocaleVisaFieldsMap> = {
  tr: trVisaFields,
  "zh-Hans": zhHansVisaFields,
};

export function localizeVisaFields<T extends Record<string, unknown>>(
  subclass: string,
  locale: string,
  visa: T
): T {
  const localeMap = localizedVisaFieldsData[locale];
  const localized = localeMap?.[subclass];
  if (!localized) return visa;

  return {
    ...visa,
    ...localized,
  } as T;
}

export function localizeVisaStructuredData<T extends Record<string, unknown> | null>(
  subclass: string,
  locale: string,
  structured: T
): T {
  if (!structured || typeof structured !== "object") return structured;

  const localeMap = localizedStructuredData[locale];
  const localized = localeMap?.[subclass];
  if (!localized) return structured;

  const merged = {
    ...(structured as Record<string, unknown>),
    ...localized,
  } as Record<string, unknown>;

  const baseStructured = structured as Record<string, unknown>;
  if (
    baseStructured.english_requirements &&
    typeof baseStructured.english_requirements === "object" &&
    localized.english_requirements &&
    typeof localized.english_requirements === "object"
  ) {
    merged.english_requirements = {
      ...(baseStructured.english_requirements as Record<string, unknown>),
      ...(localized.english_requirements as Record<string, unknown>),
    };

    const baseOnline = (baseStructured.english_requirements as Record<string, unknown>)
      .online_tests_not_accepted;
    const localizedOnline = (localized.english_requirements as Record<string, unknown>)
      .online_tests_not_accepted;

    if (
      baseOnline &&
      typeof baseOnline === "object" &&
      localizedOnline &&
      typeof localizedOnline === "object"
    ) {
      (merged.english_requirements as Record<string, unknown>).online_tests_not_accepted = {
        ...(baseOnline as Record<string, unknown>),
        ...(localizedOnline as Record<string, unknown>),
      };
    }

    const baseFunctional = (baseStructured.english_requirements as Record<string, unknown>)
      .functional_english_for_family_members;
    const localizedFunctional = (localized.english_requirements as Record<string, unknown>)
      .functional_english_for_family_members;

    if (
      baseFunctional &&
      typeof baseFunctional === "object" &&
      localizedFunctional &&
      typeof localizedFunctional === "object"
    ) {
      (merged.english_requirements as Record<string, unknown>).functional_english_for_family_members = {
        ...(baseFunctional as Record<string, unknown>),
        ...(localizedFunctional as Record<string, unknown>),
      };
    }
  }

  // Deep-merge financial_requirements
  if (
    baseStructured.financial_requirements &&
    typeof baseStructured.financial_requirements === "object" &&
    localized.financial_requirements &&
    typeof localized.financial_requirements === "object"
  ) {
    merged.financial_requirements = {
      ...(baseStructured.financial_requirements as Record<string, unknown>),
      ...(localized.financial_requirements as Record<string, unknown>),
    };
  }

  // Deep-merge raw_json (one level - merge individual section keys)
  if (
    baseStructured.raw_json &&
    typeof baseStructured.raw_json === "object" &&
    localized.raw_json &&
    typeof localized.raw_json === "object"
  ) {
    merged.raw_json = {
      ...(baseStructured.raw_json as Record<string, unknown>),
      ...(localized.raw_json as Record<string, unknown>),
    };
  }

  return merged as T;
}
