type LocalizedStructuredFields = {
  key_requirements?: string[];
  documents_required?: string[];
  application_steps?: string[];
  visa_conditions?: string[];
  risks?: string[];
};

type LocaleVisaStructuredMap = Record<string, LocalizedStructuredFields>;

const trStructuredData: LocaleVisaStructuredMap = {
  "500": {
    key_requirements: [
      "Avustralya içinden veya dışından çevrimiçi başvurun",
      "Tam zamanlı bir eğitime kayıtlı olun ve geçerli bir Kayıt Onayı (CoE) bulundurun",
      "Yurt Dışı Öğrenci Sağlık Sigortasını (OSHC) sürdürün",
      "En az 6 yaşında olun",
      "18 yaşından küçükseniz uygun refah düzenlemelerine sahip olun",
      "Avustralya içinden başvuruyorsanız uygun bir esas vizeye sahip olun",
      "İngilizce dil şartlarını karşılayın veya muafiyet kapsamında olun",
      "Kalış süresi için yeterli mali kapasiteyi gösterin",
      "Gerçek bir öğrenci olduğunuzu gösterin",
      "Sağlık ve karakter şartlarını karşılayın",
      "18 yaş ve üzerindeyseniz Avustralya Değerler Beyanını imzalayın",
      "Avustralya Hükümetine olan borçlarınızı ödemiş olun",
      "Uygunluğu olumsuz etkileyen bir vize geçmişine sahip olmayın",
    ],
    documents_required: [
      "Geçerli pasaport",
      "Kayıt Onayı (CoE)",
      "Gerekliyse İngilizce yeterlilik kanıtı",
      "Gerekliyse mali yeterlilik kanıtı",
      "Yurt Dışı Öğrenci Sağlık Sigortası (OSHC)",
      "Kimlik belgeleri",
      "Gerekliyse sağlık muayenesi sonuçları",
      "Gerekliyse polis belgeleri",
      "18 yaş altı için refah ve ebeveyn onay belgeleri",
      "Varsa eş ve bakmakla yükümlü olunan kişilere ait belgeler",
      "İngilizce olmayan belgeler için onaylı çeviriler",
    ],
    application_steps: [
      "Başvuru öncesi hazırlığınızı tamamlayın",
      "Belge Kontrol Aracı ile gerekli belgeleri toplayın",
      "ImmiAccount üzerinden çevrimiçi başvurun",
      "Belgeleri yükleyin ve vize başvuru ücretini ödeyin veya muafiyet kanıtı sunun",
      "Ek bilgi taleplerine yanıt verin",
      "İstenirse biyometri veya sağlık muayenesini tamamlayın",
      "Yazılı vize sonucunu bekleyin",
    ],
    visa_conditions: [
      "Uygun bir eğitim programındaki kaydınızı sürdürün",
      "Çalışma kısıtlarına uyun",
      "Yeterli sağlık sigortasını sürdürün",
      "Avustralya yasalarına uyun",
      "Vize geçerliyken Avustralya'ya giriş çıkış yapabilirsiniz",
      "Bu vize uzatılamaz; daha uzun kalmak için yeni vizeye başvurulmalıdır",
      "Koşullarınız değişirse Bakanlığı bilgilendirin",
    ],
    risks: [
      "Başvuru eksikse işlem gecikebilir veya reddedilebilir",
      "CoE eksik ya da geçersizse başvuru geçersiz sayılabilir",
      "Yanlış veya yanıltıcı bilgi ret ve gelecekte vize sonuçlarına yol açabilir",
      "Yetersiz mali kanıt ret ile sonuçlanabilir",
      "OSHC'nin sürdürülmemesi uyum sorunlarına yol açabilir",
      "Önceki ret veya iptaller uygunluğu etkileyebilir",
      "Gerçek Öğrenci şartının karşılanmaması ret ile sonuçlanabilir",
    ],
  },
  "189": {
    key_requirements: [
      "İlgili nitelikli meslek listesinde bir mesleğe sahip olun",
      "Uygun bir beceri değerlendirmesine sahip olun",
      "Başvuru daveti alın",
      "En az 65 puan alın",
      "Davet tarihinde 45 yaşın altında olun",
      "Yeterli düzeyde İngilizceye sahip olun",
      "Sağlık ve karakter şartlarını karşılayın",
    ],
    documents_required: [
      "Niyet Beyanı (EOI)",
      "Başvuru daveti",
      "Beceri değerlendirmesi",
      "İngilizce sınav sonuçları",
      "Kimlik belgeleri",
      "Puan beyanlarını destekleyen kanıtlar",
    ],
    application_steps: [
      "SkillSelect üzerinden EOI gönderin",
      "Daveti bekleyin",
      "Belgeleri toplayın",
      "ImmiAccount üzerinden başvurun",
      "Belgeleri yükleyin",
      "Kararı bekleyin",
    ],
    visa_conditions: [
      "Kalıcı oturum",
      "Avustralya'nın her yerinde yaşama ve çalışma hakkı",
      "5 yıl seyahat hakkı",
      "Vatandaşlığa uygunluk imkanı",
    ],
    risks: [
      "Davet yoksa başvuru yapılamaz",
      "Düşük puan davet alınamamasına neden olabilir",
      "Yanlış beyanlar ret ile sonuçlanabilir",
    ],
  },
  "190": {
    key_requirements: [
      "İlgili nitelikli meslek listesinde bir mesleğe sahip olun",
      "Meslek için uygun bir beceri değerlendirmesine sahip olun",
      "SkillSelect üzerinden Niyet Beyanı (EOI) gönderin",
      "Bir Avustralya eyaleti veya bölgesi tarafından aday gösterilin",
      "Bu vize için başvuru daveti alın",
      "En az 65 puan alın",
      "Başvuru daveti aldığınızda 45 yaşın altında olun",
      "Davet anında en az Yeterli İngilizce düzeyine sahip olun",
      "Sağlık ve karakter şartlarını karşılayın",
      "Avustralya Hükümetine olan borçlarınızı ödeyin",
      "18 yaş ve üzerindeyseniz Avustralya Değerler Beyanını imzalayın",
    ],
    documents_required: [
      "SkillSelect üzerinden Niyet Beyanı (EOI)",
      "Başvuru daveti",
      "Eyalet veya bölge adaylığı",
      "Uygun beceri değerlendirmesi",
      "Kimlik belgeleri",
      "Yeterli İngilizce kanıtı",
      "Puan beyanlarını destekleyen kanıtlar",
      "Varsa ilişki belgeleri",
      "Gerekliyse karakter belgeleri ve polis kayıtları",
      "İstenirse sağlık muayenesi sonuçları",
      "Dahil edilen aile üyelerine ait belgeler",
      "İngilizce olmayan belgeler için çeviriler",
    ],
    application_steps: [
      "SkillSelect üzerinden Niyet Beyanı (EOI) gönderin",
      "Nitelikli Aday Gösterilmiş 190 alt sınıf vizesini seçin",
      "Eyalet veya bölge adaylığı için bekleyin",
      "Aday gösterilirseniz başvuru daveti alın",
      "Davet tarihinden itibaren 60 gün içinde ImmiAccount üzerinden çevrimiçi başvurun",
      "Belgeleri yükleyin ve başvuru ücretini ödeyin",
      "İstenirse ek bilgi taleplerine yanıt verin",
      "İstenirse sağlık muayenesi veya biyometriyi tamamlayın",
      "Yazılı vize sonucunu bekleyin",
    ],
    visa_conditions: [
      "Kalıcı vize",
      "Avustralya'da yaşama, çalışma ve eğitim hakkı",
      "Vize veriliş tarihinden itibaren 5 yıl giriş çıkış hakkı",
      "5 yıl sonra yeniden giriş için Resident Return vizesi gerekebilir",
      "Uygun akrabalar için sponsorluk imkanı",
      "Avustralya vatandaşlığına uygunluk imkanı",
      "Avustralya yasalarına uyma zorunluluğu",
    ],
    risks: [
      "Eyalet veya bölge adaylığı yoksa başvuru daveti alınamaz",
      "Adaylık başvuru sonrası geri çekilirse başvuru geçersiz olur",
      "65 puanın altındaki skor davet alınamamasına yol açar",
      "EOI puanlarına göre davet puanı 65'in üzerinde olabilir",
      "Davet sonrası puan beyanları kanıtlanmalıdır",
      "Davet tarihinde yaş 45'in altında olmalıdır",
      "Beceri değerlendirmesi uygun ve geçerli olmalıdır",
      "Meslek ilgili nitelikli meslek listesinde olmalıdır",
      "Eyalet ve bölge kurumlarının kendi adaylık kriterleri vardır",
      "Eksik veya hatalı bilgi başvuruyu geciktirebilir ya da olumsuz etkileyebilir",
    ],
  },
};

const zhHansStructuredData: LocaleVisaStructuredMap = {
  "500": {
    key_requirements: [
      "在澳大利亚境内或境外在线申请",
      "注册全日制课程并持有有效的入学确认函（CoE）",
      "持续持有海外学生健康保险（OSHC）",
      "年龄至少为6岁",
      "未满18岁需具备合规的监护安排",
      "在澳大利亚境内申请时需持有符合条件的实质性签证",
      "满足英语语言要求或符合豁免条件",
      "具备覆盖在澳期间的充足经济能力",
      "符合真实学生（Genuine Student）要求",
      "满足健康与品行要求",
      "18岁及以上需签署澳大利亚价值观声明",
      "已偿还欠澳大利亚政府的相关债务",
      "无影响资格的不良签证历史",
    ],
    documents_required: [
      "有效护照",
      "入学确认函（CoE）",
      "如需提供英语能力证明",
      "如需提供资金能力证明",
      "海外学生健康保险（OSHC）",
      "身份证明文件",
      "如需提供体检结果",
      "如需提供无犯罪证明",
      "未满18岁需提供监护及父母同意文件",
      "如适用，配偶与受抚养人相关文件",
      "非英文文件的认证翻译件",
    ],
    application_steps: [
      "提交申请前完成准备工作",
      "使用文件清单工具准备所需材料",
      "通过 ImmiAccount 在线提交申请",
      "上传材料并支付签证申请费，或提供费用豁免证明",
      "按要求补充提交额外信息",
      "如被要求，完成生物信息采集或体检",
      "等待书面签证结果",
    ],
    visa_conditions: [
      "持续就读于符合条件的课程",
      "遵守工作时长限制",
      "持续维持充分的健康保险",
      "遵守澳大利亚法律",
      "签证有效期内可自由出入澳大利亚",
      "该签证不可延期；需延长停留应重新申请新签证",
      "个人情况变化时需通知移民部门",
    ],
    risks: [
      "材料不完整可能导致审理延迟或被拒",
      "缺少或无效 CoE 可能导致申请无效",
      "错误或虚假信息可能导致拒签并影响后续签证",
      "资金证明不足可能导致拒签",
      "未持续持有 OSHC 可能引发合规问题",
      "既往拒签或签证取消记录可能影响资格",
      "未满足真实学生要求可能导致拒签",
    ],
  },
  "189": {
    key_requirements: [
      "职业需在相关技术职业清单上",
      "持有合格的职业评估",
      "获得申请邀请",
      "EOI 评分至少达到65分",
      "获邀时年龄低于45岁",
      "具备合格英语能力",
      "满足健康与品行要求",
    ],
    documents_required: [
      "意向申请（EOI）",
      "申请邀请函",
      "职业评估",
      "英语考试成绩",
      "身份证明文件",
      "支持打分主张的证明材料",
    ],
    application_steps: [
      "在 SkillSelect 提交 EOI",
      "等待获邀",
      "准备申请材料",
      "通过 ImmiAccount 提交申请",
      "上传材料",
      "等待签证结果",
    ],
    visa_conditions: [
      "永久居留签证",
      "可在澳大利亚任何地区生活与工作",
      "享有5年出入境权限",
      "可符合申请入籍条件",
    ],
    risks: [
      "未获邀请则无法申请",
      "分数偏低可能无法获邀",
      "不实主张可能导致拒签",
    ],
  },
  "190": {
    key_requirements: [
      "职业需在相关技术职业清单上",
      "持有与职业匹配的合格职业评估",
      "通过 SkillSelect 提交 EOI",
      "获得澳大利亚州或领地政府提名",
      "获得本签证申请邀请",
      "EOI 评分至少达到65分",
      "获邀时年龄低于45岁",
      "获邀时至少达到合格英语水平",
      "满足健康与品行要求",
      "已偿还欠澳大利亚政府的债务",
      "18岁及以上需签署澳大利亚价值观声明",
    ],
    documents_required: [
      "通过 SkillSelect 提交的 EOI",
      "申请邀请函",
      "州或领地提名证明",
      "合格职业评估",
      "身份证明文件",
      "合格英语证明",
      "支持打分主张的证明材料",
      "如适用，关系证明文件",
      "如需提供品行文件与无犯罪证明",
      "如被要求，体检结果",
      "如包含家属，需提供家属相关文件",
      "非英文文件的翻译件",
    ],
    application_steps: [
      "通过 SkillSelect 提交 EOI",
      "选择技术提名 190 子类签证",
      "等待州或领地政府可能发出的提名",
      "获提名后接收申请邀请",
      "在获邀后60个自然日内通过 ImmiAccount 在线申请",
      "上传材料并支付申请费",
      "如被要求，补充提交额外信息",
      "如被要求，完成体检或生物信息采集",
      "等待书面签证结果",
    ],
    visa_conditions: [
      "永久签证",
      "可在澳大利亚生活、工作和学习",
      "自签证获批日起5年内可多次出入境",
      "5年后再次入境可能需申请居民返程签证",
      "可为符合条件的亲属提供担保",
      "可符合申请澳大利亚国籍条件",
      "必须遵守澳大利亚法律",
    ],
    risks: [
      "未获州或领地提名将无法获得该签证邀请",
      "申请后若提名被撤回，申请将变为无效",
      "低于65分将无法获邀",
      "根据 EOI 声明，实际获邀分数可能高于65分",
      "获邀后必须证明打分主张",
      "获邀时年龄必须低于45岁",
      "职业评估必须合格且在有效期内",
      "职业必须在相关技术职业清单上",
      "各州和领地有各自的提名标准",
      "信息不完整或不准确可能导致审理延迟或不利结果",
    ],
  },
};

const localizedStructuredData: Record<string, LocaleVisaStructuredMap> = {
  tr: trStructuredData,
  "zh-Hans": zhHansStructuredData,
};

export function localizeVisaStructuredData(
  subclass: string,
  locale: string,
  structured: unknown
) {
  if (!structured || typeof structured !== "object") return structured;

  const localeMap = localizedStructuredData[locale];
  const localized = localeMap?.[subclass];
  if (!localized) return structured;

  return {
    ...(structured as Record<string, unknown>),
    ...localized,
  };
}
