type LocalizedStructuredFields = {
  key_requirements?: string[];
  documents_required?: string[];
  application_steps?: string[];
  visa_conditions?: string[];
  risks?: string[];
};

type LocalizedVisaFields = {
  visa_name?: string;
  category?: string;
  purpose?: string;
  stay_period?: string;
  cost?: string;
  work_rights?: string;
};

type LocaleVisaStructuredMap = Record<string, LocalizedStructuredFields>;
type LocaleVisaFieldsMap = Record<string, LocalizedVisaFields>;

const trVisaFields: LocaleVisaFieldsMap = {
  "500": {
    visa_name: "Öğrenci vizesi",
    category: "Eğitim",
    purpose: "Avustralya'da uygun bir eğitim programına katılmak",
    stay_period: "6 yıla kadar ve kayıt durumuna bağlı",
    cost: "Muafiyet yoksa AUD 2.000'den başlar",
    work_rights:
      "Eğitim dönemi boyunca iki haftada 48 saate kadar çalışma; araştırma veya lisansüstü öğrenciler için farklı kurallar uygulanabilir",
  },
  "482": {
    visa_name: "Talep Gören Beceriler vizesi",
    category: "Çalışma",
    purpose:
      "Core Skills Occupation List'te yer alan bir meslek için onaylı işveren sponsoruyla Avustralya'da geçici çalışma",
    stay_period: "4 yıla kadar. Hong Kong pasaport sahipleri 5 yıla kadar kalabilir.",
    cost: "Asıl başvuru sahibi ve 18+ bağımlılar için AUD 3.210'dan başlar. 18 yaş altı bağımlılar için AUD 805.",
    work_rights:
      "Atanan meslekte onaylı sponsor için çalışma. Bazı durumlarda sponsorun ilişkili kuruluşunda çalışma mümkündür.",
  },
  "189": {
    visa_name: "Nitelikli Bağımsız vizesi",
    category: "Kalıcı Nitelikli Göç",
    purpose: "Davetli nitelikli çalışan olarak Avustralya'nın her yerinde kalıcı yaşamak ve çalışmak",
    stay_period: "Kalıcı",
    cost: "Asıl başvuru sahibi için AUD 4.910'dan başlar",
    work_rights: "Avustralya'nın her yerinde çalışma ve eğitim",
  },
  "190": {
    visa_name: "Nitelikli Aday Gösterilmiş vizesi",
    category: "Kalıcı Nitelikli Göç",
    purpose:
      "Avustralya eyalet veya bölge yönetimi tarafından aday gösterilen nitelikli çalışan olarak kalıcı yaşamak ve çalışmak",
    stay_period: "Kalıcı",
    cost: "Asıl başvuru sahibi için AUD 4.910'dan başlar",
    work_rights: "Avustralya'nın her yerinde çalışma ve eğitim",
  },
  "491": {
    visa_name: "Nitelikli Bölgesel Çalışma (Geçici) vizesi",
    category: "Bölgesel Nitelikli Göç",
    purpose:
      "Nitelikli çalışan olarak Avustralya'nın belirlenmiş bölgesel alanlarında yaşamak, çalışmak ve eğitim görmek",
    stay_period: "5 yıl",
    cost: "Asıl başvuru sahibi için AUD 4.910'dan başlar. Aile üyeleri ve ikinci taksit için ek ücretler olabilir.",
    work_rights: "Avustralya'nın belirlenmiş bölgesel alanlarında yaşama, çalışma ve eğitim.",
  },
  "820_801": {
    visa_name: "Partner vizesi (ülke içi)",
    category: "Aile Göçü",
    purpose:
      "Avustralya vatandaşı, daimi oturum sahibi veya uygun Yeni Zelanda vatandaşı partnerin eşine/fiili partnerine Avustralya'da geçici yaşama ve kalıcı aşamaya ilerleme imkanı sağlar",
    stay_period: "Kalıcı Partner vizesi 801 sonuçlanana veya geri çekilene kadar geçici",
    cost:
      "Çoğu başvuru sahibi için AUD 9.365'ten başlar. Subclass 300 sahipleri için AUD 1.560'tan, bazı eski subclass 300 sahipleri için AUD 1.980'den başlar.",
    work_rights: "Kalıcı Partner vizesi değerlendirilirken Avustralya'da yaşama, çalışma ve eğitim.",
  },
  "485": {
    visa_name: "Geçici Mezun vizesi",
    category: "Mezuniyet Sonrası Çalışma",
    purpose:
      "Uygun yakın dönem mezunlara Avustralya'daki eğitimlerini tamamladıktan sonra geçici yaşama, çalışma ve eğitim imkanı sağlar",
    stay_period:
      "Genellikle niteliğe göre 2-3 yıl; Hong Kong ve British National Overseas pasaport sahipleri 5 yıl kalabilir",
    cost: "AUD 4.600'dan başlar",
    work_rights:
      "Avustralya'da yaşama, çalışma ve eğitim. Vize geçerliyken giriş-çıkış yapma ve uygun aile üyelerini dahil etme.",
  },
};

const zhHansVisaFields: LocaleVisaFieldsMap = {
  "500": {
    visa_name: "学生签证",
    category: "学习",
    purpose: "在澳大利亚参加符合条件的课程学习",
    stay_period: "最长6年，并与注册期限一致",
    cost: "如无豁免，费用自 AUD 2,000 起",
    work_rights: "课程期间每两周最多工作48小时；研究型或研究生可能适用不同规则",
  },
  "482": {
    visa_name: "紧缺技能签证",
    category: "工作",
    purpose: "在获批雇主担保下，以核心技能职业清单中的职业在澳大利亚临时工作",
    stay_period: "最长4年。香港护照持有人最长可达5年。",
    cost: "主申请人及18岁以上附属申请人每人 AUD 3,210 起；18岁以下每人 AUD 805。",
    work_rights: "在提名职业中为获批担保雇主工作；部分情况下可为关联实体工作。",
  },
  "189": {
    visa_name: "独立技术移民签证",
    category: "永久技术移民",
    purpose: "作为受邀技术人员在澳大利亚任何地区永久生活和工作",
    stay_period: "永久",
    cost: "主申请人 AUD 4,910 起",
    work_rights: "可在澳大利亚任何地区工作和学习",
  },
  "190": {
    visa_name: "州担保技术移民签证",
    category: "永久技术移民",
    purpose: "作为州或领地提名的技术人员在澳大利亚永久生活和工作",
    stay_period: "永久",
    cost: "主申请人 AUD 4,910 起",
    work_rights: "可在澳大利亚任何地区工作和学习",
  },
  "491": {
    visa_name: "偏远地区技术工作（临时）签证",
    category: "偏远地区技术移民",
    purpose: "作为技术人员在澳大利亚指定偏远地区生活、工作和学习",
    stay_period: "5年",
    cost: "主申请人 AUD 4,910 起；家庭成员及第二笔费用可能另计。",
    work_rights: "可在澳大利亚指定偏远地区生活、工作和学习。",
  },
  "820_801": {
    visa_name: "伴侣签证（境内）",
    category: "家庭移民",
    purpose:
      "允许澳大利亚公民、永久居民或符合条件的新西兰公民的配偶/事实伴侣在澳临时居留，并过渡到永久居留",
    stay_period: "临时，直至永久伴侣签证 801 完成审理或撤回",
    cost:
      "多数申请人 AUD 9,365 起。300 子类持有人 AUD 1,560 起，部分原 300 子类持有人 AUD 1,980 起。",
    work_rights: "在永久伴侣签证审理期间可在澳生活、工作和学习。",
  },
  "485": {
    visa_name: "临时毕业生签证",
    category: "毕业后工作",
    purpose: "允许符合条件的应届毕业生在完成澳洲学习后在澳临时生活、工作和学习",
    stay_period: "通常2至3年（取决于学历）；香港及英籍国民（海外）护照持有人可达5年",
    cost: "AUD 4,600 起",
    work_rights: "可在澳生活、工作和学习；签证有效期内可出入境，并可包含符合条件的家庭成员。",
  },
};

const trStructuredData: LocaleVisaStructuredMap = {
  "500": {
    key_requirements: [
      "Avustralya içinden veya dışından çevrimiçi başvurun",
      "Tam zamanlı bir eğitime kayıtlı olun ve geçerli bir Kayıt Onayı (CoE) bulundurun",
      "Yurt Dışı Öğrenci Sağlık Sigortasını (OSHC) sürdürün",
      "En az 6 yaşında olun",
      "18 yaşından küçükseniz uygun refah düzenlemelerine sahip olun",
      "Avustralya içinden başvuruyorsanız uygun bir esas vizeye sahip olun",
      "İngilizce dil şartlarını karşılayın veya muafiyet kapsamında olun",
      "Kalış süresi için yeterli mali kapasiteyi gösterin",
      "Gerçek bir öğrenci olduğunuzu gösterin",
      "Sağlık ve karakter şartlarını karşılayın",
      "18 yaş ve üzerindeyseniz Avustralya Değerler Beyanını imzalayın",
      "Avustralya Hükümetine olan borçlarınızı ödemiş olun",
      "Uygunluğu olumsuz etkileyen bir vize geçmişine sahip olmayın",
    ],
    documents_required: [
      "Geçerli pasaport",
      "Kayıt Onayı (CoE)",
      "Gerekliyse İngilizce yeterlilik kanıtı",
      "Gerekliyse mali yeterlilik kanıtı",
      "Yurt Dışı Öğrenci Sağlık Sigortası (OSHC)",
      "Kimlik belgeleri",
      "Gerekliyse sağlık muayenesi sonuçları",
      "Gerekliyse polis belgeleri",
      "18 yaş altı için refah ve ebeveyn onay belgeleri",
      "Varsa eş ve bakmakla yükümlü olunan kişilere ait belgeler",
      "İngilizce olmayan belgeler için onaylı çeviriler",
    ],
    application_steps: [
      "Başvuru öncesi hazırlığınızı tamamlayın",
      "Belge Kontrol Aracı ile gerekli belgeleri toplayın",
      "ImmiAccount üzerinden çevrimiçi başvurun",
      "Belgeleri yükleyin ve vize başvuru ücretini ödeyin veya muafiyet kanıtı sunun",
      "Ek bilgi taleplerine yanıt verin",
      "İstenirse biyometri veya sağlık muayenesini tamamlayın",
      "Yazılı vize sonucunu bekleyin",
    ],
    visa_conditions: [
      "Uygun bir eğitim programındaki kaydınızı sürdürün",
      "Çalışma kısıtlarına uyun",
      "Yeterli sağlık sigortasını sürdürün",
      "Avustralya yasalarına uyun",
      "Vize geçerliyken Avustralya'ya giriş çıkış yapabilirsiniz",
      "Bu vize uzatılamaz; daha uzun kalmak için yeni vizeye başvurulmalıdır",
      "Koşullarınız değişirse Bakanlığı bilgilendirin",
    ],
    risks: [
      "Başvuru eksikse işlem gecikebilir veya reddedilebilir",
      "CoE eksik ya da geçersizse başvuru geçersiz sayılabilir",
      "Yanlış veya yanıltıcı bilgi ret ve gelecekte vize sonuçlarına yol açabilir",
      "Yetersiz mali kanıt ret ile sonuçlanabilir",
      "OSHC'nin sürdürülmemesi uyum sorunlarına yol açabilir",
      "Önceki ret veya iptaller uygunluğu etkileyebilir",
      "Gerçek Öğrenci şartının karşılanmaması ret ile sonuçlanabilir",
    ],
  },
  "189": {
    key_requirements: [
      "İlgili nitelikli meslek listesinde bir mesleğe sahip olun",
      "Uygun bir beceri değerlendirmesine sahip olun",
      "Başvuru daveti alın",
      "En az 65 puan alın",
      "Davet tarihinde 45 yaşın altında olun",
      "Yeterli düzeyde İngilizceye sahip olun",
      "Sağlık ve karakter şartlarını karşılayın",
    ],
    documents_required: [
      "Niyet Beyanı (EOI)",
      "Başvuru daveti",
      "Beceri değerlendirmesi",
      "İngilizce sınav sonuçları",
      "Kimlik belgeleri",
      "Puan beyanlarını destekleyen kanıtlar",
    ],
    application_steps: [
      "SkillSelect üzerinden EOI gönderin",
      "Daveti bekleyin",
      "Belgeleri toplayın",
      "ImmiAccount üzerinden başvurun",
      "Belgeleri yükleyin",
      "Kararı bekleyin",
    ],
    visa_conditions: [
      "Kalıcı oturum",
      "Avustralya'nın her yerinde yaşama ve çalışma hakkı",
      "5 yıl seyahat hakkı",
      "Vatandaşlığa uygunluk imkanı",
    ],
    risks: [
      "Davet yoksa başvuru yapılamaz",
      "Düşük puan davet alınamamasına neden olabilir",
      "Yanlış beyanlar ret ile sonuçlanabilir",
    ],
  },
  "190": {
    key_requirements: [
      "İlgili nitelikli meslek listesinde bir mesleğe sahip olun",
      "Meslek için uygun bir beceri değerlendirmesine sahip olun",
      "SkillSelect üzerinden Niyet Beyanı (EOI) gönderin",
      "Bir Avustralya eyaleti veya bölgesi tarafından aday gösterilin",
      "Bu vize için başvuru daveti alın",
      "En az 65 puan alın",
      "Başvuru daveti aldığınızda 45 yaşın altında olun",
      "Davet anında en az Yeterli İngilizce düzeyine sahip olun",
      "Sağlık ve karakter şartlarını karşılayın",
      "Avustralya Hükümetine olan borçlarınızı ödeyin",
      "18 yaş ve üzerindeyseniz Avustralya Değerler Beyanını imzalayın",
    ],
    documents_required: [
      "SkillSelect üzerinden Niyet Beyanı (EOI)",
      "Başvuru daveti",
      "Eyalet veya bölge adaylığı",
      "Uygun beceri değerlendirmesi",
      "Kimlik belgeleri",
      "Yeterli İngilizce kanıtı",
      "Puan beyanlarını destekleyen kanıtlar",
      "Varsa ilişki belgeleri",
      "Gerekliyse karakter belgeleri ve polis kayıtları",
      "İstenirse sağlık muayenesi sonuçları",
      "Dahil edilen aile üyelerine ait belgeler",
      "İngilizce olmayan belgeler için çeviriler",
    ],
    application_steps: [
      "SkillSelect üzerinden Niyet Beyanı (EOI) gönderin",
      "Nitelikli Aday Gösterilmiş 190 alt sınıf vizesini seçin",
      "Eyalet veya bölge adaylığı için bekleyin",
      "Aday gösterilirseniz başvuru daveti alın",
      "Davet tarihinden itibaren 60 gün içinde ImmiAccount üzerinden çevrimiçi başvurun",
      "Belgeleri yükleyin ve başvuru ücretini ödeyin",
      "İstenirse ek bilgi taleplerine yanıt verin",
      "İstenirse sağlık muayenesi veya biyometriyi tamamlayın",
      "Yazılı vize sonucunu bekleyin",
    ],
    visa_conditions: [
      "Kalıcı vize",
      "Avustralya'da yaşama, çalışma ve eğitim hakkı",
      "Vize veriliş tarihinden itibaren 5 yıl giriş çıkış hakkı",
      "5 yıl sonra yeniden giriş için Resident Return vizesi gerekebilir",
      "Uygun akrabalar için sponsorluk imkanı",
      "Avustralya vatandaşlığına uygunluk imkanı",
      "Avustralya yasalarına uyma zorunluluğu",
    ],
    risks: [
      "Eyalet veya bölge adaylığı yoksa başvuru daveti alınamaz",
      "Adaylık başvuru sonrası geri çekilirse başvuru geçersiz olur",
      "65 puanın altındaki skor davet alınamamasına yol açar",
      "EOI puanlarına göre davet puanı 65'in üzerinde olabilir",
      "Davet sonrası puan beyanları kanıtlanmalıdır",
      "Davet tarihinde yaş 45'in altında olmalıdır",
      "Beceri değerlendirmesi uygun ve geçerli olmalıdır",
      "Meslek ilgili nitelikli meslek listesinde olmalıdır",
      "Eyalet ve bölge kurumlarının kendi adaylık kriterleri vardır",
      "Eksik veya hatalı bilgi başvuruyu geciktirebilir ya da olumsuz etkileyebilir",
    ],
  },
  "482": {
    key_requirements: [
      "Onaylı bir sponsor tarafından aday gösterilmek",
      "Core Skills Occupation List'teki bir meslek için aday gösterilmek",
      "Yıllık Piyasa Ücret Oranı ve Core Skills Income Threshold altında olmayacak ücret almak",
      "Aday olunan meslekte veya ilgili alanda en az 1 yıl deneyime sahip olmak",
      "Gerekliyse uygun beceri değerlendirmesine sahip olmak",
      "Muaf durumlar dışında yalnızca sponsor veya ilişkili kuruluş için çalışmak",
      "Muaf değilse asgari İngilizce yeterliliğini sağlamak",
      "Avustralya içinden başvuruluyorsa uygun vizeye sahip olmak",
      "Avustralya içinden başvuruda önceki vize koşullarına uymuş olmak",
      "Yeterli sağlık sigortasını sürdürmek",
      "Sağlık ve karakter şartlarını karşılamak",
      "Vize sponsorluğu için ödeme geçmişine sahip olmamak",
      "Uygunluğu etkileyen ret/iptal geçmişine sahip olmamak",
      "Avustralya Hükümetine borcu olmamak",
      "18 yaş ve üzerindekiler için Avustralya Değerler Beyanı'nı imzalamak",
    ],
    documents_required: [
      "Geçerli pasaport",
      "İşveren adaylık Transaction Reference Number",
      "Kimlik belgeleri",
      "Varsa isim değişikliği kanıtı",
      "Zorunluysa beceri değerlendirme referans numarası",
      "Beceri, yeterlilik ve iş geçmişi kanıtı",
      "İlgili diploma/sertifika belgeleri",
      "Gerekliyse kayıt veya lisans belgeleri",
      "Özgeçmiş",
      "İş referansları",
      "İngilizce yeterlilik belgeleri",
      "Yeterli sağlık sigortası kanıtı",
      "Gerekliyse sağlık muayenesi sonuçları",
      "Gerekliyse Avustralya polis belgesi",
      "Gerekliyse yurt dışı polis belgeleri",
      "Varsa askerlik kayıtları",
      "Varsa partner belgeleri",
      "Varsa bağımlı belgeleri",
      "18 yaş altı bağımlılar için ebeveyn sorumluluk belgeleri (varsa)",
      "İngilizce olmayan belgeler için çeviriler",
    ],
    application_steps: [
      "Başvuru öncesi adaylık, pasaport, gerekliyse beceri değerlendirmesi ve İngilizce sınavını hazırlayın",
      "Kimlik, beceri, meslek, İngilizce, sağlık sigortası, karakter ve aile belgelerini toplayın",
      "ImmiAccount üzerinden çevrimiçi başvurun",
      "Belgeleri yükleyin ve başvuru ücretini ödeyin",
      "İstenirse ek bilgi taleplerine yanıt verin",
      "İstenirse sağlık muayenesi veya biyometriyi tamamlayın",
      "Başvuru işlenirken yasal statünüzü koruyun",
      "Yazılı vize sonucunu bekleyin",
    ],
    visa_conditions: [
      "Aday gösterilen meslekte çalışmak",
      "Genellikle yalnızca sponsor işveren için çalışmak",
      "Avustralyalı sponsor varsa sponsor veya ilişkili kuruluş için çalışabilmek",
      "Avustralya'ya girişten itibaren veya ülke içi onayda verilişten itibaren 90 gün içinde işe başlamak",
      "Yeterli sağlık sigortasını sürdürmek",
      "Avustralya yasalarına uymak",
      "Vize geçerliyken Avustralya'ya giriş çıkış yapabilmek",
      "Avustralya dışında geçirilen süre vizeyi uzatmaz",
      "İletişim, işveren, çalışma durumu, ilişki durumu veya çocuk doğumu gibi değişiklikleri bildirmek",
    ],
    risks: [
      "İşveren adaylığı onaylanmadan vize verilemez",
      "Belgeler eksikse başvuru gecikebilir veya reddedilebilir",
      "Zorunlu beceri değerlendirmesi başvuru öncesi başlatılmamışsa başvuru geçersiz olabilir",
      "Yanlış veya yanıltıcı bilgi ret ve gelecekte vize sonuçlarına yol açabilir",
      "İngilizce şartlarının karşılanmaması uygunluğu etkileyebilir",
      "Sağlık sigortasının sürdürülmemesi vize koşulu ihlaline yol açabilir",
      "Önceki ret veya iptaller uygunluğu etkileyebilir",
      "Son 3 yılda sponsorluk için ödeme yapılması uygunluğu etkileyebilir",
      "İş sona ererse yeni işveren bulunması veya Avustralya'dan ayrılma düzenlemesi gerekebilir",
    ],
  },
  "491": {
    key_requirements: [
      "Eyalet/bölge adaylığı almak veya uygun bir akraba tarafından sponsor edilmek",
      "İlgili nitelikli meslek listesinde bir mesleğe sahip olmak",
      "Meslek için uygun beceri değerlendirmesine sahip olmak",
      "Başvuru daveti almak",
      "Puan testini karşılamak",
      "En az 65 puan almak",
      "Davet tarihinde 45 yaşın altında olmak",
      "Davet anında en az Yeterli İngilizceye sahip olmak",
      "Onaylanırsa belirlenmiş bölgesel alanda yaşamak, çalışmak ve eğitim görmek",
      "Sağlık ve karakter şartlarını karşılamak",
      "Avustralya Hükümetine borçları ödemiş olmak",
      "18 yaş ve üzerindekiler için Avustralya Değerler Beyanı'nı imzalamak",
    ],
    documents_required: [
      "SkillSelect üzerinden EOI",
      "Başvuru daveti",
      "Uygun beceri değerlendirmesi",
      "Kimlik belgeleri",
      "Yeterli İngilizce kanıtı",
      "Puan beyanlarını destekleyen kanıtlar",
      "Gerekliyse karakter belgeleri ve polis kayıtları",
      "İstenirse sağlık muayenesi sonuçları",
      "Varsa partner belgeleri",
      "Varsa bağımlı çocuk belgeleri",
      "Akraba sponsorluğu varsa sponsor beyanı",
      "Sponsorun uygun akraba olduğuna dair kanıt",
      "Sponsorun 18+ olduğuna dair kanıt",
      "Sponsorun Avustralya vatandaşı/daimi oturumlu/uygun Yeni Zelanda vatandaşı olduğuna dair kanıt",
      "Sponsorun belirlenmiş bölgede ikamet ettiğine dair kanıt",
      "İngilizce olmayan belgeler için çeviriler",
    ],
    application_steps: [
      "SkillSelect üzerinden EOI gönderin",
      "491 davetli yolunu seçin",
      "Eyalet/bölge adaylığı mı yoksa akraba sponsorluğu mu istediğinizi belirtin",
      "Adaylık, sponsorluk veya davet turunu bekleyin",
      "Seçilirseniz başvuru daveti alın",
      "Davet tarihinden itibaren 60 gün içinde ImmiAccount üzerinden başvurun",
      "Belgeleri yükleyip ilk başvuru ücretini ödeyin",
      "İstenirse ek bilgi taleplerine yanıt verin",
      "İstenirse sağlık muayenesi veya biyometriyi tamamlayın",
      "Başvuru sürecinde yasal statünüzü koruyun",
      "Yazılı vize sonucunu bekleyin",
    ],
    visa_conditions: [
      "5 yıl geçerli geçici vize",
      "Belirlenmiş bölgesel alanlarda yaşama, çalışma ve eğitim zorunluluğu",
      "Vize geçerliyken Avustralya'ya giriş çıkış",
      "Yurt dışında geçirilen süre vizeyi uzatmaz",
      "Uygunsa 3 yıl sonra 191 kalıcı oturumuna başvuru imkanı",
      "Bu vize uzatılamaz",
      "Vize sahibi aile üyeleri de bölgesel alanlarda yaşamalı/çalışmalı/eğitim görmelidir",
      "Tüm vize koşullarına ve Avustralya yasalarına uyulmalıdır",
    ],
    risks: [
      "Davet yoksa başvuru yapılamaz",
      "65 puan altı davet alınamamasına neden olur",
      "EOI beyanlarına göre davet puanı 65'in üzerinde olabilir",
      "Davet tarihinde yaş 45'in altında olmalıdır",
      "Beceri değerlendirmesi uygun ve geçerli olmalıdır",
      "Meslek ilgili listede olmalıdır",
      "Adaylık/sponsorluk geçerli olmalıdır",
      "Adaylık geri çekilirse vize verilmeyebilir",
      "Onaylanırsa yalnızca belirlenmiş bölgesel alanlarda yaşama/çalışma/eğitim şartı vardır",
      "491 sahipleri genelde 3 yıl dolmadan bazı kalıcı vizelere başvuramaz",
      "Eksik veya hatalı bilgi başvuruyu geciktirebilir veya olumsuz etkileyebilir",
    ],
  },
  "820_801": {
    key_requirements: [
      "Avustralya vatandaşı/daimi oturumlu/uygun Yeni Zelanda vatandaşı eş veya fiili partnerle gerçek bir ilişki içinde olmak",
      "Eşin veya fiili partnerin başvuru sahibi için sponsor olması",
      "Geçici 820 başvurusu sırasında Avustralya'da bulunmak",
      "Başvuruya dahil aile üyelerinin de Avustralya'da olması",
      "Geçici vize kararı verilirken Avustralya içinde veya dışında olmak",
      "Çoğu durumda 18 yaş veya üzerinde olmak",
      "Eş/fiili partner ilişki şartlarını karşılamak",
      "Sağlık şartlarını karşılamak",
      "Karakter şartlarını karşılamak",
      "Avustralya Hükümetine borç olmaması veya ödeme planı bulunması",
      "Gerekiyorsa Avustralya Değerler Beyanı'nı imzalamak",
    ],
    documents_required: [
      "Pasaport ve kimlik belgeleri",
      "Her iki ebeveyn adını içeren doğum belgesi veya kabul edilen alternatif kimlik belgesi",
      "Varsa ulusal kimlik kartı",
      "Varsa isim değişikliği kanıtı",
      "İlişki geçmişi beyanı",
      "Evliyseniz evlilik belgesi veya evliliğin Avustralya'da geçerli olduğuna dair kanıt",
      "Varsa fiili ilişki kanıtı",
      "Muafiyet yoksa en az 12 aylık fiili ilişki kanıtı",
      "Ortak finansal ilişki kanıtları (mortgage, kira, kredi, banka hesabı, fatura vb.)",
      "Ortak yaşam düzenine ilişkin kanıtlar",
      "Sosyal ilişki kanıtları (ortak davetler, seyahat, tanık beyanları vb.)",
      "Uzun vadeli bağlılık kanıtları",
      "Varsa önceki ilişkilere dair kanıtlar",
      "İstenirse sağlık muayenesi kanıtı",
      "Gerekliyse Avustralya polis belgesi",
      "Gerekliyse yurt dışı polis belgeleri",
      "Varsa askerlik kayıtları",
      "Sponsorun vatandaşlık/oturum durumunu gösteren kanıt",
      "Sponsor tarafından doldurulan partner sponsorluk formu",
      "Varsa bağımlı çocuk belgeleri",
      "18 yaş altı için ebeveyn sorumluluk belgeleri (varsa)",
      "İngilizce olmayan belgeler için çeviriler",
    ],
    application_steps: [
      "İlişki, kimlik, sponsorluk, sağlık, karakter ve aile belgelerini hazırlayın",
      "Avustralya'dayken ImmiAccount üzerinden online başvurun",
      "Family ve Stage 1 Partner or Prospective Marriage Visa seçin",
      "Başvuruyu tamamlayıp ücreti ödeyin",
      "Başvuruyu gönderin",
      "Sponsorla Transaction Reference Number/Application ID paylaşın",
      "Sponsor ImmiAccount üzerinden sponsorluk başvurusu yapsın",
      "Destekleyici belgeleri ekleyin",
      "Gerekliyse sağlık muayenelerini tamamlayın",
      "Gerekliyse karakter belgeleri ve polis kayıtlarını sunun",
      "İstenirse ek bilgi taleplerine yanıt verin",
      "Başvuru süresince Avustralya'da yasal statünüzü koruyun",
      "820 geçici vize için yazılı kararı bekleyin",
      "Uygun zamanda 801 kalıcı aşama için ek belgeleri sunun",
    ],
    visa_conditions: [
      "Avustralya'da yaşama, çalışma ve eğitim",
      "Vize süresince Avustralya'ya giriş çıkış",
      "Avustralya yasalarına ve vize koşullarına uyum",
      "Vize detayları için VEVO kullanımı",
      "801 uygunluğunu etkileyecek başka vize almamaya dikkat",
      "820 onaylandıktan sonra başvuruya aile üyesi eklenemez",
      "İlişki durumu, iletişim bilgileri, pasaport bilgileri veya çocuk doğumu gibi değişiklikleri bildirme",
    ],
    risks: [
      "İlişkinin sona ermesi geçici veya kalıcı partner vize sonucunu etkileyebilir",
      "Yetersiz ilişki kanıtı başvuruyu geciktirebilir veya olumsuz etkileyebilir",
      "Eksik sponsorluk bilgisi bazı durumlarda başvuruyu geçersiz kılabilir",
      "Esas vizesi olmayan başvuru sahipleri için ek kriterler uygulanabilir",
      "Bazı önceki ret/iptaller uygunluğu etkileyebilir",
      "Bazı bölgesel vize sahipleri başvuru öncesi 2-3 yıl beklemek zorunda olabilir",
      "No further stay koşulu başvuruyu engelleyebilir (kaldırılmadıkça)",
      "Sponsorun onaylanması gerekir",
      "Subclass 444 verilmesi bazı durumlarda 801 uygunluğunu etkileyebilir",
      "Başka bir vize verilirse 801 uygunluğu kaybedilebilir",
      "Yanlış/eksik bilgi gecikme, geçersizlik veya ret doğurabilir",
    ],
  },
  "485": {
    key_requirements: [
      "Başvuru sırasında Avustralya'da olmak",
      "Başvurudan önceki son 6 ay içinde bir dönemde Student visa (500) sahibi olmak",
      "CRICOS kayıtlı kurumdan uygun bir Avustralya niteliğini (lisans veya üzeri) tamamlamış olmak",
      "Çoğu durumda 50 yaş altında olmak (standart sınır 35 altı; bazı istisnalar olabilir)",
      "İngilizce şartlarını karşılamak",
      "Vize süresince kabul edilebilir sağlık sigortası bulundurmak",
      "Sağlık ve karakter şartlarını (polis belgesi dahil) karşılamak",
      "Avustralya Hükümetine ödenmemiş borcu olmamak",
      "18 yaş ve üzerindeyse Avustralya Değerler Beyanı'nı imzalamak",
    ],
    documents_required: [
      "Geçerli pasaport",
      "CRICOS kayıtlı kurumdan uygun mezuniyet kanıtı",
      "Son 6 ay içinde 500 vizesi sahibi olunduğuna dair kanıt",
      "Asgari eşiği karşılayan İngilizce sınav sonucu",
      "Sağlık sigortası kanıtı",
      "Avustralya polis belgesi",
      "Gerekliyse yurt dışı polis belgeleri",
      "Kimlik belgeleri ve varsa isim değişikliği kanıtı",
      "İstenirse sağlık muayenesi sonuçları",
      "Bağımlı dahil ediliyorsa aile belgeleri",
      "İngilizce olmayan belgeler için çeviriler",
    ],
    application_steps: [
      "Yaş, öğrenci vizesi süresi, nitelik ve İngilizce şartlarını teyit edin",
      "Nitelik, polis belgesi ve sigorta dahil tüm belgeleri toplayın",
      "Avustralya'dayken ImmiAccount üzerinden online başvurun",
      "Başvuru ücretini ödeyin",
      "İstenirse sağlık muayenesini tamamlayın",
      "İstenen polis belgeleri ve ek belgeleri sunun",
      "Ek bilgi taleplerine yanıt verin",
      "Yazılı vize sonucunu bekleyin",
    ],
    visa_conditions: [
      "Geçici vize; istihdamı başvuru sahibi bulur",
      "Vize uzatılamaz; ek kalış için yeni başvuru gerekir",
      "Uygunsa 485 ikinci akışa başvuru mümkün olabilir",
      "Vize süresince uygun sağlık sigortasını sürdürmek zorunludur",
      "Tüm vize koşulları ve Avustralya yasalarına uyulmalıdır",
      "Vize geçerliyken Avustralya'ya giriş çıkış yapılabilir",
      "Yurt dışında geçirilen süre vizeyi uzatmaz",
      "Koşullar değişirse Bakanlığı bilgilendirin",
    ],
    risks: [
      "Başvuru anında Avustralya'da olmak zorunludur",
      "Başvurudan önceki 6 ay içinde öğrenci vizesi sahibi olmak kritik bir şarttır",
      "Yaş şartları uygulanır; standart durumda genelde 35 yaş altı gerekir",
      "İngilizce sınav sonuçları minimum eşiği karşılamalıdır",
      "Nitelik CRICOS kayıtlı kurumdan lisans veya üzeri olmalıdır",
      "İstihdam ve sonraki yollar kişisel koşullara bağlıdır",
      "Vize, nitelikli göç yollarına geçiş garantisi vermez",
      "Eksik veya hatalı bilgi başvuruyu geciktirebilir veya olumsuz etkileyebilir",
    ],
  },
};

const zhHansStructuredData: LocaleVisaStructuredMap = {
  "500": {
    key_requirements: [
      "在澳大利亚境内或境外在线申请",
      "注册全日制课程并持有有效的入学确认函（CoE）",
      "持续持有海外学生健康保险（OSHC）",
      "年龄至少为6岁",
      "未满18岁需具备合规的监护安排",
      "在澳大利亚境内申请时需持有符合条件的实质性签证",
      "满足英语语言要求或符合豁免条件",
      "具备覆盖在澳期间的充足经济能力",
      "符合真实学生（Genuine Student）要求",
      "满足健康与品行要求",
      "18岁及以上需签署澳大利亚价值观声明",
      "已偿还欠澳大利亚政府的相关债务",
      "无影响资格的不良签证历史",
    ],
    documents_required: [
      "有效护照",
      "入学确认函（CoE）",
      "如需提供英语能力证明",
      "如需提供资金能力证明",
      "海外学生健康保险（OSHC）",
      "身份证明文件",
      "如需提供体检结果",
      "如需提供无犯罪证明",
      "未满18岁需提供监护及父母同意文件",
      "如适用，配偶与受抚养人相关文件",
      "非英文文件的认证翻译件",
    ],
    application_steps: [
      "提交申请前完成准备工作",
      "使用文件清单工具准备所需材料",
      "通过 ImmiAccount 在线提交申请",
      "上传材料并支付签证申请费，或提供费用豁免证明",
      "按要求补充提交额外信息",
      "如被要求，完成生物信息采集或体检",
      "等待书面签证结果",
    ],
    visa_conditions: [
      "持续就读于符合条件的课程",
      "遵守工作时长限制",
      "持续维持充分的健康保险",
      "遵守澳大利亚法律",
      "签证有效期内可自由出入澳大利亚",
      "该签证不可延期；需延长停留应重新申请新签证",
      "个人情况变化时需通知移民部门",
    ],
    risks: [
      "材料不完整可能导致审理延迟或被拒",
      "缺少或无效 CoE 可能导致申请无效",
      "错误或虚假信息可能导致拒签并影响后续签证",
      "资金证明不足可能导致拒签",
      "未持续持有 OSHC 可能引发合规问题",
      "既往拒签或签证取消记录可能影响资格",
      "未满足真实学生要求可能导致拒签",
    ],
  },
  "189": {
    key_requirements: [
      "职业需在相关技术职业清单上",
      "持有合格的职业评估",
      "获得申请邀请",
      "EOI 评分至少达到65分",
      "获邀时年龄低于45岁",
      "具备合格英语能力",
      "满足健康与品行要求",
    ],
    documents_required: [
      "意向申请（EOI）",
      "申请邀请函",
      "职业评估",
      "英语考试成绩",
      "身份证明文件",
      "支持打分主张的证明材料",
    ],
    application_steps: [
      "在 SkillSelect 提交 EOI",
      "等待获邀",
      "准备申请材料",
      "通过 ImmiAccount 提交申请",
      "上传材料",
      "等待签证结果",
    ],
    visa_conditions: [
      "永久居留签证",
      "可在澳大利亚任何地区生活与工作",
      "享有5年出入境权限",
      "可符合申请入籍条件",
    ],
    risks: [
      "未获邀请则无法申请",
      "分数偏低可能无法获邀",
      "不实主张可能导致拒签",
    ],
  },
  "190": {
    key_requirements: [
      "职业需在相关技术职业清单上",
      "持有与职业匹配的合格职业评估",
      "通过 SkillSelect 提交 EOI",
      "获得澳大利亚州或领地政府提名",
      "获得本签证申请邀请",
      "EOI 评分至少达到65分",
      "获邀时年龄低于45岁",
      "获邀时至少达到合格英语水平",
      "满足健康与品行要求",
      "已偿还欠澳大利亚政府的债务",
      "18岁及以上需签署澳大利亚价值观声明",
    ],
    documents_required: [
      "通过 SkillSelect 提交的 EOI",
      "申请邀请函",
      "州或领地提名证明",
      "合格职业评估",
      "身份证明文件",
      "合格英语证明",
      "支持打分主张的证明材料",
      "如适用，关系证明文件",
      "如需提供品行文件与无犯罪证明",
      "如被要求，体检结果",
      "如包含家属，需提供家属相关文件",
      "非英文文件的翻译件",
    ],
    application_steps: [
      "通过 SkillSelect 提交 EOI",
      "选择技术提名 190 子类签证",
      "等待州或领地政府可能发出的提名",
      "获提名后接收申请邀请",
      "在获邀后60个自然日内通过 ImmiAccount 在线申请",
      "上传材料并支付申请费",
      "如被要求，补充提交额外信息",
      "如被要求，完成体检或生物信息采集",
      "等待书面签证结果",
    ],
    visa_conditions: [
      "永久签证",
      "可在澳大利亚生活、工作和学习",
      "自签证获批日起5年内可多次出入境",
      "5年后再次入境可能需申请居民返程签证",
      "可为符合条件的亲属提供担保",
      "可符合申请澳大利亚国籍条件",
      "必须遵守澳大利亚法律",
    ],
    risks: [
      "未获州或领地提名将无法获得该签证邀请",
      "申请后若提名被撤回，申请将变为无效",
      "低于65分将无法获邀",
      "根据 EOI 声明，实际获邀分数可能高于65分",
      "获邀后必须证明打分主张",
      "获邀时年龄必须低于45岁",
      "职业评估必须合格且在有效期内",
      "职业必须在相关技术职业清单上",
      "各州和领地有各自的提名标准",
      "信息不完整或不准确可能导致审理延迟或不利结果",
    ],
  },
  "482": {
    key_requirements: [
      "需由获批担保方提名",
      "提名职业需在 Core Skills Occupation List 上",
      "薪资需达到市场薪资并不低于核心技能收入门槛",
      "在提名职业或相关领域具备至少1年经验",
      "如职业要求，需提供有效职业评估",
      "除豁免外，仅可为担保方或其关联实体工作",
      "除豁免外，需满足最低英语要求",
      "境内申请时需持有合适签证",
      "境内申请时需遵守过往签证条件",
      "需维持充分健康保险",
      "需满足健康与品行要求",
      "不得有为签证担保付费的不良记录",
      "不得有影响资格的拒签或取消记录",
      "不得欠澳大利亚政府债务",
      "18岁及以上需签署澳大利亚价值观声明",
    ],
    documents_required: [
      "有效护照",
      "雇主提名 Transaction Reference Number",
      "身份证明文件",
      "如适用，姓名变更证明",
      "如强制要求，职业评估参考号",
      "技能、资历与工作背景证明",
      "相关学历或资格证书",
      "如需，注册或执照证明",
      "简历",
      "工作证明/推荐信",
      "英语能力文件",
      "健康保险证明",
      "如需，体检结果",
      "如需，澳洲无犯罪证明",
      "如需，海外无犯罪证明",
      "如适用，服役记录",
      "如适用，配偶文件",
      "如适用，受抚养人文件",
      "如适用，18岁以下受抚养人监护责任文件",
      "非英文文件翻译件",
    ],
    application_steps: [
      "申请前准备提名、护照、所需职业评估及英语考试",
      "收集身份、技能、职业、英语、保险、品行与家庭文件",
      "通过 ImmiAccount 在线申请",
      "上传材料并支付申请费",
      "如被要求，补交材料",
      "如被要求，完成体检或生物信息采集",
      "审理期间保持合法居留",
      "等待书面结果",
    ],
    visa_conditions: [
      "在提名职业中工作",
      "通常仅为担保企业工作",
      "如由澳洲企业担保，可为其或关联实体工作",
      "入境后90天内或境内获批后90天内开始工作",
      "维持充分健康保险",
      "遵守澳大利亚法律",
      "签证有效期内可出入境",
      "离境时间不延长签证",
      "联系方式、雇主、就业、关系状态或子女出生变更需通知移民部门",
    ],
    risks: [
      "雇主提名未获批，签证无法获批",
      "材料不完整可能导致延迟或拒签",
      "如需职业评估但未在申请前启动，申请可能无效",
      "虚假或误导信息可能导致拒签并影响后续签证",
      "未满足英语要求会影响资格",
      "未维持健康保险可能违反签证条件",
      "既往拒签或取消记录可能影响资格",
      "近3年存在为担保付费行为可能影响资格",
      "若工作终止，可能需更换雇主或安排离境",
    ],
  },
  "491": {
    key_requirements: [
      "需获得州/领地提名或符合条件亲属担保",
      "职业需在相关技术职业清单上",
      "需具备合格职业评估",
      "需获得申请邀请",
      "需满足打分测试",
      "至少65分",
      "获邀时年龄低于45岁",
      "获邀时至少达到合格英语",
      "获批后需在指定偏远地区生活、工作和学习",
      "满足健康与品行要求",
      "已偿还政府债务",
      "18岁及以上需签署澳大利亚价值观声明",
    ],
    documents_required: [
      "SkillSelect EOI",
      "申请邀请函",
      "合格职业评估",
      "身份证明文件",
      "合格英语证明",
      "支持打分主张的证据",
      "如需，品行文件与无犯罪证明",
      "如需，体检结果",
      "如适用，配偶文件",
      "如适用，受抚养子女文件",
      "如为亲属担保，担保声明",
      "担保人符合亲属关系证明",
      "担保人18岁以上证明",
      "担保人公民/永居/符合条件新西兰公民证明",
      "担保人通常居住在指定地区证明",
      "非英文文件翻译件",
    ],
    application_steps: [
      "在 SkillSelect 提交 EOI",
      "选择 491 邀请通道",
      "说明申请州担保或亲属担保",
      "等待提名/担保/邀请轮次",
      "获选后接收邀请",
      "在60天内通过 ImmiAccount 申请",
      "上传材料并支付第一笔申请费",
      "如被要求，补交信息",
      "如被要求，完成体检或生物信息采集",
      "审理期间保持合法身份",
      "等待书面结果",
    ],
    visa_conditions: [
      "5年临时签证",
      "须在指定偏远地区生活、工作和学习",
      "签证有效期内可出入境",
      "离境时间不延长签证",
      "符合条件可在3年后申请191",
      "该签证不可延期",
      "持签家庭成员同样需在指定地区生活、工作和学习",
      "需遵守签证条件及澳大利亚法律",
    ],
    risks: [
      "未获邀请则无法申请",
      "低于65分通常无法获邀",
      "实际获邀分数可能高于65分",
      "获邀时年龄必须低于45岁",
      "职业评估必须有效且匹配",
      "职业必须在相关清单上",
      "提名或担保必须有效",
      "提名被撤回可能导致无法获签",
      "获批后仅可在指定偏远地区生活、工作和学习",
      "通常需持491满3年后方可申请部分永居签证",
      "信息不完整或不准确可能导致延迟或不利结果",
    ],
  },
  "820_801": {
    key_requirements: [
      "与澳大利亚公民/永居/符合条件新西兰公民配偶或事实伴侣关系真实",
      "需由配偶或事实伴侣担保",
      "申请820阶段时需在澳大利亚境内",
      "共同申请家庭成员也需在澳境内",
      "临时阶段审理时可在境内或境外",
      "多数情况下需年满18岁",
      "满足婚姻或事实伴侣关系要求",
      "满足健康要求",
      "满足品行要求",
      "无政府欠款或已安排偿还",
      "如要求，签署澳大利亚价值观声明",
    ],
    documents_required: [
      "护照及身份证明",
      "载明父母姓名的出生证明或可接受替代文件",
      "如有，国民身份证",
      "如适用，姓名变更证明",
      "关系历史陈述",
      "如已婚，结婚证或婚姻在澳有效证明",
      "如适用，事实伴侣关系证明",
      "如无豁免，至少12个月事实关系证明",
      "财务关系证明（联名房贷/租约/贷款/账户/账单等）",
      "共同生活证明",
      "社会关系证明（共同邀请、旅行、证人声明等）",
      "长期承诺证明",
      "如适用，既往关系证明",
      "如要求，体检证明",
      "如需，澳洲无犯罪证明",
      "如需，海外无犯罪证明",
      "如适用，服役记录",
      "担保人身份资格证明",
      "担保人填写的伴侣担保表格",
      "如适用，受抚养子女文件",
      "如适用，18岁以下申请人的监护责任文件",
      "非英文文件翻译件",
    ],
    application_steps: [
      "准备关系、身份、担保、健康、品行和家庭材料",
      "在澳期间通过 ImmiAccount 在线申请",
      "选择 Family 和 Stage 1 Partner or Prospective Marriage Visa",
      "完成申请并支付费用",
      "提交申请",
      "将 TRN 或 Application ID 提供给担保人",
      "担保人通过 ImmiAccount 提交担保申请",
      "上传支持材料",
      "如需，完成体检",
      "如需，提交品行及无犯罪材料",
      "如被要求，补交信息",
      "审理期间保持在澳合法身份",
      "等待820阶段书面决定",
      "到期后提交801阶段补充材料",
    ],
    visa_conditions: [
      "可在澳生活、工作和学习",
      "持签期间可出入境",
      "遵守澳大利亚法律与签证条件",
      "可通过 VEVO 查看签证信息",
      "避免获取影响801资格的其他签证",
      "820获批后不可再向该申请新增家庭成员",
      "关系、联系方式、护照信息或子女出生变化需通知移民部门",
    ],
    risks: [
      "关系破裂可能影响临时或永久阶段结果",
      "关系证据不足可能导致延迟或不利结果",
      "担保信息缺失在部分情形下可导致申请无效",
      "若申请人不持有实质性签证，可能适用额外标准",
      "既往拒签或取消记录可能影响资格",
      "部分偏远地区签证持有人可能需持签满2-3年后方可申请",
      "No further stay 条款未豁免时可能阻止申请",
      "担保人必须获批",
      "部分情况下444签证可能影响801资格",
      "如获批其他签证，可能失去801资格",
      "错误或不完整信息可能导致延迟、无效或拒签",
    ],
  },
  "485": {
    key_requirements: [
      "申请时必须在澳大利亚境内",
      "申请前6个月内曾持有500学生签证",
      "完成 CRICOS 注册机构的合格澳洲学历（本科及以上）",
      "多数情况年龄需在50岁以下（标准门槛通常35岁以下，部分可例外）",
      "满足英语要求",
      "全程持有可接受的健康保险",
      "满足健康与品行要求（含无犯罪证明）",
      "不得拖欠政府债务",
      "18岁及以上需签署澳大利亚价值观声明",
    ],
    documents_required: [
      "有效护照",
      "CRICOS 注册机构合格学历完成证明",
      "近6个月内持有500签证证明",
      "达到最低门槛的英语成绩",
      "健康保险证明",
      "澳洲无犯罪证明",
      "如需，海外无犯罪证明",
      "身份证明及如适用姓名变更证明",
      "如被要求，体检结果",
      "如包含家属，家属文件",
      "非英文文件翻译件",
    ],
    application_steps: [
      "确认年龄、学生签证时效、学历和英语要求",
      "收集学历、无犯罪和保险等全部材料",
      "在澳期间通过 ImmiAccount 在线申请",
      "支付签证申请费",
      "如被要求，完成体检",
      "提交无犯罪证明及其他补充材料",
      "按要求补交进一步信息",
      "等待书面结果",
    ],
    visa_conditions: [
      "临时签证，需自行就业",
      "签证不可延期，如需继续停留须重新申请",
      "符合条件可申请485第二阶段相关通道",
      "签证期间需持续维持可接受的健康保险",
      "必须遵守签证条件及澳大利亚法律",
      "签证有效期内可出入境",
      "离境时间不延长签证",
      "情况变化时需通知移民部门",
    ],
    risks: [
      "申请时必须在澳大利亚境内",
      "申请前6个月内曾持有学生签证是关键条件",
      "存在年龄门槛，标准申请人通常需低于35岁",
      "英语成绩需达到最低要求",
      "学历需为 CRICOS 注册机构本科及以上",
      "就业与后续路径取决于个人情况",
      "该签证不保证进入技术移民路径",
      "信息不完整或不准确可能导致延迟或不利结果",
    ],
  },
};

const localizedStructuredData: Record<string, LocaleVisaStructuredMap> = {
  tr: trStructuredData,
  "zh-Hans": zhHansStructuredData,
};

const localizedVisaFieldsData: Record<string, LocaleVisaFieldsMap> = {
  tr: trVisaFields,
  "zh-Hans": zhHansVisaFields,
};

export function localizeVisaFields<T extends Record<string, unknown>>(
  subclass: string,
  locale: string,
  visa: T
): T {
  const localeMap = localizedVisaFieldsData[locale];
  const localized = localeMap?.[subclass];
  if (!localized) return visa;

  return {
    ...visa,
    ...localized,
  } as T;
}

export function localizeVisaStructuredData<T extends Record<string, unknown> | null>(
  subclass: string,
  locale: string,
  structured: T
): T {
  if (!structured || typeof structured !== "object") return structured;

  const localeMap = localizedStructuredData[locale];
  const localized = localeMap?.[subclass];
  if (!localized) return structured;

  return {
    ...(structured as Record<string, unknown>),
    ...localized,
  } as T;
}
