/**
 * Writes docs/state-recheck-2026-27.md: which state and territory program pages need re-checking for the 2026-27 program year, and the source
 * files in data/knowledge to replace. Read only (reads the committed state rules); nothing else changes.
 *
 *   npx tsx scripts/list-state-recheck.ts
 */
import { writeFileSync } from "node:fs";
import { getStateRule } from "../lib/state-nomination/state-rules-config";

const CODES = ["ACT", "NSW", "NT", "QLD", "SA", "TAS", "VIC", "WA"] as const;
const REPORT_DATE = "2026-10-08";

const lines: string[] = [
  "# State and territory pages to re-check for the 2026-27 program year",
  "",
  `Generated by \`scripts/list-state-recheck.ts\` on ${REPORT_DATE} from \`lib/state-nomination/state-rules-config.ts\`. The 2026-27 program year began on 1 July 2026; every state's rule text below was written from a 2025-26 page, so each needs a check. The report flags any state whose data was checked more than 30 days before the report is viewed (\`data may have changed since\`).`,
  "",
  "For each state: the page(s) to open, the file(s) in `data/knowledge/State Immigrations/` to replace with a fresh capture (PDF or screenshot, same file name so `sourceDocument` stays valid), and which sentences in our data still describe 2025-26. After replacing a file, update the state's rule in `state-rules-config.ts` (note, keyFacts, `lastVerified`, `sourceDocument`) and `src/data/state-nomination-status.json` / `src/data/state-sponsorship.json` where they carry the same state.",
  "",
];

for (const code of CODES) {
  const r = getStateRule(code)!;
  const sources = r.sourceDocument.split(";").map((x) => x.trim()).filter(Boolean);
  const text = [r.note, r.aiSummary, ...r.keyFacts];
  const mention = (year: RegExp) => text.filter((x) => year.test(x)).map((x) => x.replace(/\s+/g, " ").slice(0, 170));
  const old = mention(/2025[-–/]26/);
  const next = mention(/2026[-–/]27/);
  lines.push(`## ${code}`, "", `- State: ${r.name}`, `- Status in our data: ${r.status} (last verified ${r.lastVerified})`);
  lines.push("- Open and re-capture:");
  for (const s of sources) lines.push(s.startsWith("data/knowledge/") ? `  - replace \`${s}\`` : `  - ${s} (a web page checked directly; re-check the page itself, no file to replace)`);
  lines.push(`- Sentences that still describe 2025-26 (${old.length}):`);
  for (const x of old.slice(0, 6)) lines.push(`  - ${x}`);
  lines.push(`- Sentences that already say what 2026-27 will bring (${next.length}):`);
  if (next.length === 0) lines.push("  - none: the 2026-27 settings are not described at all");
  for (const x of next.slice(0, 4)) lines.push(`  - ${x}`);
  lines.push("");
}

lines.push("## Also check", "", "- `src/data/state-nomination-status.json` and `src/data/state-sponsorship.json`: the generic dataset beneath the rules above (its own `lastVerified` per state).", "- The live admin State Nomination Config in the database takes priority over the rules file; update it in the admin panel after the files above.", "");
writeFileSync("docs/state-recheck-2026-27.md", lines.join("\n"));
console.log("wrote docs/state-recheck-2026-27.md");
