/**
 * CA ANZ migration skills assessment fees, read from the git-committed extraction
 * src/data/skills-assessment/caanz-fees.json (generated by scripts/generate-caanz-fees.ts from CA ANZ's own document,
 * data/knowledge/Skill Assessments/Chartered Accountants Australia and New Zealand/; provenance facts caanz_* in
 * src/data/fee-provenance.json). One AUD fee per assessment type, from 1 July 2026, with its processing time in
 * business days -- the document states no onshore / offshore / Singapore variant. This replaces the registry's earlier
 * figures, which were CPA Australia's (onshore/offshore/Singapore, Fast Track) copied under CA ANZ's name.
 */
import type { AuthorityFee, LocalizedString } from "./types";
import data from "@/src/data/skills-assessment/caanz-fees.json";

type Fee = (typeof data.fees)[number];

export const CAANZ_FEES_SOURCE = {
  document: data.sourceDocument,
  title: data.sourceTitle,
  pageCount: data.sourcePageCount,
  effectiveDate: data.effectiveDate,
  extractedDate: data.extractedDate,
} as const;

export function caanzFee(id: string): Fee {
  const fee = data.fees.find((f) => f.id === id);
  if (!fee) throw new Error(`caanz-fees.json has no "${id}" -- regenerate it (scripts/generate-caanz-fees.ts)`);
  return fee;
}

export const CAANZ_FEES: readonly Fee[] = data.fees;
export const CAANZ_OCCUPATIONS = data.occupations.list;

/** Business days -> the registry's processingTimeWeeks (5 business days = 1 week). */
export const businessDaysToWeeks = (days: number) => days / 5;

const LABELS: Record<string, LocalizedString> = {
  caanz_qualification_standard: { en: "Qualification assessment only – standard", tr: "Yalnızca nitelik değerlendirmesi – standart", "zh-Hans": "仅资格评估 – 标准" },
  caanz_qualification_express: { en: "Qualification assessment only – express", tr: "Yalnızca nitelik değerlendirmesi – ekspres", "zh-Hans": "仅资格评估 – 加急" },
  caanz_skilled_employment_standard: { en: "Skilled employment assessment only – standard", tr: "Yalnızca nitelikli istihdam değerlendirmesi – standart", "zh-Hans": "仅技术工作评估 – 标准" },
  caanz_skilled_employment_express: { en: "Skilled employment assessment only – express", tr: "Yalnızca nitelikli istihdam değerlendirmesi – ekspres", "zh-Hans": "仅技术工作评估 – 加急" },
  caanz_combined: { en: "Combined assessment (qualification and skilled employment)", tr: "Birleşik değerlendirme (nitelik ve nitelikli istihdam)", "zh-Hans": "联合评估（资格与技术工作）" },
};

/**
 * A registry fee entry for a CA ANZ assessment: the extracted amount, labelled, with a note giving the processing
 * time and the document page (the report shows it next to the amount: "AUD 565 (10 business days; CA ANZ p.45)").
 */
export function caanzRegistryFee(id: string): AuthorityFee {
  const f = caanzFee(id);
  const label = LABELS[id];
  if (!label) throw new Error(`caanz-fees.ts: no label for "${id}"`);
  return {
    label,
    amountAUD: f.amountAud,
    note: {
      en: `${f.processingBusinessDays} business days; CA ANZ document p.${f.page}`,
      tr: `${f.processingBusinessDays} iş günü; CA ANZ belgesi s.${f.page}`,
      "zh-Hans": `${f.processingBusinessDays} 个工作日；CA ANZ 文件第 ${f.page} 页`,
    },
  };
}
