import type { SkillsAssessmentAuthority, LocalizedString } from "../types";

/**
 * Vocational Education and Training Assessment Services (VETASSESS)
 * Source: "Am I Eligible to Apply with My Professional Occupation" + Trade Skills Assessment guides
 * Verified: 2026-08-04
 *
 * Multilanguage support: EN, TR, ZH-Hans
 * VETASSESS has two independent assessment services:
 *   1. Professional & Other Non-Trade — 341 occupations, standard skills assessment
 *   2. Trade Skills Assessment — licensed/non-licensed trades via TSS/OSAP programs
 */
export const vetassessAuthority: SkillsAssessmentAuthority = {
  authorityId: "VETASSESS",
  authorityName: "Vocational Education and Training Assessment Services",
  country: "AU",
    occupations: [
    { anzscoCode: "411111", title: "Ambulance Officer" },
    { anzscoCode: "141999", title: "Accommodation and Hospitality Managers nec" },
    { anzscoCode: "211111", title: "Actor" },
    { anzscoCode: "121111", title: "Aquaculture Farmer" },
    { anzscoCode: "421112", title: "Accounting Technician" },
    { anzscoCode: "211199", title: "Actors, Dancers and Other Entertainers nec" },
    { anzscoCode: "224111", title: "Actuary" },
    { anzscoCode: "252211", title: "Acupuncturist" },
    { anzscoCode: "225111", title: "Advertising Specialist" },
    { anzscoCode: "411212", title: "Dental Prosthetist" },
    { anzscoCode: "411211", title: "Dental Hygienist" },
    { anzscoCode: "311112", title: "Agricultural and Agritech Technician" },
    { anzscoCode: "234111", title: "Agricultural Consultant" },
    { anzscoCode: "234114", title: "Agricultural Research Scientist" },
    { anzscoCode: "234112", title: "Agricultural Scientist" },
    { anzscoCode: "311111", title: "Agricultural Technician" },
    { anzscoCode: "311113", title: "Animal Husbandry Technician" },
    { anzscoCode: "311114", title: "Aquaculture or Fisheries Technician" },
    { anzscoCode: "234115", title: "Agronomist" },
    { anzscoCode: "231199", title: "Air Transport Professionals nec" },
    { anzscoCode: "733112", title: "Aircraft Refueller" },
    { anzscoCode: "442211", title: "Alarm, Security or Surveillance Monitor" },
    { anzscoCode: "149111", title: "Amusement Centre Manager" },
    { anzscoCode: "361199", title: "Animal Attendants and Trainers nec" },
    { anzscoCode: "142112", title: "Antique Dealer" },
    { anzscoCode: "121311", title: "Apiarist" },
    { anzscoCode: "121213", title: "Fruit or Nut Grower" },
    { anzscoCode: "134411", title: "Faculty Head" },
    { anzscoCode: "234116", title: "Aquaculture or Fisheries Scientist" },
    { anzscoCode: "311212", title: "Cardiac Technician" },
    { anzscoCode: "272414", title: "Archaeologist" },
    { anzscoCode: "232111", title: "Architect" },
    { anzscoCode: "312111", title: "Architectural Draftsperson" },
    { anzscoCode: "312199", title: "Architectural, Building and Surveying Technicians nec" },
    { anzscoCode: "249211", title: "Art Teacher (Private Tuition)" },
    { anzscoCode: "611111", title: "Auctioneer" },
    { anzscoCode: "252711", title: "Audiologist" },
    { anzscoCode: "211211", title: "Composer" },
    { anzscoCode: "221211", title: "Company Secretary" },
    { anzscoCode: "451111", title: "Beauty Therapist" },
    { anzscoCode: "212311", title: "Art Director (Film, Television or Stage)" },
    { anzscoCode: "451311", title: "Funeral Director" },
    { anzscoCode: "141911", title: "Bed and Breakfast Operator" },
    { anzscoCode: "142113", title: "Betting Agency Manager" },
    { anzscoCode: "234513", title: "Biochemist" },
    { anzscoCode: "234514", title: "Biotechnologist" },
    { anzscoCode: "149911", title: "Boarding Kennel or Cattery Operator" },
    { anzscoCode: "234515", title: "Botanist" },
    { anzscoCode: "399511", title: "Broadcast Transmitter Operator" },
    { anzscoCode: "312112", title: "Building Associate" },
    { anzscoCode: "312113", title: "Building Inspector" },
    { anzscoCode: "312911", title: "Maintenance Planner" },
    { anzscoCode: "411611", title: "Massage Therapist" },
    { anzscoCode: "612111", title: "Business Broker" },
    { anzscoCode: "141111", title: "Cafe or Restaurant Manager" },
    { anzscoCode: "541111", title: "Call or Contact Centre Team Leader" },
    { anzscoCode: "399512", title: "Camera Operator (Film, Television or Video)" },
    { anzscoCode: "141211", title: "Caravan Park and Camping Ground Manager" },
    { anzscoCode: "839911", title: "Cement and Concrete Plant Worker" },
    { anzscoCode: "234915", title: "Exercise Physiologist" },
    { anzscoCode: "411311", title: "Diversional Therapist" },
    { anzscoCode: "252111", title: "Chiropractor" },
    { anzscoCode: "149912", title: "Cinema or Theatre Manager" },
    { anzscoCode: "312212", title: "Civil Engineering Technician" },
    { anzscoCode: "451711", title: "Flight Attendant" },
    { anzscoCode: "599211", title: "Clerk of Court" },
    { anzscoCode: "599915", title: "Clinical Coder" },
    { anzscoCode: "393299", title: "Clothing Trades Workers nec" },
    { anzscoCode: "222111", title: "Commodities Trader" },
    { anzscoCode: "272611", title: "Community Arts Worker" },
    { anzscoCode: "252299", title: "Complementary Health Therapists nec" },
    { anzscoCode: "149311", title: "Conference and Event Organiser" },
    { anzscoCode: "234911", title: "Conservator" },
    { anzscoCode: "312114", title: "Construction Estimator" },
    { anzscoCode: "133111", title: "Construction Project Manager" },
    { anzscoCode: "511111", title: "Contract Administrator" },
    { anzscoCode: "599111", title: "Conveyancer" },
    { anzscoCode: "212411", title: "Copywriter" },
    { anzscoCode: "132111", title: "Corporate Services Manager" },
    { anzscoCode: "272199", title: "Counsellors nec" },
    { anzscoCode: "599212", title: "Court Bailiff or Sheriff (Aus) \\ Court Collections Officer (NZ)" },
    { anzscoCode: "599213", title: "Court Orderly (Aus) \\ Court Registry Officer (NZ)" },
    { anzscoCode: "121299", title: "Crop Farmers nec" },
    { anzscoCode: "149212", title: "Customer Service Manager" },
    { anzscoCode: "121215", title: "Grape Grower" },
    { anzscoCode: "121313", title: "Dairy Cattle Farmer" },
    { anzscoCode: "311215", title: "Pharmacy Technician" },
    { anzscoCode: "232313", title: "Jewellery Designer" },
    { anzscoCode: "249212", title: "Dance Teacher (Private Tuition)" },
    { anzscoCode: "599311", title: "Debt Collector" },
    { anzscoCode: "121314", title: "Deer Farmer" },
    { anzscoCode: "441111", title: "Defence Force Member - Other Ranks" },
    { anzscoCode: "411214", title: "Dental Therapist" },
    { anzscoCode: "441311", title: "Detective" },
    { anzscoCode: "212312", title: "Director (Film, Television, Radio or Stage)" },
    { anzscoCode: "212313", title: "Director of Photography" },
    { anzscoCode: "399911", title: "Diver" },
    { anzscoCode: "452311", title: "Diving Instructor (Open Water)" },
    { anzscoCode: "452318", title: "Dog or Horse Racing Official" },
    { anzscoCode: "361111", title: "Dog Handler or Trainer" },
    { anzscoCode: "232312", title: "Industrial Designer" },
    { anzscoCode: "249213", title: "Drama Teacher (Private Tuition)" },
    { anzscoCode: "272112", title: "Drug and Alcohol Counsellor" },
    { anzscoCode: "249111", title: "Education Adviser" },
    { anzscoCode: "134499", title: "Education Managers nec" },
    { anzscoCode: "249112", title: "Education Reviewer" },
    { anzscoCode: "224911", title: "Electorate Officer" },
    { anzscoCode: "441211", title: "Emergency Service Worker" },
    { anzscoCode: "312999", title: "Building and Engineering Technicians nec" },
    { anzscoCode: "234521", title: "Entomologist" },
    { anzscoCode: "234311", title: "Conservation Officer" },
    { anzscoCode: "234312", title: "Environmental Consultant" },
    { anzscoCode: "251311", title: "Environmental Health Officer" },
    { anzscoCode: "234313", title: "Environmental Research Scientist" },
    { anzscoCode: "234399", title: "Environmental Scientists nec" },
    { anzscoCode: "149915", title: "Equipment Hire Manager" },
    { anzscoCode: "149913", title: "Facilities Manager" },
    { anzscoCode: "272113", title: "Family and Marriage Counsellor" },
    { anzscoCode: "311211", title: "Anaesthetic Technician" },
    { anzscoCode: "212314", title: "Film and Video Editor" },
    { anzscoCode: "212399", title: "Film, Television, Radio and Stage Directors nec" },
    { anzscoCode: "222112", title: "Finance Broker" },
    { anzscoCode: "222199", title: "Financial Brokers nec" },
    { anzscoCode: "222299", title: "Financial Dealers nec" },
    { anzscoCode: "149914", title: "Financial Institution Branch Manager" },
    { anzscoCode: "222311", title: "Financial Investment Adviser" },
    { anzscoCode: "222312", title: "Financial Investment Manager" },
    { anzscoCode: "222211", title: "Financial Market Dealer" },
    { anzscoCode: "451815", title: "First Aid Trainer" },
    { anzscoCode: "311311", title: "Fisheries Officer" },
    { anzscoCode: "149112", title: "Fitness Centre Manager" },
    { anzscoCode: "149411", title: "Fleet Manager" },
    { anzscoCode: "121611", title: "Flower Grower" },
    { anzscoCode: "234211", title: "Chemist" },
    { anzscoCode: "234212", title: "Food Technologist" },
    { anzscoCode: "452411", title: "Footballer" },
    { anzscoCode: "234113", title: "Forester" },
    { anzscoCode: "451399", title: "Funeral Workers nec" },
    { anzscoCode: "733113", title: "Furniture Removalist" },
    { anzscoCode: "222212", title: "Futures Trader" },
    { anzscoCode: "224212", title: "Gallery or Museum Curator" },
    { anzscoCode: "399311", title: "Gallery or Museum Technician" },
    { anzscoCode: "234411", title: "Geologist" },
    { anzscoCode: "234412", title: "Geophysicist" },
    { anzscoCode: "121315", title: "Goat Farmer" },
    { anzscoCode: "452412", title: "Golfer" },
    { anzscoCode: "232213", title: "Cartographer" },
    { anzscoCode: "452312", title: "Gymnastics Coach or Instructor" },
    { anzscoCode: "142114", title: "Hair or Beauty Salon Manager" },
    { anzscoCode: "451211", title: "Driving Instructor" },
    { anzscoCode: "134299", title: "Health and Welfare Services Managers nec" },
    { anzscoCode: "411511", title: "Aboriginal and Torres Strait Islander Health Worker" },
    { anzscoCode: "251999", title: "Health Diagnostic and Promotion Professionals nec" },
    { anzscoCode: "224213", title: "Health Information Manager" },
    { anzscoCode: "512211", title: "Health Practice Manager" },
    { anzscoCode: "252212", title: "Homoeopath" },
    { anzscoCode: "272411", title: "Historian" },
    { anzscoCode: "252213", title: "Naturopath" },
    { anzscoCode: "121316", title: "Horse Breeder" },
    { anzscoCode: "452313", title: "Horse Riding Coach or Instructor" },
    { anzscoCode: "311213", title: "Medical Laboratory Technician" },
    { anzscoCode: "139911", title: "Arts Administrator or Manager" },
    { anzscoCode: "423311", title: "Hospital Orderly" },
    { anzscoCode: "149999", title: "Hospitality, Retail and Service Managers nec" },
    { anzscoCode: "141311", title: "Hotel or Motel Manager" },
    { anzscoCode: "431411", title: "Hotel Service Manager" },
    { anzscoCode: "223111", title: "Human Resource Adviser" },
    { anzscoCode: "234413", title: "Hydrogeologist" },
    { anzscoCode: "311415", title: "Hydrographer" },
    { anzscoCode: "225213", title: "ICT Sales Representative" },
    { anzscoCode: "232412", title: "Illustrator" },
    { anzscoCode: "133311", title: "Importer or Exporter" },
    { anzscoCode: "121211", title: "Cotton Grower" },
    { anzscoCode: "611211", title: "Insurance Agent" },
    { anzscoCode: "222113", title: "Insurance Broker" },
    { anzscoCode: "599611", title: "Insurance Investigator" },
    { anzscoCode: "599612", title: "Insurance Loss Adjuster" },
    { anzscoCode: "599613", title: "Insurance Risk Surveyor" },
    { anzscoCode: "212212", title: "Book or Script Editor" },
    { anzscoCode: "224411", title: "Intelligence Officer" },
    { anzscoCode: "232212", title: "Surveyor" },
    { anzscoCode: "222313", title: "Investment Adviser" },
    { anzscoCode: "399411", title: "Jeweller" },
    { anzscoCode: "225311", title: "Public Relations Professional" },
    { anzscoCode: "139913", title: "Laboratory Manager" },
    { anzscoCode: "232311", title: "Fashion Designer" },
    { anzscoCode: "224511", title: "Land Economist" },
    { anzscoCode: "212111", title: "Artistic Director" },
    { anzscoCode: "224712", title: "Organisation and Methods Analyst" },
    { anzscoCode: "234511", title: "Life Scientist (General)" },
    { anzscoCode: "234599", title: "Life Scientists nec" },
    { anzscoCode: "121214", title: "Grain, Oilseed or Pasture Grower" },
    { anzscoCode: "591111", title: "Logistics Clerk" },
    { anzscoCode: "211112", title: "Dancer or Choreographer" },
    { anzscoCode: "234516", title: "Marine Biologist" },
    { anzscoCode: "225114", title: "Content Creator (Marketing)" },
    { anzscoCode: "225113", title: "Marketing Specialist" },
    { anzscoCode: "311312", title: "Meat Inspector" },
    { anzscoCode: "311411", title: "Chemistry Technician" },
    { anzscoCode: "232413", title: "Multimedia Designer" },
    { anzscoCode: "211212", title: "Music Director" },
    { anzscoCode: "249214", title: "Music Teacher (Private Tuition)" },
    { anzscoCode: "211213", title: "Musician (Instrumental)" },
    { anzscoCode: "212412", title: "Newspaper or Periodical Editor" },
    { anzscoCode: "251112", title: "Nutritionist" },
    { anzscoCode: "251312", title: "Occupational Health and Safety Adviser" },
    { anzscoCode: "512111", title: "Office Manager" },
    { anzscoCode: "399412", title: "Optical Mechanic" },
    { anzscoCode: "252112", title: "Osteopath" },
    { anzscoCode: "452912", title: "Outdoor Adventure Guide" },
    { anzscoCode: "211411", title: "Painter (Visual Arts)" },
    { anzscoCode: "234213", title: "Wine Maker" },
    { anzscoCode: "411714", title: "Parole or Probation Officer" },
    { anzscoCode: "212211", title: "Author" },
    { anzscoCode: "521111", title: "Personal Assistant" },
    { anzscoCode: "311412", title: "Earth Science Technician" },
    { anzscoCode: "621411", title: "Pharmacy Sales Assistant" },
    { anzscoCode: "234914", title: "Physicist" },
    { anzscoCode: "121318", title: "Pig Farmer" },
    { anzscoCode: "441312", title: "Police Officer" },
    { anzscoCode: "224412", title: "Policy Analyst" },
    { anzscoCode: "211412", title: "Potter or Ceramic Artist" },
    { anzscoCode: "121319", title: "Poultry Farmer" },
    { anzscoCode: "212413", title: "Print Journalist" },
    { anzscoCode: "442111", title: "Prison Officer" },
    { anzscoCode: "133612", title: "Procurement Manager" },
    { anzscoCode: "133511", title: "Production Manager (Forestry)" },
    { anzscoCode: "133512", title: "Production Manager (Manufacturing)" },
    { anzscoCode: "133513", title: "Production Manager (Mining)" },
    { anzscoCode: "311413", title: "Life Science Technician" },
    { anzscoCode: "511112", title: "Program or Project Administrator" },
    { anzscoCode: "133112", title: "Project Builder" },
    { anzscoCode: "139914", title: "Project Director" },
    { anzscoCode: "131112", title: "Sales and Marketing Manager" },
    { anzscoCode: "225412", title: "Sales Representative (Medical and Pharmaceutical Products)" },
    { anzscoCode: "612112", title: "Property Manager" },
    { anzscoCode: "272111", title: "Careers Counsellor" },
    { anzscoCode: "131114", title: "Public Relations Manager" },
    { anzscoCode: "591114", title: "Purchasing Officer" },
    { anzscoCode: "224211", title: "Archivist" },
    { anzscoCode: "612115", title: "Real Estate Representative" },
    { anzscoCode: "542111", title: "Receptionist (General)" },
    { anzscoCode: "223112", title: "Recruitment Consultant" },
    { anzscoCode: "272114", title: "Rehabilitation Counsellor" },
    { anzscoCode: "121312", title: "Beef Cattle Farmer" },
    { anzscoCode: "132511", title: "Research and Development Manager" },
    { anzscoCode: "142111", title: "Retail Manager (General)" },
    { anzscoCode: "234999", title: "Natural and Physical Science Professionals nec" },
    { anzscoCode: "139912", title: "Environmental Manager" },
    { anzscoCode: "452314", title: "Snowsport Instructor" },
    { anzscoCode: "272415", title: "Sociologist" },
    { anzscoCode: "133611", title: "Supply and Distribution Manager" },
    { anzscoCode: "232411", title: "Graphic Designer" },
    { anzscoCode: "452315", title: "Swimming Coach or Instructor" },
    { anzscoCode: "211113", title: "Entertainer or Variety Artist" },
    { anzscoCode: "249311", title: "Teacher of English to Speakers of Other Languages" },
    { anzscoCode: "225499", title: "Technical Sales Representatives nec" },
    { anzscoCode: "149211", title: "Call or Contact Centre Manager" },
    { anzscoCode: "452316", title: "Tennis Coach" },
    { anzscoCode: "252999", title: "Therapist nec" },
    { anzscoCode: "223311", title: "Training and Development Professional" },
    { anzscoCode: "272413", title: "Translator" },
    { anzscoCode: "451612", title: "Travel Consultant" },
    { anzscoCode: "542211", title: "Typist" },
    { anzscoCode: "242111", title: "University Lecturer" },
    { anzscoCode: "242112", title: "University Tutor" },
    { anzscoCode: "232611", title: "Urban and Regional Planner" },
    { anzscoCode: "232511", title: "Interior Designer" },
    { anzscoCode: "224311", title: "Economist" },
    { anzscoCode: "251911", title: "Health Promotion Officer" },
    { anzscoCode: "361311", title: "Veterinary Nurse" },
    { anzscoCode: "211499", title: "Visual Arts and Crafts Professionals nec" },
    { anzscoCode: "232414", title: "Web Designer" },
    { anzscoCode: "133312", title: "Wholesaler" },
    { anzscoCode: "223113", title: "Workplace Relations Adviser" },
    { anzscoCode: "234518", title: "Zoologist" },
  ],
  lastVerified: "2026-08-04",
  sourceDocument:
    "VETASSESS — Am I Eligible to Apply with My Professional Occupation (fees & document guide) + VETASSESS Pathway 1/Pathway 2 Trade Skills Assessment guides",
  pathways: [],
  validityPeriod: {
    years: 3,
    note: {
      en: "Renewal within 3 years of the original outcome costs a reduced renewal fee; renewal requested outside 3 years requires a full new skills assessment application.",
      tr: "Orijinal sonuçtan 3 yıl içinde yenileme, indirimli yenileme ücreti ile yapılır; 3 yıl sonra yenileme talebi için tam yeni beceri değerlendirmesi gerekir.",
      "zh-Hans": "原始结果3年内续期费用优惠；超过3年续期需提交全新的技能评估申请。",
    },
  },
  services: [
    // ── Service 1: Professional & Other Non-Trade ──────────────────────
    {
      serviceId: "professional-non-trade",
      pathways: [],
      serviceName: {
        en: "Professional & Other Non-Trade Occupations — Full Skills Assessment",
        tr: "Profesyonel ve Diğer Ticaret Dışı Meslekler — Tam Beceri Değerlendirmesi",
        "zh-Hans": "专业及其他非贸易职业 — 完整技能评估",
      },
      appliesTo: {
        en: "341 professional and other non-trade occupations",
        tr: "341 profesyonel ve diğer ticaret dışı meslek",
        "zh-Hans": "341个专业及其他非贸易职业",
      },
      fees: [
        {
          label: {
            en: "Online application (onshore, incl. GST)",
            tr: "Çevrimiçi başvuru (yurtiçi, KDV dahil)",
            "zh-Hans": "在线申请（澳洲境内，含GST）",
          },
          amountAUD: 1205.60,
        },
        {
          label: {
            en: "Online application (offshore, excl. GST)",
            tr: "Çevrimiçi başvuru (yurtdışı, KDV hariç)",
            "zh-Hans": "在线申请（澳洲境外，不含GST）",
          },
          amountAUD: 1096.0,
        },
        {
          label: {
            en: "Priority Processing Fee (onshore, incl. GST)",
            tr: "Öncelikli İşlem Ücreti (yurtiçi, KDV dahil)",
            "zh-Hans": "优先处理费（澳洲境内，含GST）",
          },
          amountAUD: 907.50,
        },
        {
          label: {
            en: "Priority Processing Fee (offshore, excl. GST)",
            tr: "Öncelikli İşlem Ücreti (yurtdışı, KDV hariç)",
            "zh-Hans": "优先处理费（澳洲境外，不含GST）",
          },
          amountAUD: 825.0,
        },
        {
          label: {
            en: "Employment only assessment (onshore, incl. GST)",
            tr: "Yalnızca istihdam değerlendirmesi (yurtiçi, KDV dahil)",
            "zh-Hans": "仅就业评估（澳洲境内，含GST）",
          },
          amountAUD: 669.90,
        },
        {
          label: {
            en: "Employment only assessment (offshore, excl. GST)",
            tr: "Yalnızca istihdam değerlendirmesi (yurtdışı, KDV hariç)",
            "zh-Hans": "仅就业评估（澳洲境外，不含GST）",
          },
          amountAUD: 609.0,
        },
        {
          label: {
            en: "Qualification and employment assessment (onshore, incl. GST)",
            tr: "Nitelik ve istihdam değerlendirmesi (yurtiçi, KDV dahil)",
            "zh-Hans": "资格和就业评估（澳洲境内，含GST）",
          },
          amountAUD: 1004.30,
        },
        {
          label: {
            en: "Qualification and employment assessment (offshore, excl. GST)",
            tr: "Nitelik ve istihdam değerlendirmesi (yurtdışı, KDV hariç)",
            "zh-Hans": "资格和就业评估（澳洲境外，不含GST）",
          },
          amountAUD: 913.0,
        },
      ],
      documentRequirements: [
        {
          en: "Resume / CV (academic studies incl. major projects, plus employment/career history).",
          tr: "Özgeçmiş (akademik çalışmalar dahil büyük projeler, ayrıca iş/kariyer geçmişi).",
          "zh-Hans": "简历/履历（包括学术研究、主要项目，以及工作/职业历史）。",
        },
        {
          en: "One recent (within 6 months) passport-sized colour photograph, not self-taken.",
          tr: "Son 6 ay içinde çekilmiş, selfie olmayan bir adet pasaport boyutunda renkli fotoğraf.",
          "zh-Hans": "一张近期（6个月内）的护照尺寸彩色照片（非自拍）。",
        },
        {
          en: "Proof of identity: 3 ID documents (min. 1 primary; combos: 2 primary + 1 secondary OR 1 primary + 2 secondary).",
          tr: "Kimlik kanıtı: 3 kimlik belgesi (en az 1 birincil; kombinasyonlar: 2 birincil + 1 ikincil VEYA 1 birincil + 2 ikincil).",
          "zh-Hans": "身份证明：3份身份证件（至少1份主要证件；组合方式：2份主要+1份次要或1份主要+2份次要）。",
        },
        {
          en: "Evidence of legal name change if applicable (statutory declarations NOT accepted).",
          tr: "Yasal isim değişikliği kanıtı (varsa) (yeminli beyanlar KABUL EDİLMEZ).",
          "zh-Hans": "法定姓名变更证明（如适用）（不接受法定声明）。",
        },
        {
          en: "Qualification award certificate (or provisional certificate / official statement of completion if not yet issued) plus complete academic transcript.",
          tr: "Nitelik ödül sertifikası (veya geçici sertifika / resmi tamamlama beyanı henüz verilmediyse)艺术artı tam akademik transkript.",
          "zh-Hans": "资格授予证书（或临时证书/未发证时的官方完成声明）加完整学术成绩单。",
        },
        {
          en: "Additional verification required for qualifications from the People's Republic of China (PRC) — see notes.",
          tr: "Çin Halk Cumhuriyeti (PRC) nitelikleri için ek doğrulama gerekir — notlara bakın.",
          "zh-Hans": "中华人民共和国学历需额外验证——详见备注。",
        },
        {
          en: "Statutory declaration permitted only to supplement official employment documentation, never as sole evidence of employment dates or payment.",
          tr: "Yeminli beyan yalnızca resmi istihdam belgelerini tamamlamak için izin verilir, iş tarihleri veya ödeme için tek kanıt olarak hiçbir zaman kabul edilmez.",
          "zh-Hans": "法定声明仅用于补充官方就业文件，永远不能作为就业日期或薪酬的唯一证据。",
        },
      ],
      notes: [
        {
          en: "Qualification must be at the AQF-comparable educational level required for the nominated occupation.",
          tr: "Nitelik, adı geçen meslek için gerekli AQF karşılaştırılabilir eğitim düzeyinde olmalıdır.",
          "zh-Hans": "学历必须达到提名职业所要求的AQF可比教育水平。",
        },
        {
          en: "An Australian Graduate Diploma (or comparable overseas postgraduate diploma) is never treated as comparable to an Australian Bachelor degree, alone or combined with underpinning sub-degree qualifications.",
          tr: "Avustralya Lisansüstü Diploması (veya karşılaştırılabilir yurtdışı lisansüstü diploması) tek başına veya alt derece niteliklerle birleştirildiğinde hiçbir zaman Avustralya Lisans Derecesi ile eşdeğer olarak değerlendirilmez.",
          "zh-Hans": "澳大利亚研究生文凭（或可比的海外研究生文凭），无论单独还是与基础副学位资格结合，均不被视为等同于澳大利亚学士学位。",
        },
        {
          en: "'Highly relevant field of study' is assessed against multiple factors: major/specialisation match, depth and breadth of study, employment outcomes of the qualification in its home country, and course requirements (thesis, major projects, internships).",
          tr: "'Yüksek düzeyde ilişkili çalışma alanı', birden fazla faktöre göre değerlendirilir: ana dal/uzmanlık eşleşmesi, çalışmanın derinliği ve genişliği, niteliğin bulunduğu ülkedeki istihdam sonuçları ve ders gereksinimleri (tez, büyük projeler, stajlar).",
          "zh-Hans": "'高度相关专业领域'根据多个因素评估：专业/方向匹配度、学习的深度和广度、资格在本国的就业成果以及课程要求（论文、大型项目、实习）。",
        },
        {
          en: "Sufficient years of highly relevant employment within the last 5 years can compensate for a qualification that is not in a highly relevant major field of study.",
          tr: "Son 5 yıl içinde yeterli yıl yüksek düzeyde ilişkili istihdam, yüksek düzeyde ilişkili ana dal alanında olmayan bir niteliği telafi edebilir.",
          "zh-Hans": "过去5年内足够的高度相关就业年限可以弥补专业非高度相关的情况。",
        },
      ],
    },
    // ── Service 2: Trade Skills Assessment ──────────────────────────────
    {
      serviceId: "trade-skills-assessment",
      pathways: [],
      serviceName: {
        en: "Trade Skills Assessment",
        tr: "Ticari Beceri Değerlendirmesi",
        "zh-Hans": "贸易技能评估",
      },
      appliesTo: {
        en: "Licensed and non-licensed trade occupations (e.g. Electrician, Plumber, Air-conditioning/Refrigeration Mechanic)",
        tr: "Lisanslı ve lisanssız ticari meslekler (ör. Elektrikçi, Tesisatçı, Klima/Soğutma Mekaniği)",
        "zh-Hans": "持证和非持证贸易职业（如电工、水管工、空调/制冷技工）",
      },
      programs: [
        {
          name: {
            en: "Temporary Skills Shortage (TSS) Skills Assessment Program",
            tr: "Geçici Beceri Kıtlığı (TSS) Beceri Değerlendirmesi Programı",
            "zh-Hans": "临时技能短缺（TSS）技能评估项目",
          },
          purpose: {
            en: "For Skills in Demand visa (temporary work) applications.",
            tr: "Talep Edilen Beceriler Vizesi (geçici çalışma) başvuruları için.",
            "zh-Hans": "用于需求技能签证（临时工作）申请。",
          },
        },
      ],
      fees: [
        {
          label: {
            en: "TSS skills assessment application fee",
            tr: "TSS beceri değerlendirmesi başvuru ücreti",
            "zh-Hans": "TSS技能评估申请费",
          },
          amountAUD: undefined,
          note: "Not stated in source document; confirm via VETASSESS portal.",
        },
      ],
      documentRequirements: [
        {
          en: "Evidence of Australian qualification(s).",
          tr: "Avustralya nitelik(leri) kanıtı.",
          "zh-Hans": "澳洲资格证明。",
        },
        {
          en: "Evidence of work experience — minimum 3 years full-time (or part-time equivalent) at the skill level required.",
          tr: "İş deneyimi kanıtı — gerekli beceri seviyesinde minimum 3 yıl tam zamanlı (veya tam zamanlı eşdeğeri).",
          "zh-Hans": "工作经验证明 — 在所需技能水平上至少3年全职（或同等兼职）。",
        },
      ],
      competencyAssessment: {
        portfolioProjectsMin: 0,
        portfolioProjectsMax: 0,
        interviewDurationMinutes: 120,
        topicAreas: [
          {
            en: "Qualification and work experience evidence review",
            tr: "Nitelik ve iş deneyimi kanıtı incelemesi",
            "zh-Hans": "资格和工作经验证明审查",
          },
          {
            en: "Technical interview",
            tr: "Teknik mülakat",
            "zh-Hans": "技术面试",
          },
        ],
      },
      notes: [
        {
          en: "Outcome for both pathways is a Skills Assessment Result Letter with a 'Suitable' or 'Not Suitable' determination.",
          tr: "Her iki yol için sonuç, 'Uygun' veya 'Uygun Değil' belirlemesi içeren bir Beceri Değerlendirme Sonucu Mektubudur.",
          "zh-Hans": "两条路径的结果均为包含'适合'或'不适合'判定的技能评估结果信。",
        },
        {
          en: "Unsuccessful applicants may apply for reassessment or review.",
          tr: "Başarısız başvurular yeniden değerlendirme veya inceleme için başvurabilir.",
          "zh-Hans": "未通过的申请人可申请重新评估或审查。",
        },
        {
          en: "Technical interview rules: arriving more than 30 minutes late cancels the interview; no reference materials or internet-connected devices allowed; interview is recorded; assessor cannot disclose results on the day.",
          tr: "Teknik mülakat kuralları: 30 dakikadan fazla geç kalınması mülakatı iptal eder; referans materyalleri veya internet bağlantılı cihazlara izin verilmez; mülakat kaydedilir; değerlendirici sonuçları aynı gün açıklayamaz.",
          "zh-Hans": "技术面试规则：迟到超过30分钟取消面试；不允许携带参考资料或联网设备；面试过程录音；评估员不得当场透露结果。",
        },
        {
          en: "Interview may be cancelled if the candidate cannot prove identity, cannot understand/answer questions in English, becomes distressed, appears unwell, becomes angry/violent, or arrives intoxicated/drugged.",
          tr: "Mülakat, aday kimliğini doğrulayamazsa, İngilizce soruları anlayamaz/cevaplayamazsa, strese girerse, hasta görünürse, sinirli/shiddetli olursa veya sarhoş/uyuşturucu etkisi altında gelirse iptal edilebilir.",
          "zh-Hans": "如果申请人无法证明身份、无法理解/回答英语问题、情绪紧张、身体不适、愤怒/暴力或醉酒/吸毒到场，面试可能被取消。",
        },
      ],
    },
  ],
  excludedEvidence: [
    {
      en: "Statutory declarations or affidavits as sole evidence of employment dates or payment (must be supported by official documentation such as tax records, signed contracts, appointment letters, job descriptions).",
      tr: "İş tarihleri veya ödemeler için tek kanıt olarak yeminli beyanlar veya yeminli ifadeler (vergi kayıtları, imzalı sözleşmeler, atama mektupları, iş tanımları gibi resmi belgelerle desteklenmelidir).",
      "zh-Hans": "作为就业日期或薪酬唯一证据的法定声明或宣誓书（必须有税务记录、签署合同、任命信、职位描述等官方文件支持）。",
    },
    {
      en: "Statutory declarations as evidence of legal name change.",
      tr: "Yasal isim değişikliği kanıtı olarak yeminli beyanlar.",
      "zh-Hans": "作为法定姓名变更证据的法定声明。",
    },
  ],
};
